TrenchBroom/TrenchBroom

- Build.txt
- Remove step to install FreeImage because it's bundled with TB.
- Add a step to install cmake and ninja
- Add a step with instructions on using cmake
> Build.txt: updates to Mac instructions:

- .gitignore
- common/src/View/ActionManager.cpp
- common/src/View/CommandIds.h
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/src/View/SplitterWindow2.cpp
- common/src/View/SplitterWindow2.h
Hello,
I implemented Feature Request #913 please review the code.
Hiding of the panels is done by maximizing the opposing one.
> #913 hide gui panels

- test/src/IO/DefParserTest.cpp
- test/src/IO/FgdParserTest.cpp
- test/src/View/GetVersion.cpp
Minor fixes because testcases wouldn't compile.
> Test fixes

- common/src/Exceptions.h
- common/src/Macros.h
- common/src/Renderer/GL.h
- common/src/TrenchBroomStackWalker.cpp
- common/src/TrenchBroomStackWalker.h
- common/src/View/EntityAttributeGridTable.cpp
- common/src/View/Tool.h
- test/src/EnsureTest.cpp
- test/src/ExceptionsTest.cpp
Update EntityAttributeGridTable to use `ensure()`.
> New `ensure(condition, message)` macro.

- common/src/Model/EntityRotationPolicy.cpp
See: https://github.com/kduske/TrenchBroom/issues/1418#issuecomment-252390777
> Fix rendering of angle -1/-2, up and down were backwards.

- common/src/Assets/Md2Model.cpp
- common/src/CollectionUtils.h
- common/src/Macros.h
- common/src/Model/GameConfig.cpp
- common/src/StringMap.h
- common/src/View/CellLayout.h
- common/src/View/ControlListBox.cpp
- common/src/View/EntityDefinitionFileChooser.cpp
- common/src/View/FileTextureCollectionEditor.cpp
- common/src/View/FlagsEditor.cpp
- common/src/View/GameListBox.cpp
- common/src/View/LayerListBox.cpp
- common/src/View/ModEditor.cpp
- common/src/View/RadioGroup.cpp
- common/src/View/RecentDocumentListBox.cpp
- common/src/View/TabBar.cpp
- common/src/View/ViewEditor.cpp
- common/src/View/wxKeyStrings.cpp
Related to https://github.com/kduske/TrenchBroom/issues/1466
> Change bounds checks from assert() to ensure()

- .travis.yml
- travis-linux.sh
- travis-macos.sh
Here's what the output looks like, this is for my fork: https://travis-ci.org/ericwa/TrenchBroom
The mac builds on travis are stuck right now (it's a problem on their end) but it passed for me earlier.
> travis-ci config and build scripts for Ubuntu 14.04 and macOS

- common/src/View/VertexToolController.cpp
> #1489: Allow to start a vertex drag while holding shift AND alt.

- common/src/View/MoveToolController.h
- common/src/View/ToolController.cpp
- common/src/View/ToolController.h
- common/src/View/VertexToolController.cpp
> 1488: Vertex tool: Support "Shift to snap to grid" on a drag in progress

- common/src/Model/EmptyAttributeNameIssueGenerator.cpp
- common/src/Model/EmptyAttributeValueIssueGenerator.cpp
- common/src/Model/LinkSourceIssueGenerator.cpp
- common/src/Model/LinkTargetIssueGenerator.cpp
- common/src/Model/LongAttributeNameIssueGenerator.cpp
- common/src/Model/LongAttributeValueIssueGenerator.cpp
- common/src/Model/MapFacade.h
- common/src/Model/PushSelection.cpp
- common/src/Model/PushSelection.h
- common/src/View/MapViewBase.cpp
> Move brushes to ..." should select all brushes in the resulting merged func

- Resources/games/HalfLife.cfg
- common/src/Assets/Palette.cpp
- common/src/Assets/Palette.h
- common/src/IO/HlMipTextureReader.cpp
- common/src/IO/HlMipTextureReader.h
- common/src/IO/IdMipTextureReader.cpp
- common/src/IO/IdMipTextureReader.h
- common/src/IO/TextureLoader.cpp
> Partial Half-Life support

- common/src/Assets/Texture.cpp
- common/src/Assets/Texture.h
- common/src/IO/CharArrayReader.cpp
- common/src/IO/FreeImageTextureReader.cpp
- common/src/IO/FreeImageTextureReader.h
- common/src/IO/TextureLoader.cpp
- common/src/IO/TextureReader.cpp
- common/src/Renderer/GL.h
Hello,
I've added a FreeImageTextureLoader class and the ability to load generic (png, tga, etc) textures into the texture collections.
> Freeeimage textures

- common/src/Polyhedron.h
- common/src/Polyhedron_Misc.h
- test/src/PolyhedronTest.cpp
Issue: https://github.com/kduske/TrenchBroom/issues/1542
> 1542: Don't attempt to copy polyhedron elements if they are empty.

- common/src/Model/CollectContainedNodesVisitor.h
- common/src/Model/CollectTouchingNodesVisitor.h
- test/src/View/SelectionTest.cpp
> 1530: Don't recurse when collecting selectable objects

- appveyor.yml
> #1598: Use github token with access to TrenchBroom repo.

- common/src/IO/DefParser.cpp
- common/src/IO/ELParser.cpp
- common/src/IO/FgdParser.cpp
- common/src/IO/LegacyModelDefinitionParser.cpp
- common/src/IO/StandardMapParser.cpp
- common/src/IO/Tokenizer.cpp
- common/src/IO/Tokenizer.h
- test/src/IO/ELParserTest.cpp
- test/src/IO/TokenizerTest.cpp
> Add support for selecting escapable characters in tokenizer.

- cmake/TrenchBroomTest.cmake
- common/src/IO/DefParser.cpp
- common/src/IO/ELParser.cpp
- common/src/IO/FgdParser.cpp
- common/src/IO/LegacyModelDefinitionParser.cpp
- common/src/IO/StandardMapParser.cpp
- common/src/IO/Tokenizer.h
- test/src/IO/GameConfigParserTest.cpp
- test/src/IO/TokenizerTest.cpp
- test/src/IO/WadFileSystemTest.cpp
> Fix a problem with the compiler choosing the wrong constructor due to default parameters.

- app/resources/games/Quake/Quake.fgd
> #1628: Set default wait value for trigger_multiple to 0.2.

- common/src/Renderer/Camera.cpp
- common/src/View/ClipToolController.cpp
- common/src/View/ClipToolController.h
- common/src/View/CreateComplexBrushToolController3D.cpp
- common/src/View/CreateSimpleBrushToolController2D.cpp
- common/src/View/CreateSimpleBrushToolController2D.h
- common/src/View/CreateSimpleBrushToolController3D.cpp
- common/src/View/CreateSimpleBrushToolController3D.h
- common/src/View/MoveObjectsToolController.cpp
- common/src/View/MoveObjectsToolController.h
- common/src/View/MoveToolController.h
- common/src/View/RotateObjectsToolController.cpp
- common/src/View/ToolController.cpp
- common/src/View/ToolController.h
- common/src/View/VertexToolController.cpp
- test/src/View/MoveToolControllerTest.cpp
Closes #1625.
@ericwa Please test this thoroughly. It may affect every tool in which the user moves things around with the mouse. I did give it a test drive myself, but I'd like your input, too.
> Add more state to restricted drag tool and handle snapper change correctly.

- common/src/IO/SystemPaths.cpp
> Allow resources in app directory on linux

- app/resources/documentation/manual/index.md
- common/src/View/LaunchGameEngineDialog.cpp
> #1638: Show message dialog when an exception occurs while launching a game engine

- common/src/EL/ELExceptions.cpp
- common/src/View/CompilationRunner.cpp
> #1641: Print an error message when an error occurs while interpolating EL expression in compilation window.

- app/resources/documentation/manual/index.md
- common/src/Model/GameEngineConfig.cpp
> #1640: Fix a bug that prevented game engine profiles from being persisted properly.

- common/src/View/MapView3D.cpp
> #1661: Make sure to reset fly keys when 3D view loses focus.

- common/src/Polyhedron_ConvexHull.h
- common/src/View/ClipTool.cpp
- common/src/View/UVShearTool.cpp
- test/src/PolyhedronTest.cpp
> #1659: Ensure that points on the boundary are not added to a polygon.

- common/src/View/MapFrame.cpp
> #1665: Show state of info / inspector toggles in menu items.

- common/src/IO/DiskFileSystem.cpp
- common/src/Model/GameImpl.cpp
- common/src/TrenchBroomApp.cpp
> #1668: Show sensible error message if game file system could not be initialized

- common/src/Renderer/MapRenderer.cpp
- common/src/View/ResizeBrushesTool.cpp
- common/src/View/ResizeBrushesTool.h
- common/src/View/ResizeBrushesToolController.cpp
- common/src/View/ResizeBrushesToolController.h
- common/src/View/SelectionTool.cpp
- common/src/View/ToolBoxConnector.cpp
- common/src/View/ToolBoxConnector.h
Closes #1677. Also fixed some other minor things that came up, see the commit messages.
> #1677: Fix behavior when switching selection mode due to double click while holding Ctrl/Cmd.

- travis-macos.sh
Should fix https://github.com/kduske/TrenchBroom/issues/1681 , I'm running a build locally at the moment to check
> #1681: Tell wxWidgets to build its own libpng/libtiff/libjpeg

- common/src/StringUtils.h
- common/src/View/SmartAttributeEditorManager.cpp
- common/src/View/SmartAttributeEditorMatcher.cpp
- common/src/View/SmartAttributeEditorMatcher.h
- test/src/StringUtilsTest.cpp
> #1655: Show color editor for any entity property matching *_color, *_colour, or *_color2.

- common/src/View/SmartColorEditor.cpp
- common/src/View/SmartColorEditor.h
> #1655: Ensure that worldspawn colors are treated correctly in smart entity color editor.

- common/src/IO/SystemPaths.cpp
> #1689: Allow using TB_DEV_MODE on FreeBSD.

- common/src/Model/EntityRotationPolicy.cpp
- common/src/Model/EntityRotationPolicy.h
> #1702: Correct arrow direction for info_intermission

- common/src/View/UVView.cpp
- common/src/View/UVView.h
Set the m_helper face to nullptr and disable m_toolBox
Should fix https://github.com/kduske/TrenchBroom/issues/1700
> #1700: UVView: listen for document->documentWasClearedNotifier

- common/src/Model/Brush.cpp
- test/src/Model/BrushTest.cpp
> #1710: Don't allow moving all vertices out of world bounds

- app/resources/games/Quake.cfg
- app/resources/games/Quake2.cfg
> 1713: Fix for "hintskip" not being considered "hint"

- common/src/Model/BrushFace.cpp
- common/src/Model/BrushFace.h
- common/src/Model/ParallelTexCoordSystem.cpp
- common/src/Model/ParallelTexCoordSystem.h
- common/src/Model/TexCoordSystem.cpp
- common/src/Model/TexCoordSystem.h
- common/src/View/CopyTexCoordSystemFromFaceCommand.cpp
- common/src/View/CopyTexCoordSystemFromFaceCommand.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapDocumentCommandFacade.h
- common/src/View/SetBrushFaceAttributesTool.cpp
Fixes #1790 (the test case I gave there at least) and also fixes https://github.com/kduske/TrenchBroom/issues/1753
> 1790: Fix alt+click for Valve maps

- Build.md
> 1785: Describe TB_DEV_MODE in Build.md

- Build.md
> 1373: add warning to avoid Address Sanitizer in Xcode

- common/src/View/MapViewBase.cpp
> 1748: Update "Move Brushes to World" menu item's enabled/disabled state

- common/src/View/VertexTool.cpp
> Cannot change vertex selection by clicking on already-selected vertex

- common/src/Model/CompilationProfile.cpp
- common/src/Model/CompilationProfile.h
- common/src/View/CompilationTaskList.cpp
- common/src/View/ELAutoCompleteHelper.cpp
- test/src/VecTest.cpp
> Crash while excluding compiling profile

- common/src/View/MapViewBase.cpp
> Point entities can be "Added to" brush entities

- common/src/View/ViewPreferencePane.cpp
- common/src/View/ViewPreferencePane.h
> 1724: Options to change colours of grid and brush outlines

- common/src/Preferences.cpp
- common/src/Preferences.h
- common/src/View/FlyModeHelper.cpp
- common/src/View/MousePreferencePane.cpp
- common/src/View/MousePreferencePane.h
- common/src/View/PreferenceDialog.cpp
- common/src/View/PreferencePane.cpp
- common/src/View/PreferencePane.h
> 1722: Option to change the WASD flymode speed

- common/src/Assets/EntityModelManager.cpp
- common/src/Model/GameFactory.cpp
- common/src/Model/GameFactory.h
- common/src/Model/GameImpl.cpp
- common/src/Model/GameImpl.h
- common/src/PreferenceManager.h
- common/src/View/GamesPreferencePane.cpp
- common/src/View/GamesPreferencePane.h
> 1777: Setting an invalid game path causes a crash

- common/src/Model/BrushFace.cpp
- common/src/Model/BrushFace.h
- common/src/Plane.h
- common/src/Polyhedron_Clip.h
- common/src/Polyhedron_ConvexHull.h
- test/src/Model/BrushTest.cpp
- test/src/PolyhedronTest.cpp
> 1801: .map that crashes on load

- .github/issue_template.md
> 1755: Issue template

- common/src/View/RotateObjectsToolController.cpp
> 1729: Can't move down rotator widget with ALT without moving widget horizontally

- common/src/Preference.h
- common/src/PreferenceManager.cpp
- common/src/PreferenceManager.h
- common/src/View/KeyboardPreferencePane.cpp
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/src/View/MapView2D.cpp
- common/src/View/MapView3D.cpp
- common/src/View/MapViewBase.cpp
Closes #1762 
@ericwa I could only partially replicate the problem in my Windows VM. Could you try to verify if my changes fix the problem?
> 1762: Update accelerator table when preferences change.

- common/src/View/CellLayout.h
...Let's try this again. Sorry if I'm doing this wrong, this is my first pull request to anything
> Fix compile error caused by two floats being called as if they were functions

- common/src/View/MapViewBase.cpp
It should show if we are inside a group, and there is something selected
Fixes #1879
> 1879: Fix condition to show "Remove Objects from Group" menu item

- common/src/View/Console.cpp
> 1885: add IsBeingDeleted check to Console::logToConsole

- common/src/Model/Brush.cpp
- test/src/View/MapDocumentTest.cpp
- test/src/View/MapDocumentTest.h
> 1896: Transfer Valve texturing with CSG Subtract/Merge

- Build.md
> 1912: clarify VS2017 setup instructions

- common/src/View/DirectoryTextureCollectionEditor.cpp
> 1927: Cannot remove directory based texture collections

- common/src/View/MapFrame.cpp
- common/src/View/ResizeBrushesTool.cpp
> 1861: Crash when extruding new brush

- common/src/Preferences.cpp
- common/src/Preferences.h
- common/src/View/FlyModeHelper.cpp
- common/src/View/FlyModeHelper.h
- common/src/View/MousePreferencePane.cpp
- common/src/View/MousePreferencePane.h
> 1854: Fly mode would be better with keys to up and down

- common/src/Model/EntityAttributeSnapshot.h
- common/src/View/ChangeEntityAttributesCommand.cpp
- common/src/View/EntityAttributeGridTable.cpp
- common/src/View/EntityAttributeGridTable.h
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapDocumentCommandFacade.h
> 1915: Unwanted behaviour when entering keys and undoing

- app/resources/documentation/manual/shortcuts_helper.js
- appveyor.bat
- appveyor.yml
> 1903 / 1902: Correctly transform manual keyboard shortcuts on Windows builds

- common/src/View/CompilationRunner.cpp
> 1864: Stopping a compile will not kill the compiler

- common/src/IO/Path.cpp
- test/src/IO/PathTest.cpp
> 1921: Path::extension crash when typing a path in the game engine profile dialog

- Build.md
- common/src/Algorithms.h
- common/src/View/VertexHandleManager.cpp
> 1940: Slanted faces don't show the split handle

- common/src/View/MapFrame.cpp
- common/src/View/MapViewBase.h
> 1957: Can't duplicate selection while rotate tool is active in RC5

- common/src/View/GameDialog.cpp
- common/src/View/MapFrame.cpp
- common/src/View/ToolController.cpp
- common/src/View/ToolController.h
- common/src/View/VertexTool.cpp
- common/src/View/VertexToolController.cpp
- common/src/View/VertexToolController.h
- common/src/View/VertexToolControllerBase.h
- common/src/View/WelcomeFrame.cpp
Closes #1938. Investigated with @ericwa and determined it was some leftover code: https://github.com/kduske/TrenchBroom/pull/1892#issuecomment-349758685
> 1938: Crash when creating new vertices

- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MoveBrushEdgesCommand.cpp
- common/src/View/MoveBrushFacesCommand.cpp
- common/src/View/MoveBrushVerticesCommand.cpp
- common/src/View/VertexCommand.cpp
- common/src/View/VertexCommand.h
> 1961: Restore undo collation for vertex operations

- common/src/View/DirectoryTextureCollectionEditor.cpp
- common/src/View/MapFrame.cpp
> 1974: Crashing on Linux when pressing [Ctrl]+[Z] with an empty command stack

- common/src/Polygon.h
- common/src/View/FaceToolController.cpp
- common/src/View/VertexHandleManager.h
- test/src/PolygonTest.cpp
> 1982: Can't move shared faces together

- common/src/Model/Hit.cpp
- common/src/Model/HitQuery.cpp
- common/src/Model/HitQuery.h
- common/src/Renderer/RenderService.cpp
- common/src/View/EdgeTool.cpp
- common/src/View/EdgeToolController.cpp
- common/src/View/FaceToolController.cpp
- common/src/View/VertexHandleManager.cpp
- common/src/View/VertexHandleManager.h
- common/src/View/VertexTool.cpp
- common/src/View/VertexToolControllerBase.h
Closes #1980. This PR removes the ability to drag edges anywhere. Now edges and faces must be dragged by their handles.
> 1980: Add selection handles for edge tool

- common/src/View/EntityAttributeGrid.cpp
- common/src/View/VertexTool.cpp
> 1981: Moving shared edges in a 2D view leads to a crash

- common/src/View/ActionManager.cpp
- common/src/View/KeyboardShortcut.cpp
- test/src/View/KeyboardShortcutTest.cpp
> 1973: KB shortcut issues across Windows 7 / 10 / Linux

- common/src/Model/ParallelTexCoordSystem.cpp
- test/src/Model/BrushFaceTest.cpp
> 1995: rewrite ParallelTexCoordSystem::doUpdateNormalWithProjection

- .travis.yml
- appveyor.yml
Docs show something similar here: https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
> 2017: try fixing deployment condition

- .gitignore
- app/resources/documentation/manual/default.css
- app/resources/documentation/manual/index.md
- app/resources/documentation/manual/manual.sublime-project
> 2022: Manual requires a very wide browser window to avoid horizontal scrolling

- app/resources/documentation/manual/index.md
> 2024: replace IRC link in manual with discord

- common/src/View/CreateComplexBrushTool.cpp
- common/src/View/CreateComplexBrushTool.h
> 2026: Closing the Brush tool with the hotkey retains old information

- common/src/Allocator.h
- common/src/IO/DefParser.cpp
- common/src/IO/StandardMapParser.cpp
- common/src/Macros.h
- common/src/Model/ChangeBrushFaceAttributesRequest.cpp
- common/src/Polyhedron_ConvexHull.h
- common/src/Renderer/IndexRangeMap.cpp
- common/src/View/CellLayout.h
- test/src/Model/BrushTest.cpp
Fixes #2035
I'm assuming all of the switch fallthroughs I annotated are intentional.
> 2035: fix gcc 7.2 warnings

- common/src/IO/DiskIO.cpp
> 1979: Adding a WAD "relative to game directory"

- common/src/Model/EditorContext.cpp
- common/src/View/MapDocumentCommandFacade.cpp
> 1787: "Select All" behaves awkwardly when a group is open

- common/src/View/ActionManager.cpp
> 2049: Rotate Tool: Missing Functionality Described in Manual

- common/src/View/VertexToolController.cpp
- common/src/View/VertexToolControllerBase.h
> 2037: Vertex tool: Ctrl/Cmd modifier doesn't work while adding a vertex with Shift+drag

- common/src/View/ClipTool.cpp
- common/src/View/ClipTool.h
> 2032: Disallow performing a clip while dragging a clip point.

- common/src/View/DirectoryTextureCollectionEditor.cpp
- common/src/View/DirectoryTextureCollectionEditor.h
> 2039: Crash when loading texture groups

- common/src/View/TextureCollectionEditor.cpp
> 2064: Texture collections panel layout wrong after reloading map

- common/src/View/ClipTool.cpp
- common/src/View/ClipTool.h
- common/src/View/ClipToolController.cpp
> 1967: Selecting faces with the Clip tool active hides them

- common/src/View/IssueBrowser.cpp
- common/src/View/IssueBrowser.h
- common/src/View/IssueBrowserView.cpp
- common/src/View/IssueBrowserView.h
- common/src/View/wxUtils.cpp
- common/src/View/wxUtils.h
> 2065: Issues panel shows invalid issues after map reload

- common/src/View/LaunchGameEngineDialog.cpp
> 2080: Game Launch doesn't work on MacOS

- common/src/Polyhedron_Matcher.h
- common/src/Relation.h
- test/src/Model/BrushTest.cpp
> 2082: Deleting a vertex or an edge from a complex brush will sometimes change the textures on unrelated faces

- common/src/View/DirectoryTextureCollectionEditor.cpp
- common/src/View/DirectoryTextureCollectionEditor.h
- common/src/View/FileTextureCollectionEditor.cpp
- common/src/View/FileTextureCollectionEditor.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
> 885: Add buttons to reload texture collections to the UI.

- common/src/View/FaceAttribsEditor.cpp
- common/src/View/FaceAttribsEditor.h
- common/src/View/FaceInspector.cpp
- common/src/View/FaceInspector.h
- common/src/View/Inspector.cpp
- common/src/View/Inspector.h
- common/src/View/MapFrame.cpp
- common/src/View/UVEditor.cpp
- common/src/View/UVEditor.h
> 2096: Cancel mouse drags in UV editor when undoing.

- common/src/View/MoveObjectsToolPage.cpp
> 2114: "Move objects by" text field does not respond to Enter key

- common/src/View/CommandIds.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapViewBase.cpp
- common/src/View/MapViewBase.h
- test/src/View/MapDocumentTest.cpp
Fixes #2051 
Adds a "Merge Groups into XX" menu item:
> 2051: Merge groups command

- common/src/IO/DefParser.cpp
- common/src/IO/DefParser.h
- common/src/IO/Tokenizer.h
- test/data/IO/Def/RTCW.def
- test/data/IO/Def/SOF.def
- test/src/IO/DefParserTest.cpp
> 2161: Improved .DEF format support

- common/src/Preference.h
- common/src/PreferenceManager.cpp
- common/src/PreferenceManager.h
- common/src/View/KeyboardShortcutEditor.cpp
- common/src/View/MousePreferencePane.cpp
- common/src/View/PreferenceDialog.cpp
> 2163: Fix binding of fly mode keys

- common/src/View/GamesPreferencePane.cpp
- common/src/View/GamesPreferencePane.h
> 2159: Use text ctrl intead of label for displaying game path to avoid pushing out the choose button

- app/resources/documentation/manual/index.md
> 2177: Add links to J. Skelton's Quake Tools.

- common/src/Model/Entity.cpp
> 2168: Rotating entities + brushes sometimes has a weird behaviour.

- common/src/Model/Brush.cpp
- common/src/Model/EditorContext.cpp
- common/src/Model/EditorContext.h
- common/src/Model/Entity.cpp
- common/src/Model/FindGroupVisitor.cpp
- common/src/Model/FindGroupVisitor.h
- common/src/Model/Group.cpp
- common/src/Model/ModelUtils.cpp
- common/src/Model/ModelUtils.h
- common/src/Model/Node.cpp
- common/src/Model/Node.h
- common/src/Model/Object.cpp
- common/src/Model/Object.h
- common/src/View/LayerEditor.cpp
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapViewBase.cpp
- common/src/View/SelectionTool.cpp
- test/src/Model/EditorContextTest.cpp
> 2150: Can select brushes within a closed group with mousewheel "selection drilling"

- common/src/Renderer/Camera.cpp
- common/src/Renderer/Camera.h
- common/src/View/RenderView.cpp
- common/src/View/RenderView.h
- common/src/View/UVView.cpp
> 2187: Catch ERASE_BACKGROUND event to avoid flickering (possibly).

- app/resources/games/Quake/Quoth2.fgd
from http://www.quaketastic.com/files/misc/quoth2.fgd
(this is linked on Preach's blog: https://tomeofpreach.wordpress.com/quoth/ )
Fixes #2147
> 2147: sync Quoth2.fgd with upstream

- appveyor.bat
- benchmark/src/Renderer/BrushRendererBenchmark.cpp
- cmake/TrenchBroomTest.cmake
- travis-linux.sh
- travis-macos.sh
> 2190: add TrenchBroom-Benchmark target and move BrushRendererTest to it

- common/src/TrenchBroom.h
- common/src/View/UVScaleTool.cpp
> 2148: Scaling texture doesn't always snap to defined grid lines in view

- .gitignore
- Build.md
- CMakeLists.txt
- common/src/DoublyLinkedList.h
- common/src/ProjectingSequence.h
- common/src/Relation.h
- test/src/View/GridTest.cpp
> 2204: Improve VS 2017 support

- common/src/Model/Brush.cpp
> 2212: Edge dragging not working

- common/src/Quat.h
- test/src/QuatTest.cpp
>  2215: fix Quat(from, to) constructor to handle 180 degree case

- common/src/Model/MapFacade.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/ScaleObjectsToolPage.cpp
- common/src/View/ScaleObjectsToolPage.h
- common/src/View/TransformObjectsCommand.cpp
- common/src/View/TransformObjectsCommand.h
- test/src/View/MapDocumentTest.cpp
> 2221: allow negative scale factors in the Scale tool text box to flip the selection

- common/src/Model/Brush.cpp
- common/src/Model/Brush.h
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapDocumentCommandFacade.h
- common/src/View/TransformObjectsCommand.cpp
- test/src/View/MapDocumentTest.cpp
> 2219: check whether transform can be applied to brushes

- common/src/Edge.h
- common/src/Model/Brush.cpp
- common/src/Model/Brush.h
- common/src/Model/BrushFace.cpp
- common/src/Model/BrushFace.h
- common/src/Polygon.h
- common/src/Polyhedron.h
- common/src/Polyhedron_Edge.h
- common/src/Polyhedron_Face.h
- common/src/Polyhedron_Misc.h
- common/src/Vec.h
- common/src/View/EdgeTool.cpp
- common/src/View/FaceTool.cpp
- common/src/View/MapDocument.cpp
- common/src/View/PreferenceDialog.cpp
- common/src/View/RecentDocuments.h
- common/src/View/VertexHandleManager.h
- common/src/View/VertexTool.cpp
- common/src/View/VertexToolBase.h
- test/src/Model/BrushTest.cpp
- test/src/PolyhedronTest.cpp
- test/src/VecTest.cpp
Closes #2195. This PR changes the vertex tool and brush vertex related functions to use absolute float precision (no epsilons).
> 2195: Vertices becoming unstuck when dragging

- Build.md
List formatting is weird, but this should be a numbered list in md? Not sure what github does with it.
> add: Better build instructions for system-wide installed wxWidgets

- app/resources/games/Quake2.cfg
> 2276: add hint/skip Quake 2 surface flags

- common/src/View/GamesPreferencePane.cpp
> 2272: Game path box in game preferences is always blank

- common/src/IO/DefParser.cpp
- common/src/IO/FgdParser.cpp
- common/src/IO/FgdParser.h
- common/src/IO/FileSystemHierarchy.cpp
- common/src/IO/FileSystemHierarchy.h
- common/src/IO/Parser.h
- common/src/IO/Path.cpp
- common/src/IO/Path.h
- common/src/IO/Tokenizer.cpp
- common/src/IO/Tokenizer.h
- common/src/Model/GameFactory.cpp
- common/src/Model/GameImpl.cpp
- test/data/IO/Fgd/parseInclude/host.fgd
- test/data/IO/Fgd/parseInclude/include.fgd
- test/data/IO/Fgd/parseNestedInclude/host.fgd
- test/data/IO/Fgd/parseNestedInclude/nested/include.fgd
- test/data/IO/Fgd/parseNestedInclude/nested/nested.fgd
- test/data/IO/Fgd/parseRecursiveInclude/host.fgd
- test/src/IO/FgdParserTest.cpp
> 2202: Add support for FGD includes

- common/src/View/ScaleObjectsToolController.cpp
- common/src/View/ShearObjectsToolController.cpp
> 2295: use std::make_tuple instead of return {...};

- common/src/View/Autosaver.cpp
- common/src/View/MapFrame.cpp
> 2305: fix gcc8 build

- common/src/View/UVCameraTool.cpp
> 2297: Texture face pane can be zoomed out until corruption occurs

- common/src/Model/ParaxialTexCoordSystem.cpp
- common/src/View/UVOriginTool.cpp
- common/src/View/UVOriginTool.h
- common/src/View/UVRotateTool.cpp
- vecmath/include/vecmath/intersection.h
- vecmath/include/vecmath/vec.h
> 2298: Texture rotation tool disappears from texture alignment pane

- common/src/Model/ParallelTexCoordSystem.cpp
- common/src/Model/ParallelTexCoordSystem.h
- test/src/Model/BrushFaceTest.cpp
> 2315: replace broken ParallelTexCoordSystem::computeNonTextureRotation

- app/resources/games/Quake/GameConfig.cfg
- common/src/Model/BrushFace.cpp
- common/src/Renderer/AllocationTracker.cpp
- common/src/Renderer/AllocationTracker.h
- common/src/Renderer/BrushRenderer.cpp
- common/src/Renderer/BrushRenderer.h
- common/src/Renderer/BrushRendererArrays.cpp
- common/src/Renderer/BrushRendererArrays.h
- common/src/Renderer/EdgeRenderer.cpp
- common/src/Renderer/FaceRenderer.cpp
- common/src/Renderer/MapRenderer.cpp
- common/src/Renderer/MapRenderer.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapDocumentCommandFacade.cpp
- test/src/Renderer/AllocationTrackerTest.cpp
Adding, removing, and reloading texture collections are working now.
Fixes #2324
> 2324: fix reloading texture collections

- common/src/IO/FgdParser.cpp
- common/src/IO/FgdParser.h
- test/src/IO/FgdParserTest.cpp
> 2329: FGD Parsing Fails to Concatenate Strings Using +

- common/src/Model/Entity.cpp
- test/src/Model/EntityTest.cpp
> 2331: fix rotation caching bug

- common/src/View/ActionManager.cpp
> 2335: Add windows shortcut to open manual.

- app/resources/games/Daikatana/Episode 1.fgd
- app/resources/games/Daikatana/Episode 2.fgd
- app/resources/games/Daikatana/Episode 3.fgd
- app/resources/games/Daikatana/Episode 4.fgd
- common/src/IO/ParserStatus.cpp
- test/src/IO/DefParserTest.cpp
- test/src/IO/FgdParserTest.cpp
> 2340: fix daikatana common include name

- travis-linux.sh
>  2352: avoid xvfb race condition

- app/resources/games/Daikatana/GameConfig.cfg
mostly thanks to @Sinihopea - Re-order the flags, fix a typo with monsterclip, add NPC clip to the list of clip types.
Fixes #2345
> 2345: Daikatana config fixes

- common/src/View/RotateObjectsToolPage.cpp
> 2349: Rotation angle is automatically rounded

- common/src/IO/DefParser.cpp
- common/src/IO/FgdParser.cpp
- test/src/IO/DefParserTest.cpp
- test/src/IO/FgdParserTest.cpp
- test/src/bbox_test.cpp
- vecmath/include/vecmath/bbox.h
> 2371: Repair invalid entity definition bounds.

- common/src/Assets/Texture.cpp
- common/src/IO/MipTextureReader.cpp
- common/src/IO/SkinLoader.cpp
- common/src/IO/TextureCollectionLoader.cpp
- common/src/IO/TextureLoader.cpp
- common/src/IO/TextureLoader.h
- common/src/IO/WalTextureReader.cpp
- common/src/Model/GameFactory.cpp
- common/src/Model/GameImpl.cpp
- common/src/Renderer/Shader.cpp
- common/src/Renderer/ShaderProgram.cpp
> 2381: Don't crash when palette cannot be found.

- common/src/View/ClipTool.cpp
- common/src/View/ClipTool.h
> 2385: With clip tool active, texture changes dont occur until you exit the tool or place a clip point

- common/src/View/RenderView.cpp
- common/src/View/RenderView.h
I confirmed that this works (enables vsync) on my Win10/Intel 4400 system, and it also worked for @jonathanlinat here: https://github.com/kduske/TrenchBroom/issues/2369#issuecomment-433765176 
Fixes #2369
> 2369: request vsync on Windows

- common/src/View/IssueBrowserView.cpp
> 2391: Quick fix menu broken on windows.

- common/src/Model/BrushFace.cpp
> 2394: fix alt-click requires 2 clicks in some circumstances 

- common/src/Model/EntityAttributes.cpp
- common/src/Model/EntityAttributes.h
- common/src/Model/GameImpl.cpp
> 2402: Add mapversion and MaxRange properties when creating a new Valve map.

- common/src/Model/PointFile.cpp
- common/src/Model/PointFile.h
- common/src/Model/PortalFile.cpp
- common/src/Model/PortalFile.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
> 2401: Disable reload point / portal file menu items if the files are deleted

- common/src/IO/MapFileSerializer.cpp
> 2407: fix space in Hexen2FileSerializer

- app/resources/documentation/manual/index.md
- common/src/Preferences.cpp
- common/src/Preferences.h
- common/src/View/ActionContext.cpp
- common/src/View/ActionContext.h
- common/src/View/ActionManager.cpp
- common/src/View/CommandIds.h
- common/src/View/FlyModeHelper.cpp
- common/src/View/FlyModeHelper.h
- common/src/View/MapFrame.cpp
- common/src/View/MapView3D.cpp
- common/src/View/MapView3D.h
- common/src/View/MapViewBase.cpp
- common/src/View/MapViewBase.h
- common/src/View/MousePreferencePane.cpp
- common/src/View/MousePreferencePane.h
> 2434: Fly mode is choppy on macOS (and possibly Windows)

- common/src/View/MapView3D.cpp
- common/src/View/MapView3D.h
> 2434: Increase WASD framerate.

- Build.md
- travis-linux.sh
(when applying wxWidgets patches.)
Fixes #2470
> 2470: avoid ambiguous redirect error with patch

- app/resources/games/Quake/GameConfig.cfg
- app/resources/games/Quake/Teamfortress.fgd
> 2489: Add support for Teamfortress.

- common/src/View/MapFrame.cpp
> 2409: Show number of selected faces in status bar

- common/src/IO/DiskFileSystem.cpp
- common/src/IO/DiskFileSystem.h
- common/src/Model/GameFactory.cpp
Reverts kduske/TrenchBroom#2506
> Revert "Use temporaries when writing game config files."

- common/src/Renderer/SelectionBoundsRenderer.cpp
> 2487: Fix size hints positioning when camera is within the selection bounds.

- common/src/View/CellLayout.h
- common/src/View/CellView.h
> 2495: Allow dragging when clicking anywhere in cell view.

- common/src/AABBTree.h
- common/src/IO/TextureCollectionLoader.cpp
- common/src/Model/Brush.cpp
- common/src/Model/Brush.h
- common/src/Model/Entity.cpp
- common/src/Model/Entity.h
- common/src/Model/GameImpl.cpp
- common/src/Model/Group.cpp
- common/src/Model/Group.h
- common/src/Model/Layer.cpp
- common/src/Model/Layer.h
- common/src/Model/Node.cpp
- common/src/Model/Node.h
- common/src/Model/World.cpp
- common/src/Model/World.h
- test/src/Model/NodeTest.cpp
- test/src/vec_test.cpp
- vecmath/include/vecmath/vec.h
> 2525: Handle nan in entity origin.

- common/src/Renderer/EntityRenderer.cpp
> 2528: fix 2D entity angle arrows always being culled

- common/src/View/Autosaver.cpp
- common/src/View/Autosaver.h
- test/src/IO/DiskFileSystemTest.cpp
- test/src/IO/TestEnvironment.cpp
- test/src/IO/TestEnvironment.h
- test/src/Model/TestGame.cpp
- test/src/View/AutosaverTest.cpp
> 2544: Disregard autosave backups with invalid file name pattern

- common/src/Assets/Quake3Shader.cpp
- common/src/Assets/Quake3Shader.h
- common/src/Assets/Texture.cpp
- common/src/IO/ParserStatus.cpp
- common/src/IO/ParserStatus.h
- common/src/IO/Quake3ShaderFileSystem.cpp
- common/src/IO/Quake3ShaderParser.cpp
- common/src/IO/Quake3ShaderParser.h
- common/src/IO/SimpleParserStatus.cpp
- common/src/IO/SimpleParserStatus.h
- common/src/Renderer/FaceRenderer.cpp
- common/src/Renderer/GL.cpp
- common/src/Renderer/GL.h
- common/src/StringUtils.cpp
- common/src/StringUtils.h
- common/src/View/CellView.h
- common/src/View/TextureBrowserView.cpp
- test/src/IO/Quake3ShaderParserTest.cpp
- test/src/IO/TestParserStatus.cpp
Closes #2568.
Also adds a test for all the blend factors and function names.
> 2568: Add missing blend factors, validate them and warn about unknown ones. Also blend factors are no longer case sensitive.

- common/src/View/ClipTool.cpp
- common/src/View/ClipToolController.cpp
Closes #2602. Might also fix #2593.
> 2602: Make clip tool more reliable with two clip points.

- common/src/IO/FgdParser.cpp
- common/src/IO/FgdParser.h
- test/src/IO/FgdParserTest.cpp
> 2601: Fix FGD parser for float and string option values with defaults.

- common/src/IO/FreeImageTextureReader.cpp
- common/src/IO/MipTextureReader.cpp
- common/src/IO/TextureReader.cpp
- common/src/IO/TextureReader.h
- common/src/IO/WalTextureReader.cpp
> 2599: Check texture dimensions on load.

- common/src/Model/GameFactory.cpp
- common/src/Model/GameFactory.h
- common/src/TrenchBroomApp.cpp
> 2623: Don’t crash when loading game configs fails.

- common/src/View/ActionManager.cpp
> 2636: Don't send wxAcceleratorEntry with keycode 0 to wxWidgets

- common/src/Model/Brush.cpp
- common/src/Model/Brush.h
- common/src/View/MapDocumentCommandFacade.cpp
> 2644: respect UV lock preference when snapping verts.

- common/src/TrenchBroomApp.cpp
> 2642: Ensure game factory is initialized before attempting to open a file from cmd line.

- common/src/Assets/EntityDefinition.h
- common/src/Assets/EntityDefinitionManager.h
- common/src/Assets/TextureCollection.h
- common/src/Assets/TextureManager.h
- common/src/Model/AttributableNode.h
- common/src/Model/CompilationConfig.h
- common/src/Model/CompilationProfile.h
- common/src/Model/CompilationTask.h
- common/src/Model/EditorContext.h
- common/src/Model/GameEngineConfig.h
- common/src/Model/GameEngineProfile.h
- common/src/Notifier.h
- common/src/PreferenceManager.h
- common/src/Renderer/Camera.h
- common/src/TrenchBroomApp.h
- common/src/View/CommandProcessor.cpp
- common/src/View/CommandProcessor.h
- common/src/View/Grid.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapViewConfig.h
- common/src/View/RecentDocuments.h
- common/src/View/Tool.h
- common/src/View/ToolBox.h
- test/src/MockObserver.h
- test/src/NotifierTest.cpp
> 2629: Replace NotifierN classes with a single vararg template

- .gitignore
- common/src/IO/Quake3ShaderParser.cpp
- test/src/IO/Quake3ShaderParserTest.cpp
> 2633: Support shaders with an absolute path

- common/src/StepIterator.h
- common/src/View/EntityBrowserView.cpp
- common/src/View/TextureBrowserView.cpp
- test/src/StepIteratorTest.cpp
> 2665: Ensure that StepIterator does not advance past end of sequence.

- common/src/View/SelectionTool.cpp
> 2677: Always close current group on double click unless double clicking on a nested group.

- common/src/View/KeyboardShortcutGridTable.cpp
> 2694: Show all shortcut entries in shortcut editor

- app/resources/games/Quake2/GameConfig.cfg
- app/resources/games/Quake3/GameConfig.cfg
- common/src/IO/GameConfigParser.cpp
- common/src/IO/GameConfigParser.h
- test/src/IO/GameConfigParserTest.cpp
> 2700: Correctly parse surface flag dependent tag matcher.

- common/src/IO/Reader.cpp
- test/fixture/IO/Reader/10byte
- test/src/IO/ReaderTest.cpp
> 2703: Properly initialize reader initial position to 0

- common/src/TrenchBroomApp.cpp
> 2712: Set app name and related properties in OnInit.

- common/src/Model/EntityRotationPolicy.cpp
- common/src/Model/EntityRotationPolicy.h
- test/src/Model/EntityTest.cpp
- test/src/mat_ext_test.cpp
- vecmath/include/vecmath/mat_ext.h
> 2727: Fix EntityRotationPolicy::getYawPitchRoll

- common/src/View/UVViewHelper.cpp
> 2728: Alternate method of computing UV origin.

- common/src/View/MapView3D.cpp
> 2765: fix positioning pastes when the mouse is over an Entity

- common/src/View/EntityAttributeGridTable.cpp
- common/src/View/EntityAttributeGridTable.h
A quick feature addition:
Fixes #2259
> 2259: autocomplete classnames

- app/resources/documentation/manual/default-sass/modules/sass/layout.sass
- app/resources/documentation/manual/default-sass/modules/sass/responsive/layout.sass
- app/resources/documentation/manual/default-sass/modules/sass/utils/variables.sass
- app/resources/documentation/manual/default.css
- app/resources/documentation/manual/template.html
> 2454: Moved version / build block to main content and applied CSS properties.

- app/resources/games/Hexen2/GameConfig.cfg
> 2772: Enable Valve format for Hexen 2 game config.

- common/src/Model/AttributeValueWithDoubleQuotationMarksIssueGenerator.cpp
- common/src/Model/InvalidTextureScaleIssueGenerator.cpp
> 2781: fix copy/paste errors in issue names

- app/resources/documentation/manual/index.md
> 2796: fix Linux user data path in the manual

- CMakeLists.txt
> 2803: raise stack size from 1MB->8MB on win32

- CMakeLists.txt
- appveyor.bat
- common/src/Assets/Palette.h
- common/src/Model/Node.cpp
- common/src/PreferenceManager.cpp
- common/src/Renderer/Circle.cpp
- common/src/Renderer/FontDescriptor.cpp
- common/src/Renderer/RenderService.cpp
- common/src/View/AppInfoPanel.cpp
- common/src/View/EntityAttributeEditor.cpp
- common/src/View/InputEvent.cpp
- common/src/View/TextureBrowserView.cpp
Fixes #2828.
This is not yet ready, I'm just creating a PR to easily keep track of the build status.
> 2828: Fix remaining warnings and issues after 2826

- common/src/Renderer/BrushRenderer.cpp
- common/src/Renderer/BrushRenderer.h
> 2848: fix rendering of selected transparent brushes

- common/src/IO/FgdParser.cpp
- common/test/src/IO/FgdParserTest.cpp
Fixes #2833
I just applied @LogicAndTrick 's patch and tested it!
> 2833: FGD: allow integer or decimal defaults for string values

- common/src/IO/ObjSerializer.cpp
> 2851: ObjFileSerializer: flip V coordinate

- common/src/IO/DkPakFileSystem.cpp
- common/src/View/CommandProcessor.h
- common/src/View/QtUtils.h
> 2880: fix unity build issues (+ unrelated docs fix)

- app/resources/shader/Face.fragsh
- common/src/IO/FreeImageTextureReader.cpp
- common/src/Renderer/FaceRenderer.cpp
- common/src/Renderer/FaceRenderer.h
- common/src/View/UVView.cpp
> 2846: invert grid color on bright textures

- common/src/IO/TextureCollectionLoader.h
> 2899: Fix non-unity build issues

- common/src/Model/HitAdapter.cpp
> 2841: fix bad_any_cast

- common/src/View/FaceAttribsEditor.cpp
- common/src/View/FlagsPopupEditor.cpp
Closes #2946
In addition to fixing the bug itself, this PR improves the visual styling for flag editors
> 2946: fix flag updates, fix flag editor styling issues

- app/CMakeLists.txt
- app/cmake/TrenchBroom.rc.in
- common/src/TrenchBroomApp.cpp
Closes #2953.
This cannot be merged, @ericwa please check out the two FIXMEs in `TrenchBroomApp.cpp`, then let's discuss how to solve them.
> 2953: set manufacturer / vendor name to 'TrenchBroom'

- CMakeLists.txt
- app/CMakeLists.txt
- common/src/Model/EntityAttributes.cpp
- common/src/Model/EntityAttributes.h
> 3016: restore ASan checks on CI, fix use-after-free in findAttribute

- app/CMakeLists.txt
- common/cmake/GenerateVersion.cmake.in
> 3019: fix building TB if the path contains spaces. Fix nomanual target failing to build on VS2017

- Build.md
- CMakeLists.txt
> 3014: Updated 'Build.md' file.

- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/src/View/Tool.cpp
- common/src/View/Tool.h
- common/src/View/ToolBox.cpp
- common/src/View/ToolBox.h
- common/src/View/VertexToolBase.h
> 3007: update action state when handle selection changes

- common/src/Model/CollectTouchingNodesVisitor.h
- common/test/src/Model/NodeTest.cpp
> 3049: fix CollectTouchingNodesVisitor

- common/src/View/CellView.cpp
- common/src/View/CellView.h
- common/src/View/InputEvent.cpp
- common/src/View/InputEvent.h
- common/src/View/InputState.h
- common/test/src/View/InputEventTest.cpp
Fixes #3008 
I've tested on macOS, Linux, Windows and this seems reasonable on all 3. On Windows it should be an exact match for 2019.6.
> 3008: fix scroll speed

- common/src/Preferences.cpp
- common/src/Preferences.h
- common/src/View/MapViewBase.cpp
Added a preference "Renderer/Show FPS"
FIxes #3046
> 3046: hide render stats by default

- Build.md
> 3040: update Build.md now that VS2019 is required

- common/src/View/GamesPreferencePane.cpp
> 3044: Preferences -> Game Path should be an editable text box

- common/src/View/TabBar.cpp
> Increase clickable area for tab bar buttons

- app/resources/games/DigitalPaintball2/GameConfig.cfg
- app/resources/games/Heretic2/GameConfig.cfg
- app/resources/games/Kingpin/GameConfig.cfg
- app/resources/games/Quake2/GameConfig.cfg
- app/resources/games/Quake3/GameConfig.cfg
- common/test/src/IO/GameConfigParserTest.cpp
> Fix typo: mosterclip

- common/src/View/Actions.cpp
> 3076: allow "Turn Selection into" on face selections

- common/src/View/TwoPaneMapView.cpp
> 3094: TwoPaneMapView: fix doMaximizeView maximizing wrong view

- app/resources/documentation/manual/index.md
- common/src/View/MoveObjectsTool.cpp
- common/src/View/SetBrushFaceAttributesTool.cpp
- common/src/View/SetBrushFaceAttributesTool.h
Fixes #2981
This is handy enough and a small enough change that it'd be nice to get into the RC
> 2981: drag apply face attributes

- common/src/View/EntityAttributeItemDelegate.cpp
when typing a letter to open the cell editor
Briefly, when typing the first letter of the text you want to enter to open the cell editor,
when setEditorData() runs, the letter has not been inserted into the QLineEdit yet.
Opening the completion popup and then typing the letter causes the editor to close, which is
issue #3082 and quite annoying. Only happens on Linux.
Fixes #3082
> 3082: fix target/targetname editor immediately closing in some cases on Linux

- common/src/Model/Entity.cpp
- common/src/Model/EntitySnapshot.cpp
- common/src/Model/EntitySnapshot.h
- common/test/src/View/SnapshotTest.cpp
> 3103: fix empty "angle" property created after undoing a rotation

- common/src/View/ControlListBox.cpp
- common/src/View/LaunchGameEngineDialog.cpp
> 3099: fix crash when adding an engine + pressing launch button, fix working dir

- app/resources/games/Quake/Quoth2.fgd
> 3086: model configuration for mapobject_custom in Quoth2.fgd

- common/src/View/FlagsEditor.cpp
- common/src/View/QtUtils.cpp
- common/src/View/QtUtils.h
- common/src/View/TextureCollectionEditor.cpp
- common/src/View/ViewEditor.cpp
> 3100: use deferred deletion for flags editor checkboxes

- app/resources/games/Quake2/Quake2.fgd
> 3091: Quake2.fgd updates

- common/src/View/EntityAttributeModel.cpp
> 3122: use QString::fromLocal8Bit for editing entity properties

- common/src/View/FileTextureCollectionEditor.cpp
- common/src/View/FileTextureCollectionEditor.h
(lost since 2019.6)
Fixes #3124
> 3124: re-implement drag and drop into file texture collection editor

- app/resources/documentation/manual/index.md
- common/src/Model/MapFacade.h
- common/src/View/Actions.cpp
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/test/src/View/MapDocumentTest.cpp
> 3137: Add "Select Inverse" command

- common/src/View/MapViewActivationTracker.cpp
- common/src/View/MapViewActivationTracker.h
> 3152: Focus map view when a drag enters

- common/src/Model/GameFileSystem.cpp
- common/test/src/IO/DiskFileSystemTest.cpp
> 3132: handle directoryExists() exception

- common/src/Model/NonIntegerPlanePointsIssueGenerator.cpp
> 2780: remove"convert plane points to integer" menu item

- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/src/View/QtUtils.cpp
- common/src/View/QtUtils.h
> 3160: Disable cut, copy, paste actions unless map view has focus

- common/src/View/Inspector.cpp
- common/src/View/Inspector.h
- common/src/View/MoveObjectsToolPage.cpp
- common/src/View/QtUtils.cpp
- common/src/View/QtUtils.h
- common/src/View/RotateObjectsToolPage.cpp
- common/src/View/ScaleObjectsToolPage.cpp
- common/src/View/TabBook.cpp
- common/src/View/TabBook.h
> Sync the min. height of map view bar and inspector tab bar both ways

- common/src/View/ToolBox.cpp
> 3176: fix Toobox ordering issue with clearing m_modalTool

- common/src/View/LayerListBox.cpp
> 3184: fix layer list box icons

- common/src/View/EntityAttributeModel.cpp
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapFrame.cpp
- common/src/View/MapTextEncoding.h
- common/src/View/QtUtils.cpp
- common/src/View/QtUtils.h
- common/src/View/SmartChoiceEditor.cpp
> 3179: fix copy/paste of entities with special Quake characters

- .gitignore
- common/src/View/BorderLine.cpp
- common/src/View/BorderPanel.cpp
- common/src/View/ChoosePathTypeDialog.cpp
- common/src/View/ColorButton.cpp
- common/src/View/CompilationDialog.cpp
- common/src/View/DirectoryTextureCollectionEditor.cpp
- common/src/View/EntityDefinitionFileChooser.cpp
- common/src/View/GameDialog.cpp
- common/src/View/LaunchGameEngineDialog.cpp
- common/src/View/MapFrame.cpp
- common/src/View/MapViewBar.cpp
- common/src/View/ModEditor.cpp
- common/src/View/QtUtils.cpp
- common/src/View/QtUtils.h
- common/src/View/ReplaceTextureDialog.cpp
- common/src/View/Splitter.cpp
- common/src/View/Splitter.h
- common/src/View/TabBar.cpp
- common/src/View/TabBar.h
- common/src/View/TitleBar.cpp
- common/src/View/TitledPanel.cpp
- common/src/View/ViewConstants.cpp
- common/src/View/ViewConstants.h
- common/src/View/ViewEditor.cpp
- common/src/View/WelcomeWindow.cpp
> 3198: Visual touchups

- app/resources/documentation/manual/index.md
> Extend list of supported package formats in manual

- common/src/View/EntityAttributeGrid.cpp
> 3195: update smart editors on more types of table changes

- common/src/Model/BrushNode.cpp
- common/src/Model/BrushNode.h
- common/src/Renderer/MapRenderer.cpp
- common/test/src/Model/BrushNodeTest.cpp
> 3238: Fix rendering selected brush faces

- common/src/View/FaceInspector.cpp
> 3244: Don't attempt to change texture if no faces are selected

- common/src/View/MapViewActivationTracker.cpp
> 3045: Make activation tracker more resilient

- common/src/Model/ChangeBrushFaceAttributesRequest.cpp
- common/test/src/View/ChangeBrushFaceAttributesTest.cpp
> 3250: Collate texture name when texture operation is collated 

- common/src/View/MapDocumentCommandFacade.cpp
- common/test/CMakeLists.txt
- common/test/src/View/ChangeEntityAttributesCommandTest.cpp
> 2777: Invalidate selection bounds after changing entity attributes

- common/src/View/MapDocument.cpp
- common/test/src/View/SelectionTest.cpp
> 3227: Ensure that lastSelectionBounds remain valid and nonempty

- common/CMakeLists.txt
- common/src/Assets/AttributeDefinition.cpp
- common/src/Assets/AttributeDefinition.h
- common/src/Assets/EntityDefinition.cpp
- common/src/Assets/EntityDefinition.h
- common/src/IO/EntParser.cpp
- common/src/IO/EntityDefinitionClassInfo.cpp
- common/src/IO/FgdParser.cpp
- common/src/View/EntityAttributeEditor.cpp
- common/src/View/SmartAttributeEditorManager.cpp
- common/src/View/SmartChoiceEditor.cpp
- common/src/View/SmartFlagsEditor.cpp
- common/src/View/SmartFlagsEditor.h
- common/src/View/SmartTypeEditorMatcher.cpp
- common/src/View/SmartTypeEditorMatcher.h
- common/test/src/IO/DefParserTest.cpp
- common/test/src/IO/EntParserTest.cpp
- common/test/src/IO/FgdParserTest.cpp
> 3024: Generalize smart spawnflags editor to any kind of flag attribute

- common/src/View/MapFrame.cpp
> 3224: Check that there is a current map view for pasting

- common/src/Model/EntityNode.cpp
> 2785: Don't round entity origin

- common/src/Renderer/Circle.cpp
> 3111: fix bogus PrimType static_cast

- common/src/Model/ChangeBrushFaceAttributesRequest.cpp
- common/src/Model/ChangeBrushFaceAttributesRequest.h
- common/src/View/UVEditor.cpp
- common/test/src/Model/TestGame.cpp
- common/test/src/Model/TestGame.h
- common/test/src/View/ChangeBrushFaceAttributesTest.cpp
> 3226: honor default texture scale on reset

- common/src/View/FaceAttribsEditor.cpp
- common/src/View/FaceAttribsEditor.h
> 3290: FaceAttribsEditor: initialize the step size by calling gridDidChange in the constructor

- Build.md
> 3321: Add Fedora build instructions (dependencies)

- common/src/TrenchBroomApp.cpp
It looks like you have to choose between access to the stack trace (by catching it using SEH which this PR implements), and access to the C++ exception object, but not being able to see the stack trace from when the exception was thrown (like we were doing before).
IMO the stack trace will be more useful - a good example is a bug like this: https://github.com/kduske/TrenchBroom/issues/3325
Fixes #3325
> 3325: capture stack trace of uncaught C++ exceptions on Windows

- Build.md
> 3318: Update Build.md for Win64

- app/resources/games/Quake/GameConfig.cfg
> 3329: Change default Quake map format to Valve

- travis-linux.sh
- travis-macos.sh
> 3335: don't run common-benchmark on debug builds

- common/src/View/CompilationProfileEditor.cpp
> 3311: CompilationProfileEditor: fix remove task button not disabling after adding profile

- common/src/IO/MapReader.cpp
- common/src/IO/NodeSerializer.cpp
- common/src/IO/WorldReader.cpp
- common/src/Model/EntityAttributes.cpp
- common/src/Model/EntityAttributes.h
- common/test/src/IO/NodeWriterTest.cpp
- common/test/src/IO/WorldReaderTest.cpp
> 3331: persist layer lock / hidden state

- Coding Standards.md
- common/src/IO/GameConfigParser.cpp
- common/src/Model/Brush.cpp
- common/src/Model/Polyhedron_ConvexHull.h
- common/src/View/MapFrame.cpp
> 3357: Replace anonymous namespaces with static functions

- common/src/View/ViewPreferencePane.cpp
> 3344: make the brightness slider have a more logical scale

- common/src/View/SpinControl.cpp
> 3373: fix SpinControl Ctrl modifier on XFCE

- common/src/View/ResizeBrushesTool.cpp
> 3389: remove snapping along face normal

- common/src/View/MapDocumentCommandFacade.cpp
> 3391: Fix resizing one face out of 2 selected brushes

- common/src/View/ResizeBrushesTool.cpp
> 3394: fix "grid snap off" case in ResizeBrushesTool

- app/resources/games/Heretic2/heretic2.fgd
> 3380: heretic2.fgd revisions from @whirledtsar

- common/src/View/RotateObjectsHandle.cpp
> 3368: increase rotate handle line width for visibility

- common/src/View/Actions.cpp
> 3406: fix "make structural" keybinding

- common/src/View/KeyboardShortcutModel.cpp
> 3408: fix assertion failure when "restore defaults" clicked on key bindings preference page

- lib/kdl/include/kdl/result_io.h
> 3429: Replace invalid characters where spaces should be used

- common/src/View/CompilationDialog.cpp
- common/src/View/CompilationDialog.h
- common/src/View/CompilationProfileEditor.cpp
- common/src/View/CompilationProfileEditor.h
- common/src/View/CompilationProfileManager.cpp
- common/src/View/CompilationProfileManager.h
> 3423: update Compile buttons when a profile is edited

- common/src/Renderer/GroupRenderer.cpp
- common/src/View/ViewEditor.cpp
> 3452: link rendering of group names to group bounds

- app/resources/games/Heretic2/GameConfig.cfg
> 3455: add "Quake2 (Valve)" format for Heretic2

- app/resources/games/Heretic2/heretic2.fgd
> 3469: heretic2.fgd updates from whirledtsar 

- common/src/Renderer/Camera.cpp
- common/src/View/MapDocument.cpp
Related: #1914
Making this PR to generate a build
> 1914: raise default world bounds to +/- 32768

- common/src/View/MapView2D.cpp
> 3474: fix 2D grid disappearing

- common/src/View/Actions.cpp
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
> 3524: add File -> Revert menu item

- common/src/IO/NodeSerializer.cpp
- common/test/src/IO/NodeWriterTest.cpp
> 3542: don't write layers as locked if they are inheriting the lock

- common/src/View/VertexToolBase.h
> 3558: Refresh all views after lasso selection in vertex tool

- common/src/View/CompilationRunner.cpp
> 3528: log working directory before starting compilation

- .github/workflows/clean-commit.yml
> 3597: Use our own fork of the clean-commit action

- common/src/IO/NodeSerializer.cpp
- common/src/Model/EditorContext.cpp
- common/src/Model/GroupNode.cpp
- common/src/Model/ModelUtils.cpp
- common/src/Model/NodeCollection.cpp
- common/src/Model/NodeVisitor.h
- common/src/Model/WorldNode.cpp
- common/src/View/ClipTool.cpp
- common/src/View/DuplicateNodesCommand.cpp
- common/src/View/MapDocument.cpp
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapViewBase.cpp
- common/src/View/VertexToolBase.h
- common/test/src/Model/NodeTest.cpp
> 3599: Disallow use of auto as the parameter type in node visitors

- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapView2D.cpp
- common/test/src/View/MapDocumentTest.cpp
Fixes #3591 
I decided to also move it to MapDocument with the other selection methods add a test, since Select Tall has broken before and we had no tests for it.
> 3591: fix selectTall

- app/resources/documentation/manual/index.md
🤡 
https://github.com/TrenchBroom/TrenchBroom/issues/3503
> 3503: Addressing typos in manual

- common/src/Model/EntityNode.cpp
- common/test/src/Model/EntityNodeTest.cpp
> 3549: Fix wrong area computation for Z axis direction

- appveyor.bat
> 3628: fix appveyor succeeding on crashes

- common/test/src/IO/NodeWriterTest.cpp
This test is used to ensure that we do not unintentionally change the float formatting in the future.
> 3657: Add test to nail down float formatting when serializing maps

- common/src/View/LayerEditor.cpp
- common/src/View/LayerEditor.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapViewBase.cpp
> 3636: add "Select All in Layers" map view context menu

- common/src/IO/MapParser.cpp
- common/src/IO/MapParser.h
- common/src/IO/StandardMapParser.cpp
- common/src/Model/EntityNode.cpp
- common/src/Model/EntityNodeIndex.cpp
- common/src/Model/GroupNode.cpp
- common/src/Model/Node.cpp
- common/src/Model/Node.h
This is my previous PR https://github.com/TrenchBroom/TrenchBroom/pull/3650 but with the merge conflicts fixed.
Fixes #3648
> 3648_2: finish loading optimizations

- common/src/View/LayerEditor.cpp
- common/src/View/LayerEditor.h
- common/src/View/MapFrame.cpp
- common/src/View/ViewUtils.cpp
- common/src/View/ViewUtils.h
> 2367: show previous group name when renaming groups

- app/resources/graphics/images/ResetTexture.svg
- app/resources/graphics/images/ResetTextureToWorld.svg
This PR changes the icons for both "Reset" buttons in the UV editor.
> 1997: Improve texture reset icons

- app/resources/games/Quake/Quoth2.fgd
> 1211: Quoth2.fgd updates from @Lain-tf

- common/src/View/GameDialog.cpp
- common/src/View/GameListBox.cpp
> 3531: Prevent crash with invalid game selection in game dialog

- common/src/View/GameListBox.cpp
Only valgrind detected this.
Fixes #3712
> 3712: fix incorrect array bounds check

- common/src/View/LayerListBox.cpp
> 3624: Remember selected layer when reloading after node changes

- common/src/Renderer/GroupRenderer.cpp
- common/src/Renderer/GroupRenderer.h
- common/src/Renderer/MapRenderer.cpp
- common/src/Renderer/ObjectRenderer.cpp
- common/src/Renderer/ObjectRenderer.h
> 3723: Allow per group colors for bounds and name labels

- common/test/src/View/CompilationRunToolTaskRunnerTest.cpp
CompilationRunnerTest starts an event loop in order to be able to use
QTimer to wait for a timeout. Starting an event loop when there is an
instance of QApplication leads to the TB welcome window popping up
during the test run, which is annoying (and slow).
This commit replaces QTimer with a mutex and a condition variable so
that we can use std thread primitives to wait for the runner to exit.
> 3743: Don't start an event loop during tests

- README.md
also remove build status icons for the unused CI services
> README.md: add manual link

- cmake/Utils.cmake
- common/src/Assets/EntityModelManager.cpp
- common/src/EL/Expression.cpp
- common/src/EL/Value.cpp
- common/src/IO/ImageFileSystem.cpp
- common/src/IO/MapReader.cpp
- common/src/IO/Parser.h
- common/src/Model/ModelUtils.cpp
- common/src/Model/Polyhedron_Matcher.h
- common/src/Renderer/EntityModelRenderer.cpp
- common/src/Renderer/FaceRenderer.cpp
- common/src/Renderer/PointHandleRenderer.cpp
- common/src/Renderer/PrimitiveRenderer.cpp
- common/src/Renderer/TexturedIndexRangeMap.cpp
- common/src/View/BrushVertexCommands.cpp
- common/src/View/ClipTool.cpp
- common/src/View/EntityBrowserView.cpp
- common/src/View/EntityPropertyEditor.cpp
- common/src/View/MapDocument.cpp
- common/src/View/MapDocumentCommandFacade.cpp
- common/src/View/MapFrame.cpp
- common/src/View/SmartPropertyEditorManager.cpp
- common/src/View/TextureBrowserView.cpp
- common/src/View/VertexHandleManager.cpp
- common/src/View/VertexHandleManager.h
- lib/kdl/CMakeLists.txt
- lib/kdl/include/kdl/map_utils.h
> 3751: convert for loops with pairs to structured bindings

- common/src/Model/GroupNode.cpp
- common/src/Model/GroupNode.h
- common/src/View/MapDocument.cpp
- common/test/CMakeLists.txt
- common/test/src/Catch2.h
- common/test/src/View/GroupNodesTest.cpp
- lib/kdl/include/kdl/set_adapter.h
> 3748: Reset Duplicate persistent group IDs when pasting nodes

- common/src/IO/BrushFaceReader.cpp
- common/src/IO/BrushFaceReader.h
- common/src/IO/MapParser.cpp
- common/src/IO/MapParser.h
- common/src/IO/MapReader.cpp
- common/src/IO/MapReader.h
- common/src/IO/NodeReader.cpp
- common/src/IO/NodeReader.h
- common/src/IO/StandardMapParser.cpp
- common/src/IO/StandardMapParser.h
- common/src/IO/WorldReader.cpp
- common/src/IO/WorldReader.h
- common/test/src/Model/BrushFaceTest.cpp
I have tried to move as many implementation details into the cpp file as possible, and to further simplify the code and the control flow. I haven't split this up into lots of small commits because it was done as an exploration that turned out successful. I could split this up into smaller commits if requested.
> 2429: Refactor map reader

- common/src/View/ClipToolController.cpp
- common/src/View/ClipToolController.h
- common/src/View/CreateComplexBrushToolController3D.cpp
- common/src/View/EdgeToolController.cpp
- common/src/View/FaceToolController.cpp
- common/src/View/MapView2D.cpp
- common/src/View/MapView3D.cpp
- common/src/View/RotateObjectsToolController.cpp
- common/src/View/RotateObjectsToolController.h
- common/src/View/SelectionTool.cpp
- common/src/View/SelectionTool.h
- common/src/View/ToolBoxConnector.cpp
- common/src/View/ToolBoxConnector.h
- common/src/View/ToolChain.cpp
- common/src/View/ToolChain.h
- common/src/View/ToolController.cpp
- common/src/View/ToolController.h
- common/src/View/UVView.cpp
- common/src/View/VertexToolController.cpp
Some cherry-picked cleanup commits from https://github.com/TrenchBroom/TrenchBroom/pull/3823 and https://github.com/TrenchBroom/TrenchBroom/pull/3819.
> 3781: Cleanups

- common/src/View/MapFrame.cpp
> 3832: Add .lin file extension to open point file dialog

- common/src/Notifier.h
This PR fixes a crash that can occur when closing a window.
Notifier must be a move-only-type because otherwise not all observers
get disconnected properly if a notifier is copied by accident. This
reveals a bug where connecting one notifier to another copies the
observing notifier. To prevent this, we provide a separate overload to
Notifier::connect that takes the observing notifier by reference,
avoiding the copy.
> 3781: Make Notifier move-only

- common/src/View/CompilationRunner.cpp
- common/test/CMakeLists.txt
- common/test/src/View/CompilationRunnerTest.cpp
> 3833: Create target directories when executing copy files task

- common/CMakeLists.txt
- common/src/View/FaceAttribsEditor.cpp
- common/src/View/FaceAttribsEditor.h
- common/src/View/MapFrame.cpp
- common/src/View/MapFrame.h
- common/src/View/MapViewBase.cpp
- common/src/View/MapViewBase.h
- common/src/View/SignalDelayer.cpp
- common/src/View/SignalDelayer.h
Fixes #3822
With this as well as https://github.com/TrenchBroom/TrenchBroom/pull/3858 we are back up to ~100fps on the #3822 test case (from ~22fps on current `master`).
> 3822_2: Delay and coalesce processing of some expensive UI updates

- common/src/View/ScaleObjectsTool.cpp
- common/src/View/ScaleObjectsToolController.cpp
getInitialHandlePositionAndOffset() needs to use the same logic for choosing handles as makeHandlePositionProposer().
Fixes #3847
> 3847: Fix scale tool back face dragging

- common/src/View/MapViewBase.cpp
- common/src/View/MapViewBase.h
- common/src/View/SignalDelayer.cpp
Fixes #3869
Forgot to make this connection in d85ab527cfacf7c922e49f13d08df6cf919b6a08
> 3869: add missing connection from SignalDelayer to MapViewBase::updateActionStates

- common/src/IO/DefParser.cpp
- common/src/IO/ELParser.cpp
- common/src/IO/ELParser.h
- common/src/IO/FgdParser.cpp
- common/src/IO/LegacyModelDefinitionParser.cpp
- common/src/IO/LegacyModelDefinitionParser.h
- common/src/IO/Tokenizer.h
- common/test/src/IO/FgdParserTest.cpp
> 3859: .FGD/.DEF parser: initialize EL sub-parser with correct line/column

- common/src/View/MapDocument.cpp
- common/src/View/RepeatStack.cpp
- common/src/View/RepeatStack.h
- common/test/src/View/RepeatableActionsTest.cpp
> 3860: Handle transactions when repeating

- common/src/Model/GameFactory.cpp
- common/src/Model/GameFactory.h
- common/src/TrenchBroomApp.cpp
- common/test/CMakeLists.txt
- common/test/src/IO/DiskFileSystemTest.cpp
- common/test/src/IO/TestEnvironment.cpp
- common/test/src/IO/TestEnvironment.h
- common/test/src/Model/GameFactoryTest.cpp
- common/test/src/View/AutosaverTest.cpp
- common/test/src/View/CompilationRunnerTest.cpp
Fixes #3904
This was broken in the course of a refactoring. This PR adds a test and fixes the issue.
> 3904: Fix loading compilation profiles

- app/resources/documentation/manual/index.md
This should fix three small typos in the manual.
> Fixing typos in the manual

- common/src/Assets/ModelDefinition.cpp
- common/src/Assets/ModelDefinition.h
- common/src/Model/Entity.cpp
- common/src/View/EntityBrowserView.cpp
- common/test/CMakeLists.txt
- common/test/src/Model/EntityRegressionTest.cpp
> 3914: Catch exceptions thrown when evaluating model scale

- common/src/TrenchBroomApp.cpp
- common/src/View/CrashDialog.cpp
- common/src/View/CrashDialog.h
I'm extracting this from another branch because it's unrelated and can be merged now. This improves how the crash dialog looks, and adds the crash reason to the dialog.
> Crash Dialog UI improvements

- common/src/Model/BrushFaceHandle.cpp
- common/src/Model/BrushFaceHandle.h
- common/src/Model/Hit.h
- common/src/Model/Polyhedron.h
- common/src/View/Grid.cpp
- common/src/View/ResizeBrushesTool.cpp
- common/src/View/ResizeBrushesTool.h
- common/src/View/ResizeBrushesToolController.cpp
- common/src/View/ResizeBrushesToolController.h
- common/src/View/VertexHandleManager.cpp
- common/test/src/View/ResizeBrushesToolTest.cpp
This PR contains a number of cleanups extracted from another branch. That other branch has become quite complex, so I extracted these cleanups to make the history simpler to understand. None of the commits on this branch change any behavior.
> Various Cleanups

- common/src/View/ResizeBrushesTool.cpp
- common/src/View/ResizeBrushesTool.h
- common/src/View/ResizeBrushesToolController.cpp
- common/src/View/ToolBox.cpp
- common/src/View/ToolBox.h
- common/src/View/ToolBoxConnector.cpp
- common/test/src/View/ResizeBrushesToolTest.cpp
- lib/kdl/include/kdl/struct_io.h
This PR cleans up the resizing tool and is a preparation to fix #3909. It doesn't change the behavior of the tool at all.
> 3909: Resize tool refactoring and cleanup

- common/src/View/EntityBrowserView.cpp
- common/src/View/EntityBrowserView.h
> 3971: Don't apply model scale in entity browser

- common/src/View/MapDocument.cpp
- common/test/src/View/SelectionTest.cpp
> 3931: Fix select siblings command

- common/src/IO/MapFileSerializer.cpp
- common/test/src/IO/NodeWriterTest.cpp
> 3951: Quote texture names when serializing to Valve format

- .github/workflows/ci.yml
- CMakeLists.txt
- app/CMakeLists.txt
- common/benchmark/CMakeLists.txt
- common/test/CMakeLists.txt
- dump-shortcuts/CMakeLists.txt
> 3996: find all needed .dll's to install using file(GET_RUNTIME_DEPENDENCIES

- common/src/Model/ModelUtils.cpp
- common/src/Model/ModelUtils.h
- common/src/View/SelectionTool.cpp
- common/test/src/View/SelectionToolTest.cpp
- lib/kdl/include/kdl/range_io.h
- lib/kdl/test/src/range_io_test.cpp
> 4030: Fix group selection

- .github/workflows/ci.yml
> 4036: Don't upload all Ubuntu binaries for releases

- common/src/Assets/ModelDefinition.cpp
- common/src/Assets/ModelDefinition.h
- common/src/EL/VariableStore.cpp
- common/src/EL/VariableStore.h
- common/src/IO/EntParser.cpp
- common/src/IO/LegacyModelDefinitionParser.cpp
- common/src/Model/EntityPropertiesVariableStore.cpp
- common/src/Model/EntityPropertiesVariableStore.h
- common/test/src/Model/EntityTest.cpp
> 4038: Spawnflags default to 0 when evaluating model expressions

- common/src/View/EntityPropertyGrid.cpp
- common/src/View/EntityPropertyGrid.h
- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/test/src/View/MapDocumentTest.cpp
> 4051: Don't crash if an entity property cannot be added

- app/resources/games/Kingpin/GameConfig.cfg
> 4027: Update kingpin gameconfig

- common/src/View/FlyModeHelper.cpp
- common/src/View/FlyModeHelper.h
Closes #4014
It doubles the speed with shift
it halves the speed with alt.
I have a separate branch for putting the speed modifier in a variable, since I have to figure out the UI system a bit better, to iron out the quirks.
> Use shift to sprint and alt to crawl

- common/src/View/Actions.cpp
> Allow texture alignment reset in any view

- common/src/View/MapDocument.cpp
- common/src/View/MapDocument.h
- common/src/View/MapViewBase.cpp
- common/test/src/View/MapDocumentTest.cpp
> 4113: Deselect nodes before creating point entity

- common/src/View/FlyModeHelper.cpp
> Reset fast / slow key state along with movement key state

- .clang-tidy
- common/src/Model/EntityProperties.cpp
- common/src/Model/EntityProperties.h
- common/src/Renderer/BrushRenderer.cpp
- common/src/Renderer/BrushRenderer.h
- common/src/Renderer/BrushRendererBrushCache.cpp
- common/src/Renderer/BrushRendererBrushCache.h
- common/src/Renderer/EdgeRenderer.cpp
- common/src/Renderer/EdgeRenderer.h
- common/src/Renderer/MapRenderer.cpp
- common/src/Renderer/MapRenderer.h
- common/src/Renderer/ObjectRenderer.h
- common/src/Renderer/PatchRenderer.cpp
- common/src/Renderer/PatchRenderer.h
- common/src/Renderer/RenderBatch.cpp
- common/src/View/SetVisibilityCommand.cpp
- common/src/View/SetVisibilityCommand.h
> 4125: Don't render hidden patches

- common/benchmark/CMakeLists.txt
- common/src/Model/Issue.cpp
- common/src/View/IssueBrowserView.cpp
- common/test/CMakeLists.txt
> 4132: Don't crash when accessing issues

- .github/workflows/ci.yml
- CI-linux.sh
- app/CMakeLists.txt
- app/cmake/PrintLinuxPackageInfo.sh.in
> Remove support for building RPM packages

- common/src/View/SmartPropertyEditorManager.cpp
- common/src/View/SmartPropertyEditorManager.h
- common/src/View/SmartPropertyEditorMatcher.cpp
- common/src/View/SmartPropertyEditorMatcher.h
- common/src/View/SmartTypeEditorMatcher.cpp
- common/src/View/SmartTypeEditorMatcher.h
Closes #4146.
The smart color editor is now also shown for properties with key `color`.
> 4146: Add "color" to the color picker trigger list

- common/src/View/MapDocument.cpp
- common/test/src/View/CopyPasteTest.cpp
> 4174: Make pasting nodes transactional

- common/src/View/MapFrame.cpp
> 4184: Split line numbers correctly

- common/src/PreferenceManager.cpp
- common/src/TrenchBroomApp.cpp
Closes #3952 (and also part of #4171).
See also [this comment](https://github.com/TrenchBroom/TrenchBroom/issues/4171#issuecomment-1374129804).
> 3952: Don't show modal dialogs while painting a GL view

- common/src/IO/ImageSpriteParser.cpp
- common/src/IO/SprParser.cpp
- common/src/View/EntityBrowserView.cpp
- common/src/View/EntityBrowserView.h
> 4140: Fix sprite alignment

- app/resources/documentation/manual/index.md
- common/src/IO/CompilationConfigParser.cpp
- common/src/IO/CompilationConfigParser.h
- common/src/IO/CompilationConfigWriter.cpp
- common/src/IO/CompilationConfigWriter.h
- common/src/IO/ConfigParserBase.cpp
- common/src/IO/ConfigParserBase.h
- common/src/Model/CompilationConfig.cpp
- common/src/Model/CompilationConfig.h
- common/src/Model/CompilationProfile.cpp
- common/src/Model/CompilationProfile.h
- common/src/Model/CompilationTask.cpp
- common/src/Model/CompilationTask.h
- common/src/View/CompilationProfileEditor.cpp
- common/src/View/CompilationProfileEditor.h
- common/src/View/CompilationRunner.cpp
- common/src/View/CompilationRunner.h
- common/src/View/CompilationTaskListBox.cpp
- common/src/View/CompilationTaskListBox.h
- common/test/src/IO/CompilationConfigParserTest.cpp
- common/test/src/View/CompilationRunnerTest.cpp
Closes #3887
Original PR: https://github.com/TrenchBroom/TrenchBroom/pull/4155
> 3887: Add a "Delete Files" task

- app/resources/linux/postinst
- app/resources/linux/prerm
> check if `xdg-desktop-menu` pre-requisites are met before running it in .deb's scripts

- common/src/View/MapFrame.cpp
> 4152: Update undo on focus change

- common/src/View/CompilationDialog.cpp
- common/src/View/CompilationDialog.h
- common/src/View/CompilationProfileEditor.cpp
- common/src/View/CompilationProfileListBox.cpp
- common/src/View/CompilationProfileManager.cpp
- common/src/View/CompilationRunner.cpp
- common/src/View/CompilationTaskListBox.cpp
> 4211: Fix compilation dialog bugs

- common/src/View/LaunchGameEngineDialog.cpp
> Remove unwanted line breaks

- common/src/IO/Reader.cpp
- common/src/IO/Reader.h
- common/test/src/IO/tst_Reader.cpp
We refactor the `Reader` type and make it a bit more efficient to use.
> Refactor Reader

- app/CMakeLists.txt
- app/resources/mac/TrenchBroom-Info.plist
Reverts #f9754e0 and makes some cleanups.
> Fix application icon on macOS

- common/src/Model/GameFactory.cpp
- common/src/Model/GameFactory.h
- common/src/TrenchBroomApp.cpp
- common/test/src/Model/tst_GameFactory.cpp
> Don't crash on parse errors in game configurations or user profiles

- common/src/Model/GameFactory.cpp
- common/src/Model/GameFactory.h
- common/test/src/Model/tst_GameFactory.cpp
> 4292: Create necessary directories when saving compilation and game engine configs

- common/src/Assets/Palette.cpp
- common/src/IO/ReadMipTexture.cpp
> Allow embedded palettes with arbitrary sizes in mip textures

- common/src/IO/ImageSpriteParser.cpp
- common/src/IO/ImageSpriteParser.h
> Allow more image formats for sprites

- common/src/View/GameEngineDialog.cpp
- common/src/View/GameEngineDialog.h
- common/src/View/GameEngineProfileEditor.cpp
- common/src/View/GameEngineProfileEditor.h
- common/src/View/GameEngineProfileListBox.cpp
- common/src/View/GameEngineProfileListBox.h
- common/src/View/GameEngineProfileManager.cpp
- common/src/View/GameEngineProfileManager.h
- common/src/View/LaunchGameEngineDialog.cpp
> 4268: Fix delete button for engine profiles

- common/src/View/MapViewBase.cpp
- common/test/src/View/tst_CompilationRunner.cpp
> 4306: Don't crash trying to merge a group into an open group

- common/src/View/ToolChain.cpp
> 4340: Fix condition for accepting drag events in the tool chain

- lib/vecmath/include/vecmath/intersection.h
> 4303: Remove unused include

- common/src/Model/PushSelection.cpp
- common/src/Model/PushSelection.h
- common/src/View/ReplaceTextureDialog.cpp
- common/src/View/ReplaceTextureDialog.h
> 4392: Restore selection after replacing textures

- common/src/IO/ImageSpriteParser.cpp
- common/src/IO/LoadTextureCollection.cpp
- common/src/IO/ReadFreeImageTexture.cpp
- common/src/IO/ReadFreeImageTexture.h
- common/test/src/IO/tst_ReadFreeImageTexture.cpp
Closes #4375.
Supersedes https://github.com/TrenchBroom/TrenchBroom/pull/4384
> Support all freeimage formats for textures and sprites

- common/src/IO/ReadFreeImageTexture.cpp
- common/src/Renderer/FontFactory.h
- common/src/Renderer/FreeTypeFontFactory.cpp
- common/src/Renderer/FreeTypeFontFactory.h
- lib/kdl/CMakeLists.txt
- lib/kdl/include/kdl/resource.h
- lib/kdl/test/CMakeLists.txt
- lib/kdl/test/src/tst_resource.cpp
This type makes it easier to manage resources from external libraries such as freeimage.
> Add kdl::resource wrapper type

- common/src/IO/File.cpp
- common/src/IO/File.h
- common/src/IO/LoadTextureCollection.cpp
- common/src/IO/ReadFreeImageTexture.cpp
- common/src/IO/Reader.cpp
- common/src/IO/Reader.h
- common/src/IO/ZipFileSystem.cpp
- common/src/IO/ZipFileSystem.h
This PR improves texture loading under certain circumstances.
Changes:
- Sample fewer pixels when computing the average texture color
> 4383: Improve texture loading performance

- common/src/Model/EntityNodeBase.cpp
- common/src/Renderer/EntityLinkRenderer.cpp
- common/src/Renderer/EntityLinkRenderer.h
- common/src/Renderer/LinkRenderer.cpp
- common/src/Renderer/LinkRenderer.h
- common/test/src/Model/tst_EntityNodeLink.cpp
> 4267: Fix updating entity links when setting targetname property

- common/src/Model/BrushBuilder.cpp
- common/test/src/Model/tst_BrushBuilder.cpp
> 4429: Always use default face attributes in BrushBuilder

- common/src/Renderer/EntityLinkRenderer.cpp
> 4431: Don't recurse infinitely when collecting transitively selected links

- common/src/Model/EntityNodeBase.cpp
> Don't crash when editing multiple entities

- app/resources/graphics/images/Conflict.svg
- common/src/IO/ResourceUtils.cpp
- common/src/IO/ResourceUtils.h
- common/src/View/MousePreferencePane.cpp
- common/src/View/MousePreferencePane.h
> 4207: Show conflicts for move keys in mouse preferences

- common/src/Model/Entity.cpp
- common/test/src/Model/tst_Entity.cpp
> 4005: Handle nan in entity origin

- common/src/IO/ELParser.cpp
- common/src/IO/ELParser.h
- common/src/IO/FgdParser.cpp
- common/src/IO/FgdParser.h
- common/test/src/IO/tst_ELParser.cpp
- common/test/src/IO/tst_FgdParser.cpp
> 4438: Create default model specification for empty sprite() expression

- common/src/View/SetBrushFaceAttributesTool.cpp
- common/src/View/SetBrushFaceAttributesTool.h
> 3926: Fix errors when applying face attributes across linked groups

- common/src/View/MapFrame.cpp
Found this one by accident. When pasting nodes, a subsequent undo will only undo the translation that takes the pasted nodes to the cursor position.
> Wrap paste and subsequent translation in transaction

- common/src/View/CellView.cpp
- common/src/View/TextureBrowserView.cpp
Fixes a rendering bug introduced in https://github.com/TrenchBroom/TrenchBroom/pull/4482
> Fix CellView render order

- common/src/View/MapDocument.cpp
> 4487: Don't collect link IDs recursively

- common/src/View/SetBrushFaceAttributesTool.cpp
> 4496: Fix selection of target faces for situations involving nested linked groups

- common/src/View/ClipTool.cpp
- common/src/View/ClipToolController.cpp
> 4508: Don't access out of bounds clip points

- common/src/TrenchBroomApp.cpp
- common/src/TrenchBroomApp.h
- common/src/View/RecentDocuments.cpp
- common/src/View/RecentDocuments.h
> 4511: Return a copy of recent documents for safety

- common/src/View/MousePreferencePane.cpp
> 4517: Restore missing fly speed slider

- .github/workflows/ci.yml
> 4528: Update brew before installing packages

- common/src/IO/DiskIO.cpp
- common/test/src/IO/TestEnvironment.cpp
- common/test/src/IO/TestEnvironment.h
- common/test/src/IO/tst_DiskIO.cpp
> 4524: Fix symlink behavior

- common/src/Model/GameImpl.cpp
> 4531: Don't crash when parsing entity definition file fails

- .github/workflows/ci.yml
- CI-macos.sh
Removes a workaround introduced in this PR: https://github.com/TrenchBroom/TrenchBroom/pull/4529
The problem appears to have been fixed upstream, or it has resolved itself somehow.
> Remove homebrew workaround

- app/resources/documentation/manual/index.md
- app/resources/games/DDayNormandy/GameConfig.cfg
- app/resources/games/Daikatana/GameConfig.cfg
- app/resources/games/DigitalPaintball2/GameConfig.cfg
- app/resources/games/Generic/GameConfig.cfg
- app/resources/games/Halflife/GameConfig.cfg
- app/resources/games/Heretic2/GameConfig.cfg
- app/resources/games/Hexen2/GameConfig.cfg
- app/resources/games/Kingpin/GameConfig.cfg
- app/resources/games/Neverball/GameConfig.cfg
- app/resources/games/Quake/GameConfig.cfg
- app/resources/games/Quake2/GameConfig.cfg
- app/resources/games/Quake3/GameConfig.cfg
- app/resources/games/Quetoo/GameConfig.cfg
- app/resources/games/Wrath/GameConfig.cfg
- common/src/IO/GameConfigParser.cpp
- common/src/TrenchBroomApp.cpp
- common/src/TrenchBroomApp.h
- common/src/View/CachingLogger.cpp
- common/src/View/CachingLogger.h
- common/src/View/FrameManager.cpp
- common/src/View/FrameManager.h
- common/test/src/IO/tst_GameConfigParser.cpp
- common/test/src/Model/tst_GameFactory.cpp
In this PR, we update the game configuration files to version 9. This version change is required because we rename some fields in the game configuration files according to the terminology change from texture to material.
> Rename game config fields

- common/src/View/GamesPreferencePane.cpp
- common/src/View/GamesPreferencePane.h
> 4557: Don't crash when setting compilation tool paths

- common/src/View/MapDocument.cpp
> 4523: Deselect everything before setting enabled texture collections

- common/src/View/Actions.cpp
> 3930: Change default shortcut for deactivating the current tool to Shift+Escaoe

- common/src/TrenchBroomApp.cpp
> Make path absolute when opening a document

- common/src/View/Grid.cpp
- common/src/View/Grid.h
- common/src/View/VertexHandleManager.cpp
- common/test/src/View/tst_Grid.cpp
> Return std::optional from Grid::snap instead of NaN

- common/src/View/Actions.cpp
- common/src/View/Actions.h
- common/src/View/KeyboardShortcutModel.cpp
- common/src/View/KeyboardShortcutModel.h
- common/test/CMakeLists.txt
- common/test/src/View/tst_Actions.cpp
- dump-shortcuts/src/KeyStrings.cpp
- dump-shortcuts/src/KeyStrings.h
- dump-shortcuts/src/Main.cpp
In https://github.com/TrenchBroom/TrenchBroom/pull/4589 we changed a keyboard shortcut and introduced a conflict. To avoid such a problem in the future, we add a test to detect such conflicts. Then we fix the issue.
> 3930: Fix conflicting keyboard shortcuts

- common/src/View/CompilationProfileEditor.cpp
- common/src/View/IssueBrowserView.cpp
> Don't capture local variables by reference

- common/src/Model/UVCoordSystem.cpp
- common/test/src/Assets/tst_AssetUtils.cpp
- common/test/src/Assets/tst_EntityModel.cpp
- common/test/src/Catch2.h
- common/test/src/EL/tst_Expression.cpp
- common/test/src/IO/tst_AseLoader.cpp
- common/test/src/IO/tst_AseLoaderRegression.cpp
- common/test/src/IO/tst_AssimpLoader.cpp
- common/test/src/IO/tst_Md3Loader.cpp
- common/test/src/IO/tst_Md3LoaderRegression.cpp
- common/test/src/Model/tst_BrushBuilder.cpp
- common/test/src/Model/tst_EntityRotation.cpp
- common/test/src/Model/tst_GameFactory.cpp
- common/test/src/Model/tst_UVCoordSystem.cpp
- common/test/src/View/tst_Actions.cpp
- lib/kdl/test/src/catch2.h
- lib/kdl/test/src/tst_grouped_range.cpp
- lib/kdl/test/src/tst_hash_utils.cpp
> 3673: Fix axis selection when translating UV coord systems

- common/src/ui/CompilationRunner.cpp
- common/src/ui/CompilationRunner.h
- common/test/src/ui/tst_CompilationRunner.cpp
- vcpkg.json
> 4625: Don't crash when failing to interpolate variables for compilation runs

- common/src/ui/RotateObjectsTool.cpp
- common/src/ui/RotateObjectsTool.h
- common/src/ui/RotateObjectsToolPage.cpp
- common/src/ui/RotateObjectsToolPage.h
- common/test/CMakeLists.txt
- common/test/src/ui/tst_RotateObjectsTool.cpp
> 4424: Set rotation center to entity origin if exactly one entity is selected

- .github/workflows/ci.yml
- common/src/ui/CompilationProfileListBox.cpp
> Don't crash when right clicking compilation profiles

- common/src/ui/EntityBrowserView.cpp
- common/src/ui/EntityBrowserView.h
> 4573: Fix rendering of non-centered entity models in browser

- common/src/Preferences.cpp
- common/src/render/BoundsGuideRenderer.cpp
- common/src/render/RenderService.cpp
- common/src/render/SelectionBoundsRenderer.cpp
- lib/vm/include/vm/bbox.h
- lib/vm/test/src/tst_bbox.cpp
> 4338: Reduce the translucency of selection bounds

- app/resources/games/Quake2/GameConfig.cfg
Adds some missing tool options, and a few surface & content flags for special textures.
> Updated Quake2/GameConfig.cfg

- common/src/ui/MapDocument.cpp
- common/src/ui/MapDocument.h
- common/test/src/ui/tst_TagManagement.cpp
> 4660: Update face tags when resources were processed

- common/src/io/GameConfigParser.cpp
- common/src/mdl/Tag.cpp
- common/src/mdl/Tag.h
- common/src/mdl/TagAttribute.cpp
- common/src/mdl/TagAttribute.h
- common/src/mdl/TagManager.cpp
These are a few leftover cleanups from a previous attempt at fixing #4595.
> 4595: Cleanups

- common/src/io/File.cpp
- common/src/io/File.h
- common/src/io/LoadMaterialCollections.cpp
- common/src/mdl/GameFileSystem.cpp
- common/test/CMakeLists.txt
- common/test/src/io/ObjectFile.h
- common/test/src/io/TestFileSystem.cpp
- common/test/src/io/tst_LoadMaterialCollections.cpp
- common/test/src/io/tst_VirtualFileSystem.cpp
> Restore the ability to group textures by the containing wad files

- common/src/io/LoadMaterialCollections.cpp
> Don't return error when material config does not have a palette key

- app/resources/games/Halflife/GameConfig.cfg
Add compilation tools to GameConfig.cfg:
-csg
-bsp
-vis
-rad
> Update HL GameConfig.cfg

- common/src/ui/MapDocument.cpp
- common/test/src/ui/tst_MapDocument.cpp
> Fix omitting layers from export

- Build.md
- app/resources/games/Quetoo/GameConfig.cfg
- app/resources/games/Quetoo/Quetoo.fgd
Reverts TrenchBroom/TrenchBroom#4735
> Revert "Minor Quetoo game configuration updates and macOS Build.md corrections"

- common/src/io/FgdParser.cpp
- common/test/src/io/tst_FgdParser.cpp
> Allow numeric entity property key definitions

- common/src/ui/SmartPropertyEditorManager.cpp
- common/src/ui/SmartPropertyEditorManager.h
> Don't override smart choice property editor with color property editor

- app/resources/games/Hexen2/GameConfig.cfg
Updated to add :
- Compile tool path options to preferences.
- Copied over brush/face tags from quake's cfg since they work here as well.
> Update GameConfig.cfg Hexen 2

- .github/workflows/ci.yml
- app/CMakeLists.txt
> Create an arm64 build for Apple Silicon

- common/src/ui/LaunchGameEngineDialog.cpp
> Don't build command string manually when launching engine

- common/src/render/EntityRenderer.cpp
> Render point entities as solid while their model is not loaded yet

- .github/workflows/ci.yml
- Build.md
- CI-macos.sh
- app/CMakeLists.txt
- app/cmake/SignMacOsArchive.sh.in
Zip files are much easier to handle for in-app updates.
> Use zip generator for macOS instead of creating a dmg

- app/resources/games/Quake/Quake.fgd
https://github.com/TrenchBroom/TrenchBroom/issues/4802
> xaGe quake.fgd updates

- vcpkg.json
See https://github.com/microsoft/vcpkg/issues/44199.
> Fix RapidJSON build error on Windows

- common/src/mdl/Polyhedron_Misc.h
This is a followup to #4813 to fix a build error
> Add missing include

- .github/workflows/ci.yml
- CI-linux.sh
- CI-macos.sh
- common/src/Ensure.cpp
We use the github cache action to cache ccache's cache (what a sentence).
> Use ccache for CI mac and linux builds

- common/src/io/AssimpLoader.cpp
> Don't rotate HL models by 90degs about Z axis

- common/src/render/EntityRenderer.cpp
> Make entity rendering consistent

- common/src/mdl/EntityColor.cpp
- common/src/mdl/EntityColor.h
> Fix entity color parsing

- common/src/mdl/BezierPatch.cpp
- common/src/mdl/BezierPatch.h
- common/src/mdl/BrushFace.cpp
- common/test/src/mdl/tst_BezierPatch.cpp
- lib/vm/include/vm/mat_ext.h
- lib/vm/test/src/tst_mat_ext.cpp
> Fix mirroring of Bezier patches

- common/src/TrenchBroomApp.cpp
- common/src/ui/QtUtils.h
- common/test/CMakeLists.txt
- common/test/src/RunAllTests.cpp
- common/test/src/ui/tst_QtUtils.cpp
- lib/kdl/src/kdl/struct_io.h
- lib/kdl/test/src/run_all.cpp
> Fix locale dependent formatting and parsing of floating point values

- common/src/ui/UpdateConfig.cpp
- lib/upd/src/upd/InstallUpdate.cpp
- lib/upd/src/upd/InstallUpdate.h
- lib/upd/src/upd/UpdateConfig.h
- lib/upd/src/upd/UpdateController.cpp
- lib/upd/src/upd/UpdateController.h
- lib/upd/src/upd/UpdateDialog.cpp
- lib/upd/src/upd/UpdateDialog.h
- lib/upd/test/src/upd/tst_UpdateController.cpp
> Ask for elevated privileges on Windows when installing an update if necessary

- common/src/ui/MapViewBase.cpp
- common/src/ui/MapViewBase.h
> Use consistent filtering when creating and clicking create entity menu
