Source/IO/MapParser.cpp
Reported by thewaz154 on func: http://www.celephais.net/board/view_thread.php?id=60908&start=1514
Sorry I didn't catch this before the 1.1.2 release :(
"parseEntity(worldBounds, forceIntegerFacePoints ? Integer : Float, NULL)" was causing an unwanted implicit conversion of the Integer or Float enum values to bool, instead of calling the desired function that takes a FacePointFormat&.
It seems that `parseEntity(.., Integer, ..);` will cause an implict conversion to bool, but:
```
FacePointFormat f = Integer;
parseEntity(.., f, ..);
```
will call the version that takes FacePointFormat&.
=> Fix for copy/paste causing rounding to integer plane points, even when the map format is float.

Source/Renderer/Vbo.cpp
Fixes bug reported by thewaz154:
```
#1. load trenchbroom and open a map with a decent amount of stuff in it and dont do anything yet
#2. go to face texture browser, pick a texture, and then create a brush
#3. re-size, clone, or copypaste that brush
#4. watch as trenchbroom crashes :c
this issue can be bypassed by moving, re-sizing, or cloning and already existing world brush and it wont happen for the rest of the session but its a bit annoying to have to do that every time i open my map up again
moving, cloning, or editing non brush entities doesnt bypass this
```
With _DEBUG_VBO 1, there is also no longer an assertion failure when performing the above steps
=> Vbo::resizeVbo: add missing update to m_last.

Source/IO/MapParser.cpp, Source/View/MapPropertiesDialog.cpp
Adds a call to map.setForceIntegerFacePoints(true) if "_point_format" "1" is set in the map. Previously, the map->m_forceIntegerFacePoints variable would be incorrectly left as false when loading a map with "_point_format" "1".
=> Fix for editing tools not snapping to integer face points when loading a map with "_point_format" "1" in the worldspawn.

common/src/View/CommandIds.h
This fixes an "expected unqualified-id" error on Arch Linux.
=> Rename Actions::None to Actions::Nothing.

common/src/Model/AttributableNode.cpp
the implictly created one was being deallocated.
Fixes a crash when right-clicking the 3d editing view.
=> AttributableNode::doGetName(): make a static String object for "<missing classname>"

common/src/IO/MapReader.cpp, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceSnapshot.cpp
.., the rotatation is already part of the texture vectors
This is a (ugly ?) fix for https://github.com/kduske/TrenchBroom/issues/921
It fixes it in a shorter way than https://github.com/kduske/TrenchBroom/pull/923 , not sure if this way is better
=> BrushFace::setAttribs(): don't rotate the texCoordSystem further when we're loading a valve220 map

Mac/Build.txt, Mac/TrenchBroom.xcodeproj/project.pbxproj, Mac/wxWidgets-patches/webview_webkit_OSX_10_10_build_fix.patch, Source/Controller/InputController.cpp, Source/IO/Wad.cpp, Source/Model/BrushGeometry.cpp, Source/Model/Entity.cpp, Source/Utility/Vec.h, Source/View/EditorView.cpp, Test/Source/Utility/VecTest.h
Hey, I've gathered a few patches that could make a nice bugfix release to TB1.
7b29aef fixes the last "vertex drift" I'm aware of, it affected some copy/paste operations on maps with "force integer plane points" 
08699ac and 095b5cf fix what I think was the most common crash (assertion failure) in vertex manip mode; I just backported the fix from the 'develop' branch
a10d458 fixes a bug where renaming an entity key corrupts the value for that key.
There are a few other minor things.
Also, I have both a windows & mac build environment set up. If these changes sound good to you I'm happy to make the builds.
=> some TB1 patches

test/src/PlaneTest.cpp
It's currently failing on the last assertion that checks the distance from some test vertices and the integer plane. 
Related to the discussion in https://github.com/kduske/TrenchBroom/issues/1033
Here is the whole map file for reference:
```
{
"spawnflags" "0"
"classname" "worldspawn"
{
( 48 18 22 ) ( 48 16 8 ) ( 48 16 28 ) carch02 368 -32 0 1 1
( 16 18 21.998046875 ) ( 16 16 27.9980487823486328125 ) ( 16 16 7.998046875 ) carch02 368 -32 0 1 1
//
// This next one with the 'clip' texture is the plane that gets distorted.
//
// For reference, there are 4 verts on this plane:
// (48 18 22), (48 16 28), (16 16 28), (16 18 22)
// (ignoring floating point error)
//
// The bad plane that the algorithm finds (in TB 1.1.5) is:
// ( 1439 263 -713 ) ( 49 -136 484 ) ( -0 23 8 )
//
( 48 16 28 ) ( 16 …
```
=> test/src/PlaneTest.cpp: add a test case for PlanePointFinder::findPoints

README.md, Source/Controller/MoveVerticesTool.cpp, Source/Controller/MoveVerticesTool.h, Source/IO/DefParser.cpp, Source/IO/StreamTokenizer.h, Source/Model/Alias.cpp, Source/Model/Brush.cpp, Source/Model/Brush.h, Source/Model/BrushGeometry.cpp, Source/Model/Face.cpp, Source/Renderer/OffscreenRenderer.cpp, Source/Utility/Math.h
Hi, I was wondering if we could do a 1.1.6 release with these changes?
I've been testing it quite a bit for the past week and the vertex manipulation seems stable; I built several arches and round towers with no issues. The test case I reported here is fixed: https://github.com/kduske/TrenchBroom/issues/1033
by a combination of raising the CorrectEpsilon, changing intermediate values to double in Edge::Split, and modifying FindIntegerFacePoints::findPoints to try both rounding as well as the search algorithm.
FifthElephant also reported the crash when dragging is fixed for him.
If all looks OK, I have ready-to-release zip files in the same dropbox folder I made for the last release, here:
https://www.dropbox.com/sh/7dbfjsai75vwi5o/AAAeahOyydiDDQ8OcTpQjWhKa?dl=0
Thanks!
=> proposed 1.1.6 release (master branch)

app/resources/mac/TrenchBroom-Info.plist, cmake/TrenchBroomApp.cmake
so CFBundleExecutable, CFBundleName, CFBundleShortVersionString, CFBundleVersion take their values from CMake variables.
Now, the final Info.plists I get when I build with Xcode or with Ninja are the same, except the Xcode one adds some extra variables like DTCompiler, DTXcodeBuild, etc, which are probably not important.
The CMake variables I used are the same ones that CMake's default Info.plist template uses, described here: https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html
I updated the section of cmake/TrenchBroomApp.cmake that set MACOSX_BUNDLE_INFO_PLIST to also set the different variables used in the plist.
Questions: 
- I made CFBundleShortVersionString include the git hash and Debug/Release type, just like the version string in the About window. …
=> build: Adjust the Info.plist template 

patches/wxWidgets/osx_10_10_fix.patch
From http://trac.wxwidgets.org/ticket/16329#comment:3
=> Add a wxWidgets patch to fix compilation of 3.0.2 on OS X 10.10+.

common/src/MathUtils.h, common/src/Plane.h, test/src/PlaneTest.cpp
added a new normalEpsilon(), 0.000001 (same as tyrutils).
Improve test suite for setPlanePoints()
Note: there are 2 tests failing now:
```
[  PASSED  ] 491 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PolyhedronTest.subtractRhombusFromCuboid
[  FAILED  ] PolyhedronTest.mergeRemainingFragments
```
They fail because of the new behaviour of setPlanePoints() normalizing the `v1` and `v2` vectors, which is adding some more rounding error.
EDIT: Fixed now
=> setPlanePoints(): check for parallel or opposite vectors

common/src/IO/ImageLoaderImpl.cpp
Was getting a weird compile error for ImageLoaderImpl.cpp. Seems to be an include ordering thing, adding the wx/wx.h include at the top of the cpp file fixes it. The rest of the common lib built without errors.
```
1>------ Build started: Project: common, Configuration: Debug Win32 ------
1>  ImageLoaderImpl.cpp
1>C:\wxWidgets-3.0.2\include\wx/msw/init.h(36): error C2065: 'HINSTANCE' : undeclared identifier
1>C:\wxWidgets-3.0.2\include\wx/msw/init.h(36): error C2146: syntax error : missing ')' before identifier 'hInstance'
1>C:\wxWidgets-3.0.2\include\wx/msw/init.h(36): error C2365: 'wxEntryStart' : redefinition; previous definition was 'function'
1>C:\wxWidgets-3.0.2\include\wx/msw/init.h(36): error C2491: 'wxEntryStart' : definition of dllimport data not allowed …
```
=> Build fix for VS2010 Express

common/src/TrenchBroomApp.cpp, common/src/TrenchBroomStackWalker.cpp, common/src/TrenchBroomStackWalker.h
This fixes the crash reporting so that the "Crash" menu item now generates a correct stack trace:
```
c:\users\ericwa\desktop\trenchbroom\common\src\view\mapframe.cpp (975): TrenchBroom::View::debugSegfault
c:\users\ericwa\desktop\trenchbroom\common\src\view\mapframe.cpp (995): TrenchBroom::View::MapFrame::OnDebugCrash
c:\wxwidgets-3.1.0\src\common\appbase.cpp (658): wxAppConsoleBase::HandleEvent
c:\wxwidgets-3.1.0\src\common\appbase.cpp (670): wxAppConsoleBase::CallEventHandler
...
```
Previously, the stack trace written to the crash log was just showing the crash reporting function being called.
=> Fix stack traces for fatal exceptions/segfaults on windows

common/src/TrenchBroomApp.cpp
in case it triggers a crash itself
=> reportCrashAndExit: add a guard against re-entering this function

common/src/Model/ParaxialTexCoordSystem.cpp
The test for "when the texture plane normal is the Y axis, we must rotation clockwise" didn't match the code in TB1:
- https://github.com/kduske/TrenchBroom/blob/archive/tb1/master/Source/Model/Face.cpp#L334
- https://github.com/kduske/TrenchBroom/blob/archive/tb1/master/Source/Model/Face.cpp#L172
This updates that check to match the TB1 code, which fixes https://github.com/kduske/TrenchBroom/issues/1372
=> ParaxialTexCoordSystem::doTransform: fix a failing case for texture lock

test/src/Model/BrushTest.cpp
See: https://github.com/kduske/TrenchBroom/issues/1415#issuecomment-239914235
This case was crashing on 63a040d, but is no longer crashing.
It fails to snap though. I'm not sure whether this should successfully snap or not.
=> Grid 64 snap test

common/src/Renderer/BrushRenderer.cpp, common/src/Renderer/BrushRenderer.h, common/src/Renderer/MapRenderer.cpp
I was messing around with https://github.com/kduske/TrenchBroom/issues/1404 a bit, tried some micro-optimization and got `MapView3D::doRenderMap` about 33% faster when making a selection on a large map.
--
IMO there are two approaches to improving the selection performance:
1.  "proper" ones, involving trying to rendering only the changed parts of the map, using arguments of functions like`MapRenderer::selectionDidChange`. (or partitioning the brushes into subsets, and only re-rendering the subsets containing the brushes that changed selection state). As you were saying in https://github.com/kduske/TrenchBroom/issues/1404 , re-rendering only the exact set of changed brushes would interfere with OpenGL batching. It might be a performance win overall to forget about OpenGL batching.
2. …
=> optimizations for selection performance

Build.txt
- remove text suggesting you can install wxWidgets from a package, which won't work because of https://github.com/kduske/TrenchBroom/issues/1367
- remove wx* packages from the example `sudo apt-get install` command, since they need to be built and installed manually
=> Build.txt: fix broken instructions for Linux

common/src/Model/ParallelTexCoordSystem.cpp, test/src/Model/BrushFaceTest.cpp, test/src/TestUtils.cpp, test/src/TestUtils.h
- Fix for https://github.com/kduske/TrenchBroom/issues/1454 . I reverted https://github.com/kduske/TrenchBroom/commit/36e49c4 and now I just bail out at the beginning of `ParallelTexCoordSystem::doTransform` if `lockTexture` is false. Texture lock OFF and ON both seem to work now.
- Tests for texture lock. The `testTextureLock_Parallel` fails without the fix to `ParallelTexCoordSystem`.
- ~~There are no tests yet for the case when texture lock is off~~ There is a basic test of "texture lock off" now. It only tests the case when a face has reset texture alignment before being transfomed.
=> Valve 220 texture lock fix

common/src/Model/Brush.cpp, common/src/View/ClipTool.cpp, common/src/View/ClipToolController.cpp, common/src/View/VertexHandleManager.cpp
I updated all of the "cheap" assertions in:
- VertexHandleManager
- Brush
- ClipTool
- ClipToolController
to use `ensure()`. 
I won't do any more for now, unless you have any requests.
=> More assert() -> ensure() migration

common/src/Renderer/MapRenderer.cpp
(in `SelectedBrushRendererFilter::doProvideEdges`.)
This matches the condition for `SelectedBrushRendererFilter::doProvideFaces` and seems to fix https://github.com/kduske/TrenchBroom/issues/1459
=> Require brush visibility and editability before rendering an edge

appveyor.yml
This will build and run the TB test suite on https://www.appveyor.com/ .. It's a "free for open source" Windows continuous integration service.
I set it up on my github fork at https://github.com/ericwa/TrenchBroom .. here is what the build output looks like:  https://ci.appveyor.com/project/EricWasylishen/trenchbroom
I'm using it on my tyrutils fork as well; it's quite nice because every commit to every branch (that has the appveyor.yml file) gets automatically built and has the test suite run. Pull requests against your repo are also tested automatically and you can see whether all tests are passing before merging.
If you're interested, I can probably also set up travis-ci to do the same thing on OS X and Linux
=> Appveyor build script (windows CI service)

test/src/EL/ExpressionTest.cpp
=> Add missing `#include <cmath>` for std::fmod in ExpressionTest.cpp

test/src/RunAllTests.cpp
Running TrenchBroom-Test (wxgtk) without a running X server will now fail cleanly (before running any tests), instead of running the tests and then crashing inside wxEntryCleanup.
=> Check wxEntryStart return value in RunAllTests.cpp

common/src/IO/ImageLoaderImpl.cpp, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/CellView.h, common/src/View/FlyModeHelper.cpp, common/src/View/FlyModeHelper.h, common/src/View/KeyboardShortcutEntry.h, common/src/View/MapFrame.cpp, common/src/View/MapView3D.cpp, common/src/View/MapViewBase.cpp, common/src/View/PopupWindow.cpp, common/src/View/ToolBox.cpp, common/src/View/ToolBox.h, common/src/View/ToolBoxConnector.cpp, common/src/View/ToolBoxConnector.h, common/src/View/UVEditor.cpp, common/src/View/ViewConstants.cpp, common/src/View/ViewPreferencePane.cpp, common/src/View/ViewUtils.cpp, common/src/View/ViewUtils.h, common/src/View/WelcomeFrame.cpp, common/src/View/wxKeyStrings.cpp, common/src/View/wxKeyStrings.h, test/src/IO/DiskFileSystemTest.cpp, test/src/RunAllTests.cpp
I thought getting rid of `#include <wx/wx.h>` might improve compile times a bit but it didn't do much. Not sure if it's worth merging?
=> Minimize wxWidgets includes

common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceAttributes.cpp, common/src/Model/BrushFaceAttributes.h, common/src/Model/ChangeBrushFaceAttributesRequest.cpp, common/src/Model/ChangeBrushFaceAttributesRequest.h, common/src/View/MapDocument.cpp
@ericwa this should fix #1493. Could you have quick look around?
=> #1493: Add explicit command to reset the texture of a brush.

Build.txt, travis-macos.sh
Fixes build on latest macOS / Xcode.
I was getting the following error when building wxWidgets on macOS 10.12.1 / Xcode 8.1:
`../src/osx/cocoa/mediactrl.mm:76:10: fatal error: 'QTKit/QTKit.h' file not found`
QTKit has apparently been deprecated for a while and was finally removed.
=> Configure wxWidgets with --disable-mediactrl

common/src/BBox.h, common/src/MathUtils.cpp, common/src/MathUtils.h, common/src/Polyhedron_Misc.h, common/src/View/MapViewBase.cpp, test/src/TestUtils.cpp, test/src/TestUtils.h, test/src/View/MapDocumentTest.cpp
Don't snap selection bounding box center points to grid in MapViewBase::rotateObjects() or MapViewBase::doFlipObjects(), fixing https://github.com/kduske/TrenchBroom/issues/1495
Instead, round the bbox corners to integers before taking the bbox midpoint. This will give a bbox center vector whose components are either integers or offset from integers by 0.5
=> #1495: Objects sometimes translate when flipping

common/src/BBox.h, common/src/CollectionUtils.h, common/src/IO/CharArrayReader.cpp, common/src/IO/TextureReader.cpp, common/src/Model/CompilationProfile.cpp, common/src/Renderer/Camera.cpp, common/src/Renderer/FreeTypeFontFactory.cpp, common/src/TrenchBroomApp.cpp, common/src/View/CameraTool3D.cpp, common/src/View/CellView.h, common/src/View/EntityAttributeGrid.cpp, common/src/View/PersistentSplitterWindow2.cpp, common/src/View/PersistentSplitterWindow4.cpp, common/src/View/SplitterWindow2.cpp, common/src/View/SplitterWindow4.cpp, lib/include/stackwalker/StackWalker.h, lib/src/stackwalker/StackWalker.cpp
I think we'll want these whether or not we switch to C++11 now.
=> Fix some warnings found when testing C++11 compatibility

common/src/Assets/EntityModelManager.cpp, common/src/Assets/EntityModelManager.h
Fixes https://github.com/kduske/TrenchBroom/issues/1525
(both the crash when loading ad_quake.fgd in ad_magna.map, and the quoth flashlight example)
There is already a `View::safeGetModel()` function in ViewUtils but it takes a logger reference, which isn't desirable in this case:
`EntityModelManager::model()` already prints a warning to its logger if the model fails to load, so `EntityModelManager::renderer()` can just ignore and return NULL if `model()` throws an exception.
=> EntityModelManager::renderer: catch exceptions thrown by model()

common/src/View/EntityAttributeGridTable.cpp
Fixes https://github.com/kduske/TrenchBroom/issues/1527
I removed this comment:
> TODO: when deleting a property that has a default value in the property definition, re-add it to the list of default properties...
because that seems to be implemented already (?)
=> EntityAttributeGridTable: fix deleting rows with default values

common/src/Model/MapFacade.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/SmartSpawnflagsEditor.cpp, common/src/View/UpdateEntitySpawnflagCommand.cpp, common/src/View/UpdateEntitySpawnflagCommand.h
This seems to fix the test case I described in #1526 , including undo/redo, but I'm not sure if this is the best way to do it?
Also, there is some extra spam in the TB console now, when checking a spawnflag checkbox with 2 entities selected, I get 3 lines in the console:
```
11:56:43 PM: Debug: Command 'Set Spawnflag' undone
11:56:43 PM: Debug: Command 'Set Spawnflag' undone
11:56:43 PM: Debug: Command 'Set Spawnflags' undone
```
=> Implement #1526, Editing spawnflags on multiple entities at a per-flag granularity

common/src/Model/BrushSnapshot.cpp, test/src/Model/BrushTest.cpp
This is to avoid dangling pointers to Texture objects.
Also added a BrushTest.snapshotTextureTest to ensure this is being done.
Fixes https://github.com/kduske/TrenchBroom/issues/1520
=> BrushSnapshot::takeSnapshot: clear the Texture pointer in the snapshotted face

common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceSnapshot.cpp, common/src/Model/BrushFaceSnapshot.h, common/src/Model/ParallelTexCoordSystem.cpp, common/src/Model/ParallelTexCoordSystem.h, common/src/Model/ParaxialTexCoordSystem.cpp, common/src/Model/ParaxialTexCoordSystem.h, common/src/Model/TexCoordSystem.cpp, common/src/Model/TexCoordSystem.h, test/src/Model/BrushFaceTest.cpp, test/src/Model/TexCoordSystemTest.cpp
- Also, change TexCoordSystemSnapshot::restore() to take the TexCoordSystem* to restore the snapshot into.
Work in progress fix for https://github.com/kduske/TrenchBroom/issues/1511 .
Argh, and I already found a way to break this.. 
1. rotate the starting brush by 15 degrees about the Z axis
2. reset the face attributes
3. move the brush
4. undo
5. undo -> will fail at the `ensure(false, "couldn't find face");`
I'm surprised it's breaking in this way, because it means there is some floating-point error persisting when you move a brush, then undo the move.
=> BrushFaceSnapshot: save face boundary plane instead of BrushFace*

test/src/View/SnapshotTest.cpp
The CI scripts do RelWithDebInfo builds now, so the assert() will get eliminated since it's a release build
=> Fix an unused variable warning in SnapshotTest.setTexturesAfterRestore

common/src/View/MapViewBase.cpp
I missed a logical not when I changed the filtering of the context menu entries.
=> 1561: Context Menu Broken

common/src/View/GLAttribs.cpp
Broken in 5137411 when a `!m_initialized` condition on the for loop was removed
=> #1560: Fix antialiasing

common/src/Polyhedron_ConvexHull.h, test/src/PolyhedronTest.cpp
The problem here was the `polygonContainsPoint(position, std::begin(m_vertices), std::end(m_vertices), GetVertexPosition())` call, which uses the order of `m_vertices`.
AFAIK, `m_vertices`'s order comes from the order of calls to `Polyhedron::addPoint`, and is not meaningful.
=> #1556: Add and fix a failing Polyhedron test

common/src/View/MapView3D.cpp
=> #1464: Align paste position to grid when cursor is over the void.

common/src/Exceptions.h, common/src/TrenchBroomApp.cpp
This was slow and causing pauses in some cases:
https://github.com/kduske/TrenchBroom/issues/1557
https://github.com/kduske/TrenchBroom/issues/1562
Unlike the stack traces on `ensure()` failures or segfaults, I don't think we got any useful bug reports this way, because most exceptions are caught.
=> 1557: Don't capture stack trace in Exception constructor

common/src/Algorithms.h, common/src/Model/BrushFace.cpp, common/src/Polyhedron.h, common/src/Polyhedron_ConvexHull.h, common/src/VecMath.h, test/src/AlgorithmsTest.cpp, test/src/Model/BrushTest.cpp, test/src/PolyhedronTest.cpp
Issue: https://github.com/kduske/TrenchBroom/issues/1573
=> Fix point-in-polygon test and use a better test in polyhedron.

common/src/Model/BrushFaceReference.cpp, common/src/Model/BrushFaceReference.h, common/src/Model/BrushFaceSnapshot.h, common/src/View/SelectionCommand.cpp, common/src/View/SelectionCommand.h, test/src/View/SelectionCommandTest.cpp
This PR is a revision of https://github.com/kduske/TrenchBroom/pull/1547 and should supersede it.
=> Don't store BrushFace* pointers in SelectionCommand and BrushFaceSnapshot

app/resources/games/Quake/Quake.fgd, app/resources/games/Quake/Quoth2.fgd, app/resources/games/Quake2/Quake2.fgd, common/src/EL/Value.cpp, common/src/IO/ELParser.cpp, common/src/IO/ELParser.h, common/src/Model/EntityAttributesVariableStore.cpp, test/src/EL/ExpressionTest.cpp
Issue: https://github.com/kduske/TrenchBroom/issues/1534
This change required some minor changes to the EL:
- Allow null values to be type convertible to other types.
- Allow blank strings to be convertible to numbers.
Also required a change to the variable store for entity attributes, which now returns an empty string for missing variables.
=> Use logical and operator to check spawnflags in FGD files.

common/src/View/ToolController.cpp
Closes #1529. Also changes the behavior when switching from vertical to horizontal dragging: Now the dragged objects do not jump when alt is released.
=> #1529: Reset current and last drag points when resetting the initial point during a drag.

common/src/IO/Tokenizer.cpp, common/src/IO/Tokenizer.h, test/src/EL/InterpolatorTest.cpp
=> #1587: Don't use backslash as an escape character by default.

common/src/DoublyLinkedList.h, common/src/Polyhedron.h, common/src/Polyhedron_Misc.h, test/src/PolyhedronTest.cpp
Closes #1593. Move assignment is handled by existing assignment operator and overload resolution of move constructor when the RHS is an rvalue reference.
=> Add move constructor and move assignment to Polyhedron.

common/src/Assets/EntityDefinition.cpp, common/src/Assets/EntityDefinition.h, common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGridTable.cpp, common/src/View/EntityAttributeGridTable.h, common/src/View/SmartSpawnflagsEditor.cpp
Closes #1538. It turns out the problem was that the last selected row was not properly restored - now it is. So even though the entity grid will not default to the spawnflags, once you select them, they will always be reselected when you select different entities.
While I was at it, I also did the following:
- Show the default rows even if multiple entities with different definitions are selected.
- Show common spawnflag names even if multiple entities with different definitions are selected.
=> Properly restore selected row after changing entity selection

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Polyhedron.h, common/src/Polyhedron_ConvexHull.h, test/src/Model/BrushTest.cpp
- Made `Brush::canMoveFaces` const.
- In `Brush::doCanMoveVertices`, build `remaining` and `moving` polyhedrons by subtracting vertices, rather than adding. In case either of these ends up being a polyhedron, the order in which the vertices are added determines the polyhedron normal. `BrushTest.movePolygonRemainingPolygon2` tests for this.
- rework the `!allowVertexRemoval` case.
- I kept the `(result.vertexCount() < m_geometry->vertexCount())` check, although I'm not sure if it's desirable. Maybe `allowVertexRemoval` should only apply to the face/edge/verts being moved?
- Actually check that all of the moving verts were not deleted. Comparing the vertex counts is not good enough, because moving a face can cause other faces to merge and eliminate verts; …
=> Reworking Brush::doCanMoveVertices

common/src/TrenchBroomApp.cpp
=> 1605: Fix resources directory on builds run within VS

common/src/View/MapFrame.cpp, common/src/View/MapFrame.h
Only tested on windows so far, but I think this is the right fix for https://github.com/kduske/TrenchBroom/issues/1537
Strangely, the missing `virtual` on `~MapFrame` was not the actual problem, but I fixed it here anyway.
> The bug was that the DestroyChildren() call in ~MapFrame was causing MapFrame::OnChildFocus() to be called, but the MapFrame was in a partially invalid state (m_mapView pointer dangling since it was already destroyed by DestroyChildren), but IsBeingDeleted() was not returning true yet, so MapFrame still attempted to handle the OnChildFocus
=> #1537: Fix crash when map loading fails

common/src/IO/DefParser.cpp, common/src/IO/ELParser.cpp, common/src/IO/FgdParser.cpp, common/src/IO/LegacyModelDefinitionParser.cpp, common/src/IO/StandardMapParser.cpp, common/src/IO/Tokenizer.h, common/src/Model/EditorContext.cpp, common/src/Model/EditorContext.h, common/src/Model/Node.cpp, common/src/Model/Node.h, test/src/IO/TokenizerTest.cpp
Closes #1615. Be aware that this contains the fix for #1613, too.
=> Be more precise when checking whether a brush entity should be visible.

common/src/View/MapFrame.cpp, common/src/View/MapViewContainer.cpp, common/src/View/MultiMapView.cpp
Closes #1619. The problem occurs when the user tries to paste, but no map view is current, i.e., none has focus.
=> Ensure that a map view has focus before attempting to paste.

common/src/View/GLContextManager.cpp, common/src/View/MapFrame.cpp
- The recursive search through wxWindow children / dynamic cast to check for a RenderView is ugly of course. I think it should be safe though.. will a MapFrame always have a RenderView?
- Remove the temporary leak in ~GLContextManager() since it's no longer necessary
Fixes https://github.com/kduske/TrenchBroom/issues/1524
=> ~MapFrame(): Make m_contextManager->mainContext() current

common/src/Assets/EntityModelManager.cpp, common/src/Assets/TextureManager.cpp, common/src/View/CellLayout.h, common/src/View/CellView.h, common/src/View/MapFrame.cpp, common/src/View/ReplaceTextureDialog.cpp, common/src/View/TextureBrowserView.cpp
Closes #1646. Also fixed a couple of resource management problems and a missing listener removal when the texture browser is destroyed.
=> #1646: Set selected texture when the user clicks on a texture in the texture browser.

app/resources/games/Quake/Quake.fgd
See: https://github.com/id-Software/Quake/blob/master/qw-qc/items.qc#L1381
Confirmed that it now matches in-game with id1 progs and r_showbboxes 1.
Fixes https://github.com/kduske/TrenchBroom/issues/1649
=> #1649: Fix bounding boxes of item_artifact_* in Quake.fgd

common/src/View/CreateComplexBrushToolController3D.cpp
=> #1656: Don't start a face drag in brush tool if there is no face under the mouse.

common/src/FileLogger.cpp, common/src/FileLogger.h, common/src/IO/DiskIO.cpp, common/src/IO/DiskIO.h, common/src/IO/SystemPaths.cpp, common/src/IO/SystemPaths.h, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/ActionManager.cpp, common/src/View/CommandIds.h, common/src/View/Console.cpp, common/src/View/CrashDialog.cpp, common/src/View/CrashDialog.h
Closes #1653. Also touched up the crash dialog a bit.
=> #1653: Create a log file and add it to crash report.

common/src/View/EntityAttributeEditor.cpp, common/src/View/EntityAttributeEditor.h, common/src/View/EntityAttributeGrid.h, common/src/View/SmartAttributeEditorManager.cpp, common/src/View/SmartColorEditor.cpp
=> #1655: Properly set selected colors in smart color editor. Switch smart editors in idle event as opposed to in reaction to row selections.

common/src/View/SelectionTool.cpp, common/src/View/SelectionTool.h
=> #1678: Only select selectable siblings when double clicking on nodes.

common/src/IO/MapFileSerializer.cpp, common/src/IO/MapStreamSerializer.cpp, common/src/IO/NodeSerializer.cpp, common/src/IO/NodeSerializer.h, common/src/IO/StandardMapParser.cpp, common/src/IO/Tokenizer.cpp, common/src/IO/Tokenizer.h, common/src/Model/AttributeNameWithDoubleQuotationMarksIssueGenerator.cpp, common/src/Model/AttributeNameWithDoubleQuotationMarksIssueGenerator.h, common/src/Model/AttributeValueWithDoubleQuotationMarksIssueGenerator.cpp, common/src/Model/AttributeValueWithDoubleQuotationMarksIssueGenerator.h, common/src/Model/Game.h, common/src/Model/GameImpl.h, common/src/Model/Issue.cpp, common/src/Model/Issue.h, common/src/Model/LongAttributeNameIssueGenerator.cpp, common/src/Model/LongAttributeNameIssueGenerator.h, common/src/Model/LongAttributeValueIssueGenerator.cpp, common/src/Model/RemoveEntityAttributesQuickFix.cpp, common/src/Model/RemoveEntityAttributesQuickFix.h, common/src/Model/TransformEntityAttributesQuickFix.cpp, common/src/Model/TransformEntityAttributesQuickFix.h, common/src/StringUtils.cpp, common/src/StringUtils.h, common/src/View/MapDocument.cpp, test/src/IO/NodeWriterTest.cpp, test/src/IO/WorldReaderTest.cpp, test/src/StringUtilsTest.cpp
Closes #1654.
Double quotation marks are marked as issues. Two quick fixes are available: _Delete property_ and _Replace double with single quotation marks_. Furthermore, they are escaped with backslashes when writing a map, and are unescaped when reading again.
=> #1654: Handle entity properties containing double quotation marks

app/resources/documentation/manual/index.md, common/src/Model/EntityRotationPolicy.cpp, common/src/Model/EntityRotationPolicy.h
=> 1692: Properly handle 'mangle' (yaw pitch roll) entity property.

common/src/Model/Brush.cpp, test/src/Model/BrushTest.cpp
Fixes #1708.
I think after 2.0.0 is out `Brush::canMoveBoundary` could use some cleanup; it has a lot of duplicated logic from `Brush::rebuildGeometry`, and not duplicating that logic exactly was the cause of this bug. I think it would be better to clone the brush, move the face in the cloned brush, catch any GeometryException, and then check for faces being dropped/redundant.
=> #1708: Don't allow resizing brushes past world bounds

common/src/Model/EntitySnapshot.cpp, test/src/View/GroupNodesTest.cpp
Fixes #1715
Not sure if it's the correct fix.
=> #1715: EntitySnapshot: don't restore empty attribute names

common/src/View/MapFrame.cpp
This was causing TB to run out of window handles on Windows, which would crash the app.
I tested this briefly on Ubuntu 16.04 and didn't see any issues.
If it turns out that there is still a problem on Unity, we can either change it to:
```
#ifndef __LINUX__
oldMenuBar->Destroy();
#endif
```
or maybe we can just clear and repopulate the menu bar returned by `GetMenuBar()` rather than replacing it?
Fixes #1730
=> #1730: Remove hack meant for Unity which was leaking wxMenuBar objects

common/src/View/MapDocument.cpp, test/src/View/MapDocumentTest.cpp
=> #1735: Fix crash when Cmd+Alt clicking to set empty texture

common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
Note: if you try to add/remove a single brush of a brush entity to/from a group, it will add/remove the whole brush entity.
`collectEntitiesForBrushes` is the same as `MapDocument::collectGroupableNodes`, so I should probably delete `collectEntitiesForBrushes` and make `MapDocument::collectGroupableNodes` public and use that?
Fixes #1744
=> #1744: Make "Add/remove objects to/from group" commands preserve brush entities

common/src/View/MapViewBase.cpp
Specifically, it will move the selected brushes to the parent group of the last selected brush, or the parent layer of that brush if it's not in a group.
Fixes #1706
=> #1706: make "Move Brushes To World" keep brushes in their group.

common/src/IO/NodeSerializer.cpp, common/src/IO/StandardMapParser.cpp, common/src/StringUtils.cpp, common/src/StringUtils.h, test/src/IO/NodeWriterTest.cpp, test/src/IO/WorldReaderTest.cpp
This disables most of the escaping/unescaping in entities, except `"` is still escaped to `\"` when writing to .MAP, so you don't break a map file's parsing by typing in a `"` in TB (same as before.)
I think this will be better for mappers as it lets them see/edit exactly what is in the .MAP file.
Fixes #1739
=> #1739: don't escape/unescape entity keys/values, except escaping " to \"

common/src/Model/EntitySnapshot.cpp, test/src/View/GroupNodesTest.cpp
=> #1754: don't insert "origin" "" when rotating a grouped brush entity

common/src/Model/BrushContentTypeEvaluator.cpp
that was causing "hint" to match the pattern "clip".
Ideally, this would have been a compile-time error.
Alternatively, could call the helper StringUtils::caseInsensitiveMatchesPattern
Fixes #1781
=> TextureNameEvaluator: fix broken use of StringUtils::matchesPattern

common/src/Renderer/BrushRenderer.cpp, common/src/Renderer/BrushRenderer.h, common/src/Renderer/MapRenderer.cpp, common/src/Renderer/MapRenderer.h, common/src/Renderer/ObjectRenderer.cpp, common/src/Renderer/ObjectRenderer.h
=> 1385: Fix transparent brushes being wrongly occluded by locked groups

common/src/Model/ParallelTexCoordSystem.cpp, common/src/Vec.h, test/src/VecTest.cpp
Fixes #1774. What was happening in Pritchard's video: for one of the faces that was NOT being moved during vertex manipulation, the normal was still changing slightly so that the `if (oldNormal != newNormal)` test in `TexCoordSystem::updateNormal` considered them different. Then, `ParallelTexCoordSystem::doUpdateNormal` was not handling close-to-equal old and new normals properly.
Also fixed Vec::makePerpendicular() and added a test that the returned vector is perpendicular.
Note: I think the texture alignment during vertex manipulation for Valve is still not very good, but I can make a new issue.
=> 1774: fix non-moving faces losing texture alignment during vertex manipulation

common/src/IO/Path.cpp, common/src/IO/Path.h, common/src/Model/Game.cpp, common/src/Model/Game.h, common/src/Model/GameFactory.cpp, common/src/Model/GameFactory.h, common/src/Model/GameImpl.cpp, common/src/Model/GameImpl.h, common/src/Model/MapFacade.h, common/src/Model/MissingModIssueGenerator.cpp, common/src/Model/MissingModIssueGenerator.h, common/src/Model/ModelTypes.h, common/src/TrenchBroomApp.cpp, common/src/View/CompilationDialog.cpp, common/src/View/FaceAttribsEditor.cpp, common/src/View/IssueBrowserView.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/src/View/ViewEditor.cpp, common/src/View/ViewUtils.cpp, test/src/IO/WorldReaderTest.cpp, test/src/Model/TestGame.cpp, test/src/Model/TestGame.h, test/src/View/MapDocumentTest.cpp
Closes #1718 
- Don't crash when a mod is missing, print error to console instead.
- Add issues for each missing mod with quick fix to remove mod.
=> 1718: Let user reassign mod directory when TB cannot find it

common/src/View/CellLayout.h, common/src/View/CellView.h
Closes #1751 
Also fixes scrolling when using a trackpad at the cost of disabling row by row scrolling.
=> 1751: Texture Browser doesn't scroll correctly with empty groups

common/src/Model/Entity.cpp
Avoids normalizing "angles" when moving an entity.
Fixes #1839
=> 1839: Entity::doTransform: only apply rotation if there is some (non-identity matrix)

common/src/Renderer/Camera.cpp, test/src/Renderer/CameraTest.cpp
This is invalid, but previously the camera state would get polluted with NAN's.
Now it's handled by picking an arbitrary m_right that's perpendicular to the provided direction.
Fixes #1843
=> 1843: Camera::setDirection: handle `direction` and `up` being colinear

common/src/View/MapViewBase.cpp
Not snapping the center point gives undesirable behaviour when
part of the selection bbox is off-grid, and the selection contains
on-grid vertices (which will be moved off grid).
This reverts the fix for #1495
Fixes #1889 , at least the example I gave here: https://github.com/kduske/TrenchBroom/issues/1889#issuecomment-347049415
=> 1889: Restore grid snapping of flip center.

common/src/Model/EntityRotationPolicy.cpp
for point entities.
Fixes #1888
=> 1888: default to RotationType_AngleUpDown instead of RotationType_Angle

common/src/IO/FreeImageTextureReader.cpp
This makes makes my PNG textures appear consistently as their WAL versions in the editor.
=> Vertical flip textures loaded with FreeImage.

cmake/PrintDebianDependencies.sh.in, cmake/TrenchBroomApp.cmake, travis-linux.sh
Fixes #1900 (it should, anyway, I haven't actually tested the .deb).
The travis build log now includes the output of `dpkg --info`: https://travis-ci.org/kduske/TrenchBroom/jobs/310304258#L4339
The libpng package is no longer a dependency, as expected:
Depends: libc6 (>= 2.15), libcairo2 (>= 1.6.0), libfreeimage3, libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libgl1-mesa-glx | libgl1, libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.14.0), libsm6, libstdc++6 (>= 5), libx11-6, libxxf86vm1, zlib1g (>= 1:1.1.4)
=> 1900: Linux: configure wxwidgets with png/tiff/jpeg=builtin

common/src/Line.h, common/src/Model/Brush.cpp, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/ParallelTexCoordSystem.cpp, common/src/Model/ParallelTexCoordSystem.h, common/src/Model/ParaxialTexCoordSystem.cpp, common/src/Model/ParaxialTexCoordSystem.h, common/src/Model/TexCoordSystem.cpp, common/src/Model/TexCoordSystem.h, common/src/Plane.h, common/src/View/CopyTexCoordSystemFromFaceCommand.cpp, common/src/View/CopyTexCoordSystemFromFaceCommand.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/SetBrushFaceAttributesTool.cpp, test/src/LineTest.cpp, test/src/PlaneTest.cpp
Fixes #1898 and also fixes #1795 + fixes #1802 
There are 2 things I did here:
- Vertex manipulation (`BrushFace::updatePointsFromVertices`) and alt-click (`BrushFace::copyTexCoordSystemFromFace`) now update the texture offset. This fixes the misalignment observed in #1898 and #1795. This is done by picking an invariant point on the seam between the two planes (the old and new plane for vertex manipulation, and the source and destination face planes for alt-click), and then calculating the offset so the texture coordinates stay the same at that point.
- I split `ParallelTexCoordSystem::doUpdateNormal` into two functions. The existing code went into `doUpdateNormalWithRotation`, and the new function I added is `doUpdateNormalWithProjection`.
The "rotation" version looks like this when you …
=> 1898: Valve alt+click and vertex manipulation texture lock fixes

common/src/Assets/Palette.cpp, common/src/EL/Interpolator.cpp, common/src/Exceptions.h, common/src/IO/ConfigParserBase.cpp, common/src/IO/DiskIO.h, common/src/IO/ELParser.cpp, common/src/IO/ELParser.h, common/src/IO/GameEngineConfigParser.cpp, common/src/IO/ImageFileSystem.cpp, common/src/IO/MapFileSerializer.cpp, common/src/IO/MapStreamSerializer.cpp, common/src/IO/MappedFile.cpp, common/src/Model/GameFactory.cpp, common/src/RecoverableExceptions.cpp, common/src/RecoverableExceptions.h, common/src/StringUtils.h, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, test/src/Assets/EntityDefinitionTestUtils.cpp, test/src/EL/ExpressionTest.cpp, test/src/IO/CompilationConfigParserTest.cpp, test/src/IO/ELParserTest.cpp, test/src/IO/GameConfigParserTest.cpp
Closes #1905 
When the editor fails to parse a compilation profile or game engine profile, it will offer to delete the invalid file and try again.
=> 1905: Add option to delete invalid config files

common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h
Fixes #1945 
Quick hack using wxEVT_CHAR_HOOK to prevent autocompletion from stealing the tab key.
Is it safe to call Bind() multiple times with the same function pointer and target object, i.e. will wxWidgets ignore the calls after the first one?
=> 1945: EntityAttributeGrid: Hack to make tab key navigate between cells

common/src/View/FlyModeHelper.cpp, common/src/View/KeyboardShortcut.cpp, common/src/View/KeyboardShortcut.h
Closes #1943.
Using modifiers for fly keys is still a bit dodgy, but there really is no good way to fix this because we cannot query the entire keyboard state reliably.
=> 1943: Strange behaviour whith some Fly Mode key bindings

common/src/Model/BrushFace.cpp, common/src/Model/ParallelTexCoordSystem.cpp, common/src/Model/ParallelTexCoordSystem.h, common/src/Model/ParaxialTexCoordSystem.cpp, common/src/Model/ParaxialTexCoordSystem.h, common/src/Model/TexCoordSystem.cpp, common/src/Model/TexCoordSystem.h, test/src/Model/BrushFaceTest.cpp
Fixes #1946 
Note: the existing test suite would have detected #1946 , but some tests were spuriously passing due to missing `face->resetTexCoordSystemCache();` calls in the test code.
=> 1946: Use the real face normal in ParaxialTexCoordSystem::doTransform

common/src/View/CompilationProfileEditor.cpp, common/src/View/CompilationTaskList.cpp, common/src/View/KeyboardShortcut.cpp
=> 1963: Backspace and delete keys cause cursor position to move to beginning in Compile dialog text controls

common/src/View/MapFrame.cpp, common/src/View/MapFrame.h
Closes #1958. Note that this "fix" doesn't allow undoing text editing text ctrls on some platforms, as it depends on whether or not the wxTextCtrl undo facilities are implemented (which they are not on macOS).
=> 1958: "Undo" while editing key name corrupts another key

common/src/Model/EditorContext.cpp, common/src/Model/EditorContext.h, common/src/View/MapDocument.cpp, test/src/View/MapDocumentTest.cpp
=>  1999: clear editor context current group in MapDocument::clearDocument

common/src/View/VertexHandleManager.h, common/src/View/VertexTool.cpp, common/src/View/VertexTool.h, common/src/View/VertexToolBase.h, common/src/View/VertexToolController.cpp, common/src/View/VertexToolController.h, common/src/View/VertexToolControllerBase.h
=> 1982: Can't move shared faces together

common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h, common/src/View/EntityAttributeGridTable.cpp
even if the text value hasn't changed
Fixes #1976 
- Only tested on macOS
- This is a horrible hack - wxGrid wasn't designed for this use case
- The first thing I tried was making `EndEdit` return true unconditionally, this leads to an infinite loop!
- I would suggest not merging this until after 2.0.0
=> 1976: hack to make Return always apply changes to a grid cell

common/src/View/MapDocument.cpp, test/src/View/MapDocumentTest.cpp
Closes #2050.
We now move ungrouped objects to the current parent.
=> 2050: "Ungroup" on a nested group moves objects out of the current group

common/src/Disjunction.cpp, common/src/Disjunction.h, common/src/IO/StandardMapParser.cpp, common/src/Notifier.h, common/src/TemporarilySetAny.cpp, common/src/TemporarilySetAny.h, common/src/TrenchBroomApp.cpp, common/src/View/Autosaver.cpp, common/src/View/CameraLinkHelper.cpp, common/src/View/ClipTool.cpp, common/src/View/CommandProcessor.cpp, common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGridTable.cpp, common/src/View/FlyModeHelper.cpp, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/ModEditor.cpp, common/src/View/SmartSpawnflagsEditor.cpp, common/src/View/ToolBox.cpp, common/src/View/VertexCommand.cpp, common/src/View/VertexHandleManager.cpp, common/src/View/VertexHandleManager.h, common/src/View/VertexTool.cpp, common/src/View/VertexToolBase.h, common/src/View/VertexToolController.cpp
Closes #2038.
The problem was caused when there was another face handle being picked. The vertex tool only switched to split mode when there was only one "face split" or "edge split" handle was picked, but this was too strict - often there is another face handle being picked (e.g. on the back of the brush), but we're okay by taking only the first one.
=> 2038: Vertex tool: Shift+Alt+Drag on a face is unreliable, often does nothing

common/src/View/MapDocument.cpp
=> 2016: Isolating and then hiding a group will not hide it's content.

common/src/Preferences.cpp, common/src/Preferences.h, common/src/Renderer/BrushRenderer.cpp, common/src/Renderer/EntityRenderer.cpp, common/src/Renderer/GroupRenderer.cpp, common/src/Renderer/GroupRenderer.h, common/src/Renderer/MapRenderer.cpp, common/src/Renderer/ObjectRenderer.cpp, common/src/Renderer/ObjectRenderer.h
Closes #2052. @ericwa This PR renders group bounds and names only for top level groups (if no group is open) or the children of the current group. This already reduces visual clutter a lot. We could also try to not render the bounds at all - I'm not sure they are very helpful.
=> 2052: Group bounds are not drawn when navigating out of a nested group

common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h
=> 2094: preserve grid cursor when renaming a key (even if it reorders the grid)

common/src/Model/Entity.cpp, common/src/Model/Entity.h, common/src/Model/Node.cpp, common/src/Model/Node.h, common/src/View/MapDocument.cpp, common/src/View/MapDocumentCommandFacade.cpp, test/src/View/MapDocumentTest.cpp
Fixes #2107 
This changes the meaning of MapDocument::select when given a brush Entity, to select the contained brushes instead of the entity itself.
=> 2107: Fix selection when ungrouping.

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Polyhedron.h, common/src/Polyhedron_Subtract.h, common/src/View/ActionManager.cpp, common/src/View/CommandIds.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, test/src/Model/BrushTest.cpp, test/src/PolyhedronTest.cpp
I implemented the "shrink, then subtract" behaviour as @Knetic requested. It's consistent with GtkRadiant and QuArK.  I also tried "grow, then subtract" and it's messy when hollowing multiple brushes.
Also in this commit, I fixed Polyhedron::subtract to return the minuend when the minuend are subtrahend are disjoint. It's not strictly needed here but the old behaviour was breaking some of my experiments with growing and subtracting multiple brushes.
=> 2069: CSG hollow

app/resources/shader/Grid.fragsh, common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/MapFacade.h, common/src/Renderer/RenderContext.cpp, common/src/Renderer/RenderContext.h, common/src/View/ActionManager.cpp, common/src/View/CommandIds.h, common/src/View/Grid.cpp, common/src/View/Grid.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/src/View/SnapBrushVerticesCommand.cpp, common/src/View/SnapBrushVerticesCommand.h, test/src/View/GridTest.cpp
Fixes #1723 
Things I tested:
- snapping a totally off-grid brush to 0.125, this worked
- menu and toolbar, increase/decrease grid size shortcuts
I'm not totally sure about the change in `Grid::moveDelta` or the cast I added to `snap()`.
The tests should probably be expanded a bit as well before merging
=> 1723: Support grid 0.5, 0.25, 0.125

common/src/View/MapFrame.cpp
=> 1885: Better fix for logger crash when closing document with a pointfile open.

common/src/View/MapViewBase.cpp
instead of selecting all worldspawn brushes.
Fixes #2128
=> 2128: Make "Move brushes to world" only select the moved brushes,

common/src/DoublyLinkedList.h, common/src/Polyhedron_Subtract.h, test/src/DoublyLinkedListTest.cpp
Closes #2132 
This PR adds tests for most of `DoublyLinkedList`'s public modifications. It also fixes the problem of the list elements not getting deleted when the list is cleared.
=> 2132: Crash when manipulating large groups

common/src/Model/GameImpl.cpp
highest to lowest:
mod pakfiles
mod loose files
id1 pakfiles
id1 loose files
Fixes #2152
=> 2152: fix search path order to match Quake:

common/src/IO/Bsp29Parser.cpp
=> 2153: Bsp29Parser: skip textures with negative textureOffset

common/src/View/EntityAttributeGrid.cpp
=> 2167: reorder AutoComplete() and Bind(wxEVT_CHAR_HOOK) calls

common/src/View/CommandProcessor.cpp, common/src/View/MoveToolController.h, common/src/View/VertexTool.cpp, common/src/View/VertexToolBase.h, common/src/View/VertexToolControllerBase.h
Closes #2164.
@ericwa The actual fix was very simple and is in the first commit. It has the potential to upset other functionality / tools, but I have found no problems in my testing so far. Please have a look as well, esp. when cancelling stuff (esc) in other tools. The other commit is just cleanup.
=> 2164: Vertex tool: cancelling a drag with "Escape" leaves detached handles

app/resources/shader/Face.fragsh, app/resources/shader/Grid.fragsh, app/resources/shader/Grid2D.fragsh, common/src/Renderer/FaceRenderer.cpp, common/src/Renderer/GridRenderer.cpp
I got rid of blendFactor and instead use dFdx/dFdy to find out how much the world position is changing between the current fragment and its neighbours, and compare the requested grid size to that - I think this is the proper way to do this kind of thing (mipmap selection works this way internally), and there's no need to look at the angle or viewport height.
Not 100% sure about the results (the 2D view is "busier" now.)
2.0.3:
This PR ( f149872 ):
test map I was using: 
[gridtest.map.txt](https://github.com/kduske/TrenchBroom/files/2216658/gridtest.map.txt)
Closes #2119
=> 2119: Moiré effect with small grid size

.travis.yml, travis-macos.sh
This PR uses Xcode to build the macOS app bundle.
Closes #2146
=> 2146: Quake/Rubicon2.def not bundled in macOS build

app/resources/shader/EntityLinkArrow.fragsh, app/resources/shader/EntityLinkArrow.vertsh, common/src/Renderer/EntityLinkRenderer.cpp, common/src/Renderer/EntityLinkRenderer.h, common/src/Renderer/Shaders.cpp, common/src/Renderer/Shaders.h
Not sure if the arrow placement rules need adjustment, but this seems like a decent start.
The vertex shader keeps the arrows facing the camera, like the entity angle arrows.
Fixes #1540
=> 1540: Draw arrowheads on entity links to indicate direction

app/resources/shader/EntityModel.fragsh, app/resources/shader/Face.fragsh, common/src/Assets/Palette.h, common/src/Assets/Texture.cpp, common/src/Assets/Texture.h, common/src/IO/FreeImageTextureReader.cpp, common/src/IO/IdWalTextureReader.cpp, common/src/IO/Md2Parser.cpp, common/src/IO/MdlParser.cpp, common/src/IO/MdlParser.h, common/src/IO/MipTextureReader.cpp, common/src/Renderer/GL.h
Screenshot with brushes textured with a "{"-prefix fence texture, as well as a .mdl (the palm tree) with the MF_HOLEY flag.
Fixes #1412
Note: the old quake tools that generate mipmaps (Wally, etc.) for the "{" textures aren't aware of this feature so the mipmaps tend to be nonsense, like this:
All engines that support this feature generate their own mipmaps, ignoring what's in the wad.
I think it's probably fine at least for a first pass of the feature. We could also do postprocessing on the textures to replace the pink color of transparent areas with a color averaged from neighbouring solid pixels (again, Fitzquake / QuakeSpasm do this), but it's IMO not critical.
=> 1412: support fence textures with "{" prefix and MF_HOLEY .mdl flag for alpha-masked skins

app/resources/games/Hexen2/Hexen2.fgd
=> 2234: Incorrect spawnflags entry for Hexen 2 mission pack support.

common/src/Notifier.h, common/src/View/ActionManager.cpp, common/src/View/CommandIds.h, common/src/View/CommandProcessor.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, test/src/View/MapDocumentTest.cpp
There are 2 changes here:
- Fixes the exception-safety problem in `CommandProcessor::doCommand` and `CommandProcessor::undoCommand` where commandDoNotifier would disable window updates, and then if an exception was thrown, the window updates would never be re-enabled.
- No longer catch exceptions in those methods. This should be safe, because if an exception was ever caught there in the past it would have caused the window updates freezing bug, which was relatively rare. Now we'll get a crash dialog instead.
Aside from that it also adds a menu item to the Debug menu that throws a GeometryException, for testing this manually.
Fixes #2237
=> 2237: Fix window updates freezing when an exception is thrown

app/resources/mac/TrenchBroom-Info.plist
Note: This has to be hardcoded, as far as I can tell.
According to this cmake only substitutes a small list of variables into the plist:
https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html
Confirmed it works by setting it to 10.14.0:
Fixes #2120
=> 2120: provide LSMinimumSystemVersion value in plist

common/src/IO/ImageFileSystem.cpp, common/src/IO/WadFileSystem.cpp
=> 2256: Don't crash when loading invalid texture collections.

common/src/Assets/TextureCollection.cpp, common/src/Assets/TextureCollection.h, common/src/IO/Bsp29Parser.cpp, common/src/IO/Bsp29Parser.h
=> 2254: Don't crash when BSP textures are missing.

common/src/Model/Entity.cpp, common/src/Model/Entity.h, test/src/Model/EntityTest.cpp
This bug confused me because it wasn't happening in my tests, until I realized that I needed to add the Entity to a World + Layer to reproduce it (when it's attached to a World/Layer, Entity::nodeBoundsDidChange() ends up calling Entity::origin()).
fixes #2293
=> 2293: fix Entity::origin() caching issue

cmake/TrenchBroomTest.cmake
=> 2303: fix link error on clang-6.0 and Ubuntu 17.10

common/src/View/MapDocument.cpp, test/src/Model/BrushTest.cpp
Closes #2290.
By always removing minuend and relying that Polyhedron::subtract() returns minuend untouched when it and subtrahend are disjoint.
=> 2290: Subtracting a brush that encloses the subtrahend has no effect.

common/src/View/FileTextureCollectionEditor.cpp, common/src/View/FileTextureCollectionEditor.h
Re-validate in the OnClick handlers.
Fixes #2326
=> 2326: Don't trust the texture collection add/remove/up/down to be disabled

common/src/View/ScaleObjectsTool.cpp, common/src/View/ScaleObjectsTool.h, common/src/View/ScaleObjectsToolPage.cpp, common/src/View/ScaleObjectsToolPage.h, travis-linux.sh
When the tool is activated, it fills in the text box with the current selection bounds size (for reference). The "to size" mode is the default.
Fixes #2336
=> 2336: Add a way to enter the desired bounds to scale to

common/src/Assets/EntityModel.cpp, common/src/Assets/EntityModelManager.cpp, common/src/IO/Bsp29Parser.cpp
Closes #2363.
The methods return default values when invalid indices are used. Printing a specific warning for this is difficult, but it will print an error message, and only once.
=> 2263: Ensure fails loading quoth mdl + builtin FGD

common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
=> 2368: Don't consider invalid merge targets.

common/src/View/MapDocument.cpp, test/src/View/MapDocumentTest.cpp, test/src/scalar_test.cpp, vecmath/include/vecmath/bbox.h, vecmath/include/vecmath/intersection.h, vecmath/include/vecmath/plane.h, vecmath/include/vecmath/scalar.h, vecmath/include/vecmath/vec.h
=> 2384: Brushes created by CSG merging faces should go in the parent of the first selected brush

travis-linux.sh
in use from a previous command. fixes #2417
=> 2417: launch xvfb-run with -a so it uses another X server ID if 99 is

common/src/IO/CharArrayReader.cpp, common/src/IO/CharArrayReader.h, common/src/IO/MipTextureReader.cpp, common/src/IO/TextureReader.cpp, common/src/IO/TextureReader.h, test/src/IO/CharArrayReaderTest.cpp, travis-linux.sh
Also adjusted CharArrayReader and MipTextureReader::doReadTexture so it'll throw exceptions if asked to do an invalid seek/read, instead of reading out of bounds / crashing.
The wad posted in #2399 seems to actually be valid so these changes are untested with actual corrupt wads.
Fixes #2399
=> 2399: fix mip size calculation in TextureReader

test/src/vec_test.cpp, vecmath/include/vecmath/vec.h
=> 2398: fix for vec3f::NaN == any vec3f returning true

common/src/Renderer/Camera.cpp, common/src/Renderer/Camera.h, test/src/Renderer/CameraTest.cpp, test/src/vec_test.cpp, vecmath/include/vecmath/vec.h
I don't know how muk actually triggered #2397 but I refactored the pitch limiting code that prevents you from looking past +Z or -Z.
There were some corner cases where the old code would produce NaN's. e.g. if m_up was somehow (0, 0, -1), it would produce NaN when yawing (CameraTest.testOrbitWhileInverted). Also this line
`const auto axis = normalize(cross(m_direction, newDirection));` would give NaN if 
m_direction and newDirection were exactly 180 degrees apart, I think.
=> 2397: rewrite Camera pitch limit

common/src/Preference.h, common/src/PreferenceManager.h, common/src/View/FlyModeHelper.cpp, common/src/View/FlyModeHelper.h
In the short amount of testing I did, this fixes the weirdness with RC2 (the error dialogs, failure to read preferences sometimes, weird nesting in registry,etc.)
Fixes #2438
=> 2438: avoid accessing preferences from FlyModeHelper thread

common/src/View/SplitterWindow2.cpp, common/src/View/SplitterWindow4.cpp
Closes #2357.
Also used this opportunity to make the hit zone for the 4 pane sash a little larger to make dragging it easier.
=> 2357: Can drag map view pane splitters outside of the window

Build.md, cmake/TrenchBroomApp.cmake
I ran in to some snags setting up a new Windows 10 / VS2017 machine to compile TB and have a few minor fixes:
- Update the list of components you need to choose in the VS installer
- Clarify that you must specify CMAKE_BUILD_TYPE on the command line (I neglected this and got a weird linker error where the code was compiled against the debug CRT but not linked to it).
- Also set up the TrenchBroom target to copy in the wxWidgets DLL's so you don't need to modify PATH
- Specify the wxWidgets path on the cmake command line, rather than using WXWIN environment variable
fixes #2465
=> 2465: Update Windows build instructions and remove need to edit PATH

common/src/Model/CollectTouchingNodesVisitor.h, common/src/View/MapDocumentCommandFacade.cpp, test/src/View/MapDocumentTest.cpp
The crash was happening because:
- if two or more of the inputs to CollectTouchingNodesVisitor were overlapping, they'd be included in the output
- `MapDocument::selectTouching` would then delete the overlapping "query" brushes, and then try to select them which succeeded but crashed later on
Fixes #2476
=> 2476: fix crash when select touching is used on overlapping query brushes

app/resources/documentation/manual/index.md, common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/View/MapDocument.cpp, common/src/View/MapFrame.cpp, test/src/View/MapDocumentTest.cpp
This implements the idea from #2288 where the CSG subtract command uses all of the selected brushes as the subtrahend, and gets the minuend by running selectTouching() on the subtrahend.
It's a bit of UI change for how CSG subtract works, but it's more flexible and hopefully more intuitive (I could never remember the order, "first - second" or "second - first"  for the old CSG subtract).
Fixes #2288
=> 2288: allow multiple subtrahends for CSG subtract; subtract against "select touching"

common/src/IO/DiskFileSystem.cpp, common/src/IO/DiskFileSystem.h, common/src/Model/GameFactory.cpp
Adds new subclass of WritableDiskFileSystem that overrides createFile to first write to a temporary file next to the original file and then afterward move it. Changes GameFactory to use this class for all writing of game config files.
=> Use temporaries when writing game config files.

vecmath/include/vecmath/constants.h, vecmath/include/vecmath/scalar.h
=> 2507: Use constexpr for constants and scalar math functions.

common/src/IO/StandardMapParser.cpp, common/src/Model/Brush.cpp, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceSnapshot.cpp, common/src/Model/BrushFaceSnapshot.h, common/src/Model/ModelFactoryImpl.cpp, common/src/Model/ParallelTexCoordSystem.cpp, common/src/Model/ParallelTexCoordSystem.h, common/src/Model/ParaxialTexCoordSystem.cpp, common/src/Model/ParaxialTexCoordSystem.h, common/src/Model/TexCoordSystem.cpp, common/src/Model/TexCoordSystem.h, common/src/View/CopyTexCoordSystemFromFaceCommand.cpp, common/src/View/CopyTexCoordSystemFromFaceCommand.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/SetBrushFaceAttributesTool.cpp, test/src/Model/BrushFaceTest.cpp, test/src/Model/BrushTest.cpp, test/src/Model/TexCoordSystemTest.cpp, test/src/View/MapDocumentTest.cpp
Closes #2491.
The cause of the crash was that the map parser was using a different method to check for validity of face points as the `BrushFace` constructor. The simple fix was to use the same check.
While debugging, I also noticed that the `BrushFace` was not exception safe: When it throws, it leaves behind the `TexCoordSystem` instance that is passed in. The easiest way to make it exception safe was to use smart pointers; and while I was at it, I changed `TexCoordSystemSnapshot` to use smart pointers, too.
=> 2491: Don't crash on brushes with colinear face points.

common/src/View/ClipTool.cpp, common/src/View/ClipToolController.cpp, common/src/View/ClipToolController.h
=> 2478: Use snapped clip point when computing clipping help vectors. Allow for some imprecision.

.gitignore, common/src/IO/FileSystem.cpp, common/src/View/Autosaver.cpp, common/src/View/Autosaver.h, common/src/View/MapFrame.cpp, test/src/IO/DiskFileSystemTest.cpp
Closes #2539.
The problem was caused by a recent change to the file system abstractions. Previously, making a path absolute would always succeed, and now it was failing unless the path already existed in the hierarchy. This PR restores the previous behaviour for the case that the path does not exist in the file system.
=> 2539: Autosave Aborted Spams Console

common/src/Assets/Texture.cpp
This was changed in the v2019.1 to v2019.2 diff, looks like a typo?
Fixes #2560
=> 2560: fix GL_TEXTURE_MAG_FILTER not being set

common/src/View/RenderView.cpp
Fixes #2562
This might be kind of hacky, but it works for me. I don't know if there is a better place to make RMB down call SetFocus, but it seems like we need to do it ourselves. In 2.1.0 it was done here:
```
void ToolBoxConnector::OnMouseButton(wxMouseEvent& event) {
if (m_window->IsBeingDeleted()) return;
ensure(m_toolBox != nullptr, "toolBox is null");
event.Skip();
const MouseButtonState button = mouseButton(event);
if (m_toolBox->ignoreNextClick() && button == MouseButtons::MBLeft) {
if (event.ButtonUp())
m_toolBox->clearIgnoreNextClick();
return;
}
m_window->SetFocus();
```
=> 2562: set focus in RenderView::OnMouse when starting mouse capture.

common/src/IO/MapReader.cpp, common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceAttributes.cpp, common/src/Model/BrushFaceAttributes.h, common/src/Model/InvalidTextureScaleIssueGenerator.cpp, common/src/Model/InvalidTextureScaleIssueGenerator.h, common/src/Model/Issue.cpp, common/src/Model/Issue.h, common/src/Model/Node.cpp, common/src/View/IssueBrowserView.cpp, common/src/View/MapDocument.cpp, common/src/View/UVRotateTool.cpp, common/src/View/UVScaleTool.cpp, common/src/View/UVShearTool.cpp
Closes #2552 
- UV rotate, scale, and shear handles will disappear if an invalid scale value is detected
- an issue will be generated in the issue browser if a face with an invalid scale value is detected
=> 2552: Prevent a scale of 0 when scaling textures. Don't allow scaling, rotation, shearing when one scale factor is 0.

common/src/Assets/Quake3Shader.cpp
=> 2568: Fix typo in Q3 shader blend func parameters.

app/resources/games/Quake3/GameConfig.cfg, common/src/IO/GameConfigParser.cpp, common/src/Model/BrushContentTypeBuilder.h, common/src/Model/BrushContentTypeEvaluator.cpp, common/src/Model/BrushContentTypeEvaluator.h
Closes #2559.
This is a cheap workaround for the problem. What we really need is per face content types or something along those lines. For now, this restores the original behavior while allowing us to have content types on brushes where some faces can be ignored.
=> 2559: Brush content types requires all faces to match, add option for ignoring some textures.

common/src/Model/BrushContentTypeEvaluator.cpp
=> 2584: Only match content type if at least one face matches (and all others are ignored)

common/src/IO/BrushFaceReader.cpp, common/src/IO/BrushFaceReader.h, common/src/IO/MapReader.cpp, common/src/IO/MapReader.h, common/src/IO/NodeReader.cpp, common/src/IO/NodeReader.h, common/src/IO/NodeSerializer.cpp, common/src/IO/NodeSerializer.h, common/src/IO/NodeWriter.cpp, common/src/IO/NodeWriter.h, common/src/IO/WorldReader.cpp, common/src/IO/WorldReader.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/Game.cpp, common/src/Model/Game.h, common/src/Model/GameImpl.cpp, common/src/Model/GameImpl.h, common/src/Model/MissingModIssueGenerator.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, test/src/AABBTreeStressTest.cpp, test/src/IO/NodeWriterTest.cpp, test/src/IO/WorldReaderTest.cpp, test/src/Model/BrushFaceTest.cpp, test/src/Model/BrushTest.cpp, test/src/Model/GameTest.cpp, test/src/Model/TestGame.cpp, test/src/Model/TestGame.h
Closes #2592 
This is purely cleanup and memory safety improvement. I replaced all of the raw pointers to objects owned by `MapDocument` with `std::unique_ptr` for better safety. This incurred some changes to other classes which would create these objects. I also replaced some raw pointers with references where necessary.
=> 2592: Replace all raw pointers in MapDocument with smart pointers

common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
- reselect the reparented nodes after the removal from group
- remove a pointless Model::PushSelection from MapViewBase::reparentNodes
(all of the callers are managing reselection)
Fixes #2600
=> 2600: close any open groups in MapViewBase::OnRemoveObjectsFromGroup

common/src/View/MoveBrushEdgesCommand.cpp, common/src/View/MoveBrushFacesCommand.cpp, common/src/View/MoveBrushVerticesCommand.cpp, common/src/View/VertexCommand.cpp, common/src/View/VertexCommand.h
=> 2598: Don't collate vertex commands that affect different brushes.

common/src/Assets/AttributeDefinition.cpp, common/src/Assets/AttributeDefinition.h, common/src/View/EntityAttributeEditor.cpp, common/src/View/EntityAttributeEditor.h, common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGridTable.cpp, common/src/View/SmartAttributeEditorManager.cpp, common/src/View/SmartAttributeEditorManager.h, common/src/View/SmartDefaultAttributeEditor.cpp, common/src/View/SmartDefaultAttributeEditor.h
- The smart editor panel is changed to a splitter, with docs on top and the smart editor on the bottom.
- The docs/smart editors automatically collapse if there is no documentation or smart editor.
- I've added a `AttributeDefinition::optionDescriptions()` method that summarizes the options and their descripions for Choice and Flags attributes. This is to bring the rendering of FGD docs closer to how DEF's are set up - DEF's will just document everything in the class description, including spawnflag values and the possible values for each key, so you can see it all at a glance. FGD's were harder to see all of the available documentation at a glance
Example from ad_1_7p1_tb.fgd: (The "Options:" section is not part of the longDescription() but is generated by …
=> 2056: revamp FGD/DEF documentation rendering

common/src/View/MapFrame.cpp
=> 2619: Restore ability to convex merge selected faces when a vertex tool is active

common/src/View/MapDocumentCommandFacade.cpp, test/src/View/MapDocumentTest.cpp
=> 2626: Don't crash when invalid scale factors are used on a Group

common/src/View/EntityAttributeEditor.cpp
Adjust min sizes to fix issue where the smart editor is collapsed when it shouldn't be, when the window size is small. Also persist documentation/smart editor splitter position.
Fixes #2631
=> 2631: fix collapsed smart editor when window size is small

app/resources/games/Quake3/GameConfig.cfg, common/src/IO/GameConfigParser.cpp, common/src/IO/Quake3ShaderFileSystem.cpp, common/src/IO/Quake3ShaderFileSystem.h, common/src/Model/GameConfig.cpp, common/src/Model/GameConfig.h, common/src/Model/GameFileSystem.cpp, test/src/IO/GameConfigParserTest.cpp, test/src/IO/Md3ParserTest.cpp, test/src/IO/Quake3ShaderFileSystemTest.cpp, test/src/Model/TestGame.cpp
=> 2635: Add support for alternate shader search paths in shader file system

common/src/View/InputEvent.cpp, common/src/View/InputEvent.h, common/src/View/ToolBoxConnector.cpp
Closes #2672
(Edit, fixed the issue number)
=> 2672: Don't swallow accidental drags; convert them into clicks instead.

common/src/Model/GameImpl.cpp, common/src/View/EntityDefinitionFileChooser.cpp
Also return true for ".ent" in GameImpl::doIsEntityDefinitionFile,
otherwise selecting an .ent file in the file browser does nothing.
Fixes #2681
=> 2681: Allow choosing .ent in EntityDefinitionFileChooser::OnChooseExternalClicked

common/src/Assets/Texture.cpp, common/src/Assets/Texture.h, common/src/Preferences.cpp, common/src/Preferences.h, common/src/Renderer/TextureFont.cpp, common/src/Renderer/TextureFont.h, common/src/View/CellLayout.h, common/src/View/TextureBrowserView.cpp, common/src/View/TextureBrowserView.h
=> 2688: Show texture collection name in light gray in a second line in texture browser.

common/src/Renderer/PointHandleRenderer.cpp, common/src/Renderer/PointHandleRenderer.h
Fixes #1568
I just copied what the text renderer was doing (near = 0, far = 1, and multiply the Z coord of the handle  by -1 after projecting the position by the perspective camera).
You can see the lines clipping through the handles now. Maybe an idea could be translating the disc towards the camera by the handle radius?
=> 1568: Render occluded handles shaded

common/src/View/MapDocument.cpp, common/src/View/MapDocument.h
loadPointFile() needs to copy the passed in Path argument because
reloadPointFile() passes in m_pointFilePath, but loadPointFile() also
clears/sets m_pointFilePath and needs this to not clobber the passed-in
path.
Fixes #2698
=> 2698: fix broken Reload Point File and Reload Portal File commands

common/src/AABBTree.h, common/src/FileLogger.cpp, common/src/Model/ComputeNodeBoundsVisitor.h, common/src/Model/Entity.cpp, common/src/Model/Entity.h, common/src/Model/EntityRotationPolicy.cpp, common/src/Model/World.cpp, common/src/Renderer/EntityRenderer.cpp, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/CreateEntityTool.cpp, common/src/View/MapDocument.cpp, test/src/RunAllTests.cpp, test/src/bbox_test.cpp, vecmath/include/vecmath/bbox.h
Closes #2705 
The problem arises from the fact that we now have different bounds in use for entities. There are the definition bounds, which are taken from the entity definition and translated to the entity's origin, there are the model bounds, which are the actual bounds of the entity model, translated to the entity's origin and rotated according to the entity's rotation, and there are the total bounds which are used for picking. For a point entity, the total bounds are the union of the definition and model bounds, and for a brush entity, the total bounds are just the union of the brush bounds. We have to use the total bounds for the AABB tree because we want to allow model picking.
In this PR I tried to make sure that we use the correct bounds everywhere, and that the cached bounds are …
=> 2705: Crash when deleting a duplicated entity with an angle value that's not in the same position as the original

common/src/View/EntityAttributeEditor.cpp
Closes #2675.
Decided not to sort the flag options in the model itself, but only when they are displayed.
=> 2675: Sort flag descriptions by their values when displaying them in the entity inspector.

common/src/View/CellView.h
except:
- ones that don't access m_layout
- ones that are part of the validation code
Not the most elegant fix, but it works for now.
Fixes #2726
=> 2726: CellView: Call validate() in the beginning of every method,

common/src/IO/FreeImageTextureReader.cpp, common/src/IO/MipTextureReader.cpp, common/src/IO/MipTextureReader.h, common/src/IO/TextureCollectionLoader.cpp, common/src/IO/WadFileSystem.cpp, common/src/IO/WadFileSystem.h, test/src/IO/IdMipTextureReaderTest.cpp, test/src/IO/WadFileSystemTest.cpp
Closes #2735.
This PR will now use the file name to determine the mip texture name as opposed to the name stored in the mip itself. This is inline with QBSP's behavior AFAIK.
Additionally, this PR ensures that wad file entries with empty file names are skipped and logged.
=>  2735: Determine mip texture name from file name, not the name stored in the mip.

common/src/IO/ObjSerializer.cpp, common/src/IO/ObjSerializer.h, common/src/Model/GameImpl.cpp
This generates a trivial .mtl file so that texture names are preserved in the .obj export, making the exported UV's more useful. These show up as materials when imported into Blender or UE4.
There's no export of the textures as .png/.tga, so the materials are initially blank when imported into Blender/UE4, so that could be a future enhancement. Not sure if it's useful though.
Fixes #1603
=> 1603: Generate a simple .mtl file for .obj export

common/src/IO/Bsp29Parser.cpp, common/src/IO/MipTextureReader.cpp, common/src/IO/MipTextureReader.h
=> 2757: Bsp29Parser: provide a path to MipTextureReader

common/src/IO/ObjSerializer.cpp, common/src/IO/ObjSerializer.h
=> 2762: .OBJ export: don't share vertices between brushes

common/src/View/MapFrame.cpp
to prevent the pasted objects from interfering with the pick ray.
Fixes #2755
=> 2755: hide pasted objects before picking the location to move them to,

common/src/Model/World.cpp, test/src/View/MapDocumentTest.cpp
This showed up because I made Group no longer added to the spatial index, but the underlying bug was the `node->shouldAddToSpacialIndex()` checks.
Fixes #2776
=> 2776: Crash when pasting a TB Group

common/src/Renderer/Camera.cpp
Closes #2775.
Should we move this to 2019.6?
=> 2775: Clamp ortho camera zoom factor.

common/src/Model/TagManager.cpp, common/src/Model/TagManager.h
Closes #2787.
The problem was that TB would run out of free tag indices when reusing the same document to load multiple maps. This was because the tag manager would not reset the current tag index when the document was cleared. We now get the tag index from the number of tags currently registered, which fixes the problem and removes a member variable.
=> 2787: get free tag index from number of registered tags

Coding Standards.md, common/src/View/Actions.cpp, common/src/View/Actions.h
This is a fixup for #2836. We'd prefer to take arguments by const reference if possible. Arguments should be moved only if there's a measurable performance gain.
=> 2836: Don't move parameters into actions.

common/src/View/FaceAttribsEditor.cpp
textures are selected.
Fixes #2843
=> 2843: FaceAttribsEditor: correctly display "multi" when several unloaded

common/src/View/ToolBoxConnector.cpp, common/src/View/UVViewHelper.cpp
correctly in pixels. Fix ToolBoxConnector::processDragStart()
so it updates picking at the position where the mouse was when it clicked
Fixes #2808
=> 2808: UV scaling fixes: compute the mouse distance to the grid line

common/src/View/UVViewHelper.cpp, common/src/View/UVViewHelper.h
My previous pr was assuming the "hit point -> closest points on the X and Y grids" vectors would be axis-aligned in view space, which isn't the case with rotation or shear.
Fixes #2808
=> 2808: fix incorrect UV grid picking when texture is rotated/sheared

common/src/TrenchBroomApp.cpp, common/src/View/SwitchableMapViewContainer.cpp
The "// fix default palette higlight text color" bit was breaking some things on macOS's dark theme.
=> 2041: fix crash when changing map view layout, some text color with mac dark theme

common/src/Model/MapFacade.h, common/src/View/FaceAttribsEditor.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h
Currently the controls only work when brush faces are selected.
Closes #2889.
=> 2889: Fix face attribute controls for brush selections

common/src/IO/Path.cpp, common/src/IO/Path.h, common/src/IO/PathQt.cpp, common/src/IO/PathQt.h, common/src/Model/GameFactory.cpp, common/src/Model/GameFactory.h, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/RecentDocumentListBox.cpp, common/src/View/RecentDocumentListBox.h, common/src/View/RecentDocuments.cpp, common/src/View/RecentDocuments.h, common/src/View/WelcomeWindow.cpp, common/src/View/WelcomeWindow.h, common/test/src/IO/PathTest.cpp
I've grouped together a few fixes here because the crash on exit was masking the path corruption.
- Path::separator returns a string view on a C string literal, so it's faster, and works even if called very late in the program (previously it would maybe return an empty string if called from a static object's destructor)
- Remove GameFactory::~GameFactory() - which was running after main(), since GameFactory is a static singleton. This was what was calling Path::separator very late and getting "" returned. It was probably undefined behaviour to use Qt filesystem API's after QApplication was destroyed, too, so now this code (for saving stuff) runs in response to QCoreApplication::aboutToQuit which is what the Qt docs advise.
- Remove WelcomeWindow::closeEvent which was unnecessary as far as …
=> 2906: fix path corruption, crash on exit

common/src/View/QtUtils.cpp
This fixes #2907 on Windows 10 and brings the info labels back in line with their size in v2019.6, though I have a suspicion that the `- 2` was added to the info text font size for a reason.
Any ideas @kduske / @ericwa ? I'm wondering if this might be OS-specific.
=> Fix info label font size reduction vs v2019.6

common/src/View/CameraTool3D.cpp, common/src/View/InputEvent.cpp
Factored out the hack in CameraTool3D::doMouseScroll which removes Qt's
"Alt+VScroll=HScroll" virtualization, so we now always do this in
InputEventRecorder::recordEvent.
Fixes #2913
=> 2913: fix Ctrl + Alt + Scrollwheel for adjusting grid size on Windows

common/src/View/ResizeBrushesTool.cpp
Closes #2091
This was introduced when I changed `Hit::m_target`'s type to `std::any` and went over all usages. In `ResizeBrushesTool::collectDragHandles`, a hit of type `Resize3D` is converted to a brush faces directly by means of `Hit::target`. I changed this to use the hit adapter to convert a hit of type `BrushHit`, but the adapter does an additional check and returns null if the hit is not of type `BrushHit`, which is what we were hitting here. I changed it back to convert the hit target directly.
=> 2921: convert hit of type Resize3D to brush face directly, not via hit adapter

common/src/View/UVScaleTool.cpp
Closes #2936.
Another instance of a bad_any_cast, this time because the UV editor is accessing a handle hit even though it isn't a match.
=> 2936: Crash when opening UV editor

common/src/IO/GameConfigParser.cpp, common/src/IO/GameConfigParser.h, common/src/IO/MapFileSerializer.cpp, common/src/IO/MapStreamSerializer.cpp, common/src/IO/StandardMapParser.cpp, common/src/Model/BrushBuilder.cpp, common/src/Model/BrushBuilder.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/BrushFaceAttributes.cpp, common/src/Model/BrushFaceAttributes.h, common/src/Model/Game.cpp, common/src/Model/Game.h, common/src/Model/GameConfig.cpp, common/src/Model/GameConfig.h, common/src/Model/GameImpl.cpp, common/src/Model/GameImpl.h, common/src/View/CreateComplexBrushTool.cpp, common/src/View/CreateSimpleBrushTool.cpp, common/src/View/FaceAttribsEditor.cpp, common/src/View/MapDocument.cpp, common/src/View/MapView2D.cpp, common/src/View/VertexToolBase.h, common/test/src/IO/GameConfigParserTest.cpp, common/test/src/Model/BrushBuilderTest.cpp, common/test/src/Model/BrushTest.cpp, common/test/src/Model/TestGame.cpp, common/test/src/Model/TestGame.h, common/test/src/View/MapDocumentTest.cpp
This PR adds support for default face attributes for new brushes by defining the default values in game configuration file. The default options and all the fields are optional so only the needed default attributes can be added to the game config when needed.
example GameConfig.cfg: 
```json
{
"faceattribs": {
"defaults": {
"textureName": "defaultTexture",
"offset": [0, 0],
"scale": [0.5, 0.5],
"rotation": 0,
"surfaceContents": ["solid"],
"surfaceFlags": ["skip"],
"surfaceValue": 0,
"color": "1.0 1.0 1.0 1.0",
}
}
}
```
Closes #2500.
=> 2500: Add support for default face attributes

common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/QtUtils.cpp, common/src/View/QtUtils.h, common/src/View/RecentDocuments.cpp, common/src/View/ThreePaneMapView.cpp, common/src/View/TwoPaneMapView.cpp
Closes #2931.
This PR fixes the case where the preferences file `TrenchBroom Preferences` does not exist and therefore cannot be located by `QStandardPaths::locate`. Furthermore, I have unified the storage location of all non-preference settings (e.g. window positions, recent documents, file dialog paths) to be stored in `TrenchBroom Preferences`, too.
=> 2931: Recent documents are not saved

common/src/View/EntityAttributeEditor.cpp, common/src/View/EntityAttributeEditor.h, common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h
Closes #2923 and #2925.
- update buttons when entity attribute grid current item changes
- ensure selected row of entity grid is always visible
- set correct minimum size for entity attribute editor
=> 2923: Correctly enable / disable entity attribute buttons and ensure current row is always visible

common/src/View/Actions.cpp, common/test/fixture/preferences-v1.ini, common/test/fixture/preferences-v2.json, common/test/src/PreferencesTest.cpp
=> 2941: use original naming for tag / entity definition shortcuts

common/src/View/SpinControl.cpp
Values won't reflect in the brushes anymore while typing but in turn prevents the caret from jumping around while typing. This also matches the behavior with wxWidgets controls in previous versions.
Closes #2926.
=> 2926: SpinControl: Disable emitting valueChanged signal while typing

app/resources/documentation/manual/index.md, common/src/IO/GameConfigParser.cpp, common/src/IO/TextureCollectionLoader.cpp, common/src/IO/TextureCollectionLoader.h, common/src/IO/TextureLoader.cpp, common/src/Model/GameConfig.cpp, common/src/Model/GameConfig.h, common/test/CMakeLists.txt, common/test/src/IO/GameConfigParserTest.cpp, common/test/src/IO/TextureLoaderTest.cpp, common/test/src/Model/TestGame.cpp
The PR adds support for excluding textures from the texture browser by hiding the textures matching the glob patterns specified in game config file:
```
"textures": {
"excludes": [
"*_norm",
"*_bump",
"*_gloss"
]
},
```
This is very handy with engines/mods supporting normal, roughness and other texture maps, which would clutter the view with textures not needed for level editing.
Closes #2702.
=> 2702: Add support for texture exclusion patterns

common/src/View/KeyboardPreferencePane.cpp
=> 2940: fix oddly sized rows in keyboard shortcut grid

app/resources/games/Quake/Quake.fgd
testplayerstart is used for testing parts of your map quickly without having to noclip over to it every time you recompile. Instead of having to move your info_player_start around or copy it (which is a bit of a hassle because of how entity edicts determine which one will be picked), you can just create a testplayerstart somewhere and delete it when you're done. No muss, no fuss.
=> Added entity definition for testplayerstart to fgd

common/src/IO/GameConfigParser.cpp, common/src/Model/TagManager.cpp, common/test/src/IO/GameConfigParserTest.cpp, common/test/src/View/TagManagementTest.cpp
I decided to catch duplicate tag names when we parse the game configurations. We already have all the plumbing in place to catch errors in game configs, so throwing a parser exception there seems to be a good solution to me.
Closes #2905.
=> 2905: Check for duplicate tags when parsing game config

common/src/View/MapFrame.cpp
menu item; canPaste() is only checked when the clipboard changes
so it shouldn't consider focus state.
Fixes #2979
=> 2979: Don't check for the map view being focused to enable the paste

app/resources/games/Quake2/GameConfig.cfg, common/src/IO/MapFileSerializer.cpp, common/src/IO/MapStreamSerializer.cpp, common/src/IO/StandardMapParser.cpp, common/src/IO/StandardMapParser.h, common/src/Model/GameImpl.cpp, common/src/Model/MapFormat.cpp, common/src/Model/MapFormat.h, common/src/Model/ModelFactoryImpl.cpp, common/test/src/IO/NodeWriterTest.cpp, common/test/src/IO/WorldReaderTest.cpp
Fixes #2840
This format is supported by https://github.com/qbism/q2tools-220
I didn't implement support in `StandardMapParser::detectFormat` because it's a bit messy and this function is unused. When we switch to autodetecting map format we can implement it.
=> 2840: Support Quake2 (Valve) map format

common/src/View/CompilationContext.cpp, common/src/View/CompilationContext.h, common/src/View/CompilationRunner.cpp, common/src/View/CompilationRunner.h, common/test/CMakeLists.txt, common/test/src/View/CompilationRunToolTaskRunnerTest.cpp
There were multiple issues in the runner. First, it does not emit the
start() signal, and second, it immediately deletes the QProcess instance
when it finishes or when an error occurs. This commit changes it so that
the instance is only deleted when the runner itself gets deleted. Since
the runner itself is a QObject, it is not necessary to manually delete
the process, so the unique_ptr which managed the process is removed.
This commit also adds a test for the runner, but it's possible that this
test will not work on CI since it pops up the welcome window for some
reason.
=> Fix multiple issues in CompilationRunToolTaskRunner

common/src/Assets/Texture.cpp, common/src/Assets/Texture.h
Closes #2729.
Turns out that we need to leave the blending mode to default unless otherwise required by the shader or material being used. This PR adds this capability - by default, textures do not change OpenGL blending now, which enables transparency again.
=> 2729: Don't change blending modes unless required by the material

lib/CMakeLists.txt, lib/cpp17/CMakeLists.txt, lib/cpp17/LICENSE.TXT, lib/cpp17/include/any, lib/cpp17/include/optional, lib/cpp17/include/variant, lib/kdl/CMakeLists.txt, lib/kdl/include/kdl/result.h, lib/kdl/include/kdl/result_forward.h, lib/kdl/test/CMakeLists.txt, lib/kdl/test/src/result_test.cpp
@ericwa I have implemented a few result types. These are not finished and some features do not yet work due to missing features from `nonstd::variant`, but I'd like to get some feedback anyway. This PR adds the result types and some tests, and I have used the result types in `Brush::buildGeometry` instead of throwing exceptions. clang now warns about every place where this function is used without error handling.
=> 2983: Add expectation types for error handling

lib/kdl/include/kdl/result.h, lib/kdl/test/src/result_test.cpp
This PR fixes two issues. First, for result values with (possibly) empty values, it is no longer necessary to pass a default value to `visit_result`. Instead, a parameterless lambda is passed that is called in absence of a value.
Second, from other namespaces, the friend member template functions `visit_result` and `map_result` could only be called without prefixing them with `kdl`, so the following would compile:
```
namespace something {
void foo() {
auto r = kdl::result<int, std::string>::success(1);
visit_result(kdl::overload{
[](const int&)         {},
[](const std::string&) {}
}, r);
}
}
```
while prefixing the call to `visit_result` with the namespace `kdl` would not:
```
namespace something {
void foo() {
auto r = kdl::result<int, std::string>::success(1); …
```
=> 2983: Fix lookup of friend member template functions from other namespaces

common/src/View/LaunchGameEngineDialog.cpp
Let Qt parse the quotes and break out the arguments.
The previous code was wrong because it was passing the entire args
string as single array element.
Fixes #3012
=> 3012: use 1-argument version of QProcess::startDetached on win/linux

common/src/View/ResizeBrushesTool.cpp, common/src/View/VertexTool.cpp, common/src/View/VertexToolControllerBase.h
I reduced an example of what I think is the same issue; ASan doesn't like this (the `test` int has been destroyed already when  printf reads it):
```
#include <cstdio>
#include <tuple>
std::tuple<int,int> foo() {
return {2,3};
}
int main() {
const auto& test = std::get<1>(foo());
printf("%d", test);
return 0;
}
```
It seems like the temporary returned by std::get isn't eligible for lifetime extension. Closest I can find of an explanation is https://abseil.io/tips/101 but it doesn't directly address the std::get case.
We could alternatively rewrite these changed lines without references which would be safer in the long run.
Fixes #3028 (I couldn't reproduce a problem on Linux with ASan off, but with ASan on it crashed on master, and doesn't crash with these changes.)
=> 3028: fix incorrect use of lifetime extension

Build.md
CMake seems to default to 64-bit platform on 64-bit hosts if this parameter is missing.
=> Add missing platform parameter to build instructions for VS2017

appveyor.bat, appveyor.yml, common/src/IO/WalTextureReader.cpp, common/src/Renderer/FreeTypeFontFactory.cpp, lib/kdl/test/src/intrusive_circular_list_test.cpp, travis-linux.sh, travis-macos.sh
The kdl tests not running on CI was hiding 2 problems:
- ASan errors in intrusive_circular_list_test
- incorrect compilation VS2017, caught at runtime by the result_test_map test failing (#3039)
Fixing the ASan errors and restoring the kdl tests on CI was straightforward, but to fix #3039 the only thing I can see is updating to vs2019.
Fixes #3037 , fixes #3039
=> 3037: run kdl tests on CI, fix ASan errors, fix Windows test failues by updating to VS2019

app/resources/documentation/manual/index.md
The example for advanced model loading in ENT files is invalid XML, Trenchbroom does not successfully parse it, as there are nested double quotation marks. This commit modifies the inner quotation marks to be single quotation marks.
=> #3041: Fix quotation marks in ENT file example for model loading

common/src/View/CompilationDialog.cpp, common/src/View/CompilationDialog.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/src/View/QtUtils.cpp, common/src/View/QtUtils.h
Fixes #3011
- Fixes a memory leak (the compilation dialog was not WA_DeleteOnClose, but we were clearing the pointer to it with `m_compilationDialog = nullptr` which would cause a new compilation dialog to be allocated in `MapFrame::showCompileDialog`)
- Fixes handling of Escape key so it shows the "Are you sure" dialog if a compilation is running
- With this change I made the compile dialog persist between launches, since it's often handy to refer to the last compile output log even if you've closed the dialog
=> 3011: fix compilation dialog not showing again after Escape

app/resources/documentation/manual/index.md, app/resources/games/Quake3/GameConfig.cfg, common/src/IO/MapFileSerializer.cpp, common/src/IO/MapStreamSerializer.cpp, common/src/IO/StandardMapParser.cpp, common/src/Model/GameImpl.cpp, common/src/Model/MapFormat.cpp, common/src/Model/MapFormat.h, common/src/Model/ModelFactoryImpl.cpp, common/test/src/IO/NodeWriterTest.cpp, common/test/src/IO/WorldReaderTest.cpp
Fixes #3053 
The gist is that since q3map2 (at least the version from netradiant-custom) supports compiling Valve 220 format maps for Quake 3, TB can/should be able to produce Quake 3 maps in that format to take advantage of improved texture mapping.
* As per discussion in the issue thread, removed "Quake3" format from gameconfig & manual for now, since BP support isn't fully implemented. Some tweaks to the wording in the manual. Ready to tweak further if needed, or revert this if there's a better approach.
* Implemented "Quake3 (Valve)" format which is the same as "Quake2 (Valve)".
* In NodeWriterTest.cpp:
* Removed dumping the string to stdout in writeQuake2ValveMap ... this was the only test that was doing this.
* Added writeQuake3ValveMap. Almost identical to writeQuake2ValveMap, but …
=> 3053: Quake 3 "220 format" support

common/src/View/MapView2D.cpp, common/src/View/MapView3D.cpp, common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
and fix shortcuts not working after changing from 1-pane to 2-pane
Fixes #3060
Fixes #3059
This is the fist thing I could come up with that worked, not sure if it's a good/correct approach.
It's messy to do virtual function calls in a constructor, as well.
However, I don't like relying on document notifications to initialize the map views - in the normal TB startup case, keyboard shortcuts were only working by coincidence, because of the MapViewBase::documentDidChange firing after the MapView2D/3D was constructor.
=> 3060: fix a crash when changing from 1-pane to 2-pane with the clip tool active

app/resources/games/Quake3/GameConfig.cfg
Fixes #3065 
This matches the texture scale most often used with the original Quake 3 textures, and the default texture scale of other existing Q3 editors.
Tested by starting new maps in both 220 and legacy formats. Applying a texture to a face of the "start brush" results in 0.5 scale (both axes). Creating a new brush in a selected texture also results in 0.5 texture scale on its faces.
=> 3065: default 0.5 texture scale for Quake 3

app/cmake/GenerateManual.cmake
When generating the manual, we assume that pandoc is on the path. On my machine, it isn't, so the build is no longer working. But `find_program` can find pandoc, so we should use the path to the executable as reported by `find_program`.
=> Use actual pandoc path returned by find_program

common/src/View/MapView2D.cpp, common/src/View/MapView2D.h, common/src/View/MapView3D.cpp, common/src/View/MapView3D.h, common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
Vertical flip on 2D views should use the vertical axis of the viewport, so it needs
different logic than doGetMoveDirection
Note, in 2019.6 this was handled by the arrow keys switching their meaning in 2D/3D views: https://github.com/kduske/TrenchBroom/blob/v2019.6/common/src/View/ActionManager.cpp#L706 , which we no longer do. The changes to doGetMoveDirection to accommodate that change broke the flipping behaviour.
Fixes #3078
=> 3078: restore 2019.6 vertical flip behaviour in 2D views

common/src/Model/TagManager.cpp, common/src/Model/TagManager.h, common/src/View/ViewEditor.cpp, common/src/View/ViewEditor.h, common/test/src/View/TagManagementTest.cpp
The bug fix is in `TagManager::registerSmartTags`; the ViewEditor code changes were just cleanup, since I thought the problem might be there at first.
Fixes #3074
=> 3074: assign indices for smart tags

app/resources/documentation/manual/manual.md
Changed instructions to "GenerateManual" rather than "GenerateHelp". Updated about info about how macros are compiled. Renamed to manual since the directory and references are all to "manual" and not "help".
=> 3089: Update help.md and rename manual.md

app/resources/documentation/manual/index.md
Updated the manual as mentioned in 2901. Could maybe add more games to the table? Maybe we should also explain the format of GameConfig.cfg?
=> 2901: Updated manual with generic texture folder info

common/src/IO/EntParser.cpp, common/test/src/IO/EntParserTest.cpp
=> 3112: correctly parse spawnflag descriptions in .ent

common/src/View/InputState.h, common/src/View/SetBrushFaceAttributesTool.cpp, common/src/View/SetBrushFaceAttributesTool.h
- refactor SetBrushFaceAttributesTool, add
a missing mode (Alt+Ctrl+LMB Drag) that should have been supported
Fixes #3106
=> 3106: only allow LMB for Alt+click texture transfer

common/src/Model/CollectSelectedNodesVisitor.h, common/src/Model/MatchSelectedNodes.h, common/src/Model/Node.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapFrame.cpp, common/test/src/View/MapDocumentTest.cpp
#3177 was happening because we were hiding the parent entity of the selected brush, when isolating on some brushes in a brush entity.
I changed it so when you isolate on something, we show those selected nodes, all children, and all parents up to the layer, and hide everything else.
Fixes #3117
=> 3117: fix node query used for isolate()

app/cmake/GenerateManual.cmake, app/resources/documentation/manual/index.md, app/resources/documentation/manual/shortcuts_helper.js
It turns out we can't do the `#key(..)` and other macro substitutions on the .md file because changes the line lengths, breaking the table markup.
So we need another solution to the auto-ellipsis problem. This is the easiest thing I could come up with, doing it in JS.
Pandoc prior to 2.0 didn't auto convert "..." to an ellipsis character. Since 2.0 they do it automatically and added a "-f markdown-smart" flag to disable the auto ellipsis conversion.
=> 3121: fix broken tables in manual

CMakeLists.txt
Tested on Linux, it correctly removes this stuff from the .deb:
```
drwxr-xr-x root/root         0 2020-04-22 14:58 ./usr/lib/
drwxr-xr-x root/root         0 2020-04-22 14:58 ./usr/lib/cmake/
drwxr-xr-x root/root         0 2020-04-22 14:58 ./usr/lib/cmake/GTest/
-rw-r--r-- root/root      1075 2020-04-22 14:47 ./usr/lib/cmake/GTest/GTestConfig.cmake
-rw-r--r-- root/root      1382 2020-04-22 14:47 ./usr/lib/cmake/GTest/GTestConfigVersion.cmake
-rw-r--r-- root/root      2503 2020-04-22 14:47 ./usr/lib/cmake/GTest/GTestTargets-release.cmake
-rw-r--r-- root/root      4159 2020-04-22 14:47 ./usr/lib/cmake/GTest/GTestTargets.cmake
-rw-r--r-- root/root    254268 2020-04-22 14:47 ./usr/lib/libgmock.a
-rw-r--r-- root/root      2942 2020-04-22 14:47 ./usr/lib/libgmock_main.a
-rw-r--r-- root/root …
```
=> 3120: Block gtest installation

common/src/Model/MapFacade.h, common/src/View/FaceInspector.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/ReplaceTextureDialog.cpp, common/src/View/SetBrushFaceAttributesTool.cpp, common/test/src/View/MapDocumentTest.cpp
=> 3125: only toggle textures back to __tb_empty when clicking in the texture browser

common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/AboutDialog.cpp, common/src/View/FrameManager.cpp
- Remove some unnecessary code that was closing the About window when
the last MapFrame closes. Qt has a built in feature for this
(Qt::WA_QuitOnClose).
- Rmoeve hide/close distinction from Welcome window
Tested on Windows, still need to test on macOS/Linux
Fixes #3141
=> 3141: fix crash when map loading fails andd we show the welcome dialog again

app/src/Main.cpp, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h
=> 3140: disable Alt press+release from focusing the menu bar on Windows

common/src/View/CompilationRunner.cpp
Tested on Windows only so far.
Fixes #3146
=> 3146: use quotes around tool executable

common/src/View/ResizeBrushesToolController.cpp
Frees up MMB/RMB for potential other uses.
Fixes #3136
=> 3136: Only use LMB for Shift+Drag/Shift+Alt+Drag/Shift+Ctrl+Drag extrusion

common/src/View/WelcomeWindow.cpp
by the WM on Ubuntu
Fixes #3130
=> 3130: use Qt::Dialog window flag for WelcomeWindow so it gets centered

common/src/View/IssueBrowserView.cpp, common/test/src/View/MapDocumentTest.cpp, lib/kdl/include/kdl/set_adapter.h
Fixes #3142
The crash was caused by trying to fix the same issue twice; fixing it the first time caused the Issue object to be deallocated.
Also added a test of the issue generator. Doesn't actually test the cause of the crash
but I thought the problem was something else until I finished the test.
=> 3142: fix crash when fixing empty attribute name issues

app/resources/documentation/manual/index.md
Closes #3166
I couldn't reproduce the issue, but I changed the offending line anyways since it might depend on browser / pandoc version / whatever else that I cannot reproduce.
=> Don't use #menu macro at the start of a paragraph

common/src/View/Autosaver.cpp, common/src/View/Autosaver.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/test/src/View/AutosaverTest.cpp
Closes #3150
This PR changes the autosaver so that it will not trigger an autosave for 1s after the last user interaction. A user interaction is any keyboard or mouse event with the map frame. This will make autosaving less frequent, but it will prevent the autosave from interrupting the user.
=> Don't trigger autosave during user interaction

common/src/View/BorderPanel.cpp
Fixes cracks under the MapViewBar's bottom line, on Windows at 200% scaling (probably mac /Linux as well).
Before:
Fixes #3159
=> 3159: BorderPanel: use fills with QRectF, instead of strokes

common/src/View/EntityAttributeEditor.cpp, common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h, common/src/View/EntityAttributeModel.cpp, common/src/View/EntityAttributeTable.cpp, common/src/View/EntityAttributeTable.h
Fixes #3165
- rename misleading signal name from EntityAttributeGrid::selectedRow to currentRowChanged
- Listen for QItemSelectionModel::selectionChanged and update the controls, fixes the remove button not being enabled when clicking on a new cell
- fixes updating buttons when deleting several rows
- fixes updating buttons when setting a value on a default attribute
- fix tooltips for add/remove buttons missing the keyboard shortcuts
=> 3165: don't allow removing default attributes

common/src/View/KeyboardPreferencePane.cpp, common/src/View/KeyboardShortcutItemDelegate.cpp, common/src/View/KeyboardShortcutItemDelegate.h
- make first column wider so cell editor doesn't get cut off
- automatcially close editor after delay
- double click (or Enter) to start editing
- drop autoResizeRows, it's too slow
Fixes #3135
=> 3135: Tweaks to shortcut editor

common/src/View/Inspector.cpp, common/src/View/Inspector.h, common/src/View/MapViewBar.cpp, common/src/View/QtUtils.cpp, common/src/View/RotateObjectsToolPage.cpp
Closes #3180
- No longer sync the map view bar height to the inspector tool bar height.
- Fix some layout issues with the map view bar on macOS.
=> Allow map view toolbar and inspector tab bar to shrink again

common/src/View/BorderLine.cpp, common/src/View/CompilationTaskListBox.cpp, common/src/View/ControlListBox.cpp, common/src/View/QtUtils.cpp, common/src/View/QtUtils.h
Main change is the ControlListBox items now fill their background with QPalette::Base (when unselected) and QPalette::Highlight (when selected). This lets us continue using QPalette::HighlightText to get good contrast against QPalette::Highlight.
As far as I can see, you're not supposed to put QLabels in a list box with https://doc.qt.io/qt-5/qlistwidget.html#setItemWidget , and there's no palette color you can use to get good text contrast. Instead you're supposed to implement the paint function on a custom delegate to paint text. This is lower-level of course.
The reason for this change:
```
-setStyleSheet("QFrame#borderLine { color: " + Colors::borderColor().name() + "; }");
+setForegroundRole(QPalette::Shadow);
```
was, with the TB dark theme, if you selected a compile task, the …
=> 3193: Fix ControListBox text highlighting on Windows theme

common/src/View/Actions.cpp
Fixes #3211
I tested both a keybinding to create a point entity and one to create a brush entity, both work as expected (the shortcut to create a brush entity does nothing if there's no selection)
=> 3211: allow shortcuts creating point entities with no selection

common/cmake/CppCheck.cmake, common/src/Renderer/AllocationTracker.cpp, travis-macos.sh
Fixes #3215
Also disabled 2 source of log spam in the macOS CI log, that were causing the cppcheck error to not be visible.
=> 3215: suppress false positive from cppcheck 2.0

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/test/src/View/TagManagementTest.cpp
Fixes #3214
Note that Brush::doSetNewGeometry clones the BrushFaces (which doesn't clone the Taggable info per face). Since this is called after vertex manipulation, we were left with cleared face tags.
=> 3214: update face tags when the brush changes

common/src/View/CompilationRunner.cpp, common/src/View/TextOutputAdapter.cpp, common/src/View/TextOutputAdapter.h, common/test/CMakeLists.txt, common/test/src/View/TextOutputAdapterTest.cpp
Fixes #3210
This is a rewrite of TextOutputAdapter that fixes a few problems:
- display output in realtime rather than buffering an entire line, so we can see slow progress bars fill up
- I think the `\r` handling in compressString was wrong.. you need a writable std::string representing the whole line and be able to rewrite different amounts of it multiple times, because you can have many `\r`'s on a line.
- Fix cursor handling, use a private cursor for the insertions, separate from the UI cursor (you can select text while the log is being appended to without anything breaking)
- Lock scroll bar at the bottom unless the user moves it away manually
- we were doing an unnecessary QString conversion (local 8 bit -> utf-16 -> utf-8 -> utf-16) before, now it's (local 8-bit -> utf-16). This is …
=> 3210: TextOutputAdapter fixes

common/src/IO/StandardMapParser.cpp, common/test/src/IO/WorldReaderTest.cpp, common/test/src/View/MapDocumentTest.cpp
Fixes #3212
This should be totally safe because we already use __TB_empty (Model::BrushFaceAttributes::NoTextureName) in various scenarios, so this change will just let stay as __TB_empty when loading a map.
I left some more suggestions for further cleanup in #3220 that we can look at later
=> 3212: don't convert "__TB_empty" to "" on map load

common/src/Model/GameFactory.cpp, common/src/Model/GameFactory.h
Closes #2994.
Unfortunately `GameFactory` isn't easily testable, so no test cases for this bug.
=> 2994: Don't crash when non existing game is detected

common/src/Model/BrushNode.cpp, common/src/Model/BrushNode.h, common/src/Renderer/MapRenderer.cpp, common/src/View/ResizeBrushesTool.cpp, common/test/src/Model/BrushNodeTest.cpp
Closes #3239 
@ericwa This fixes the behavior for me, but I wasn't able to reproduce the assertion failures you reported. Maybe you could give it another try?
=> 3239: Use correct face to update drag handles after extruding inwards

common/src/Color.h, common/src/Model/BrushFaceHandle.cpp, common/src/View/UVView.cpp, common/src/View/UVViewHelper.cpp, common/src/View/UVViewHelper.h
The BrushFace* in UVViewHelper was becoming dangling when we update the brush face attributes, and then the UV view was causing a crash when it tried to render.
As I understand the new design, UVViewHelper  shouldn't have been storing a BrushFace* pointer in the first place, so I changed it to an optional BrushFaceHandle.
Fixes #3247
=> 3247: Fix crash when setting a texture on a face

common/src/View/FaceInspector.cpp
(Note: this depends on https://github.com/kduske/TrenchBroom/pull/3248 so that should be merged first)
Fixes #3246 by reverting FaceInspector::textureSelected back to how it was in 2020.1
=> 3246: fix unsetting textures by clicking on them again

common/src/View/Actions.cpp
Closes #3225
I just added the flip actions to the main menu. I left the preference path the same as before, but at some point, we'll have to clean these up. Ideally, we should stop having separate paths for view actions and for menu actions, as this line is getting blurred.
=> Add flip actions to edit menu

common/src/View/MapDocumentCommandFacade.cpp
=> 3258: Set textures after restoring node snapshot

common/src/Model/Brush.cpp, common/src/Model/Brush.h
=> 2791: Use larger epsilon value when finding vertex after manipulation

common/src/View/ResizeBrushesTool.cpp
Closes #2790 
This PR relaxes the check for coplanarity when finding coplanar brush faces for the resize tool.
=> 2790: Be less strict when finding coplanar faces to resize

common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/ChangeBrushFaceAttributesRequest.cpp, common/src/View/UVOffsetTool.cpp, common/src/View/UVOriginTool.cpp, common/src/View/UVRotateTool.cpp, common/src/View/UVScaleTool.cpp, common/src/View/UVShearTool.cpp, common/src/View/UVView.cpp, common/test/src/IO/NodeWriterTest.cpp, common/test/src/Model/BrushFaceTest.cpp, common/test/src/View/TagManagementTest.cpp
Closes #3266
This also fixes the issue of texture rotation not being applied correctly.
=> 3266: Don't crash when using UV editor

common/src/IO/FileSystem.cpp, common/src/IO/FileSystem.h, common/src/Model/GameFactory.cpp
=> 2505: Use safer method to write compilation configs and engine profiles

common/src/Model/Game.cpp, common/src/Model/Game.h, common/src/Model/GameImpl.cpp, common/src/Model/GameImpl.h, common/src/View/FileTextureCollectionEditor.cpp, common/test/src/Model/TestGame.cpp, common/test/src/Model/TestGame.h
=> 3271: Filter the "Add file texture collections" file types to the proper extensions

common/src/View/Actions.cpp, common/src/View/CellView.cpp, common/src/View/CellView.h, common/src/View/FaceInspector.cpp, common/src/View/FaceInspector.h, common/src/View/Inspector.cpp, common/src/View/Inspector.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/src/View/MapViewBase.cpp, common/src/View/TextureBrowser.cpp, common/src/View/TextureBrowser.h, common/src/View/TextureBrowserView.cpp, common/src/View/TextureBrowserView.h
Adds this context menu item (only shown if there's only 1 texture on the selected faces/brushes), which switches to the texture browser and scrolls to the texture:
Also there's a action that can have a key bound.
Fixes #3156
=> 3156: "Reveal in texture browser" context menu item

app/resources/shader/EntityLinkArrow.vertsh, common/src/Renderer/BrushRendererArrays.h, common/src/Renderer/EntityLinkRenderer.h, common/src/Renderer/GLVertexAttributeType.h, common/src/Renderer/GLVertexType.h, common/src/Renderer/ShaderManager.cpp, common/src/Renderer/ShaderManager.h, common/src/Renderer/ShaderProgram.cpp, common/src/Renderer/ShaderProgram.h, common/src/Renderer/VboManager.cpp, common/src/Renderer/VboManager.h, common/src/Renderer/VertexArray.h, common/src/View/GLContextManager.cpp, common/src/View/GLContextManager.h
Fixes #3286
- Working implementation of GLVertexAttributeTypeTag::User (now called `class GLVertexAttributeUser`)
- pass current program into setup()/cleanup() for vertex attributes. This is needed so we can lookup the attribute indices with `glGetAttribLocation` (hidden in `ShaderProgram::findAttributeLocation`)
- instead of partial template specialization of GLVertexAttributeType, just use separate classes for Vertex/Normal/Color/TexCoord/User. I needed GLVertexAttributeUser to have different template params that the other classes, so AFAIK partial template specialization wouldn't work here.
- use in EntityLinkArrow, so it doesn't need to pass the arrow position/direction in `gl_MultiTexCoord0/1`
=> 3286: generic vertex attributes

common/src/View/Actions.cpp
=> 3291: show checked state of "show grid" and "snap to grid" menu items

common/src/View/MapDocumentCommandFacade.cpp, common/test/src/View/SnapshotTest.cpp
Not just the selected brush faces, because the snapshot restoration
invalidates the texture pointers on all faces of the brush.
Fixes #3289
=> 3289: MapDocumentCommandFacade::restoreSnapshot: restore entire node

app/resources/documentation/manual/index.md, common/src/IO/GameConfigParser.cpp, common/src/IO/GameConfigParser.h, common/src/Model/TagMatcher.cpp, common/src/Model/TagMatcher.h, common/test/src/View/TagManagementTest.cpp
Closes #3288 
In version 4 of the game config format, accept a list for "pattern" value of a surfaceparm smart tag. The tag will match against any shader that has any of the listed params. A single "pattern" value (as in version 3) is still accepted.
Use a std::set to store this list to make it easy to quickly find intersection with the set of surfaceparms.
Also, enable the "turn selection into" keyboard shortcuts for surfaceparm smart tags.
Factored some common code with the texture name smart tag matcher into a superclass.
----------
Note that in TagMatcher.h the public-ness of some TagMatcher-subclass methods has been changed to match the access type of the TagMatcher methods they are overriding.
----------
In the tag matching tests:
Because of refactoring in the texture tag matcher, …
=> 3288: Surfaceparm smart tag improvements

app/resources/games/Quake3/GameConfig.cfg
Closes #3230.
* Remove all surface flags.
* Remove all content flags except for detail.
* Fix the texture path for the Trigger smart tag (should be "common/trigger"). (And tweak the classname match pattern to the usual one.)
* Remove smart tags that refer to nonexistent content/surface flags (Liquid, Sound, Transparent).
* Remove the Skip smart tag for reasons described in the issue.
* Add some smart tags and tweak existing ones for reasons described in the issue:
* Areaportal and Clusterportal are new.
* Translucent kinda replaces the old Transparent. Now matches on surfaceparms.
* Liquid replaces the old Liquid. Now matches on surfaceparms.
* Caulk, Clip, and Hint have different matching rules.
=> 3230: Q3 game config updates/fixes

common/src/IO/SkinLoader.cpp, common/src/IO/TextureLoader.cpp, common/src/IO/TextureReader.cpp, common/src/IO/TextureReader.h, common/test/CMakeLists.txt, common/test/src/IO/M8TextureReaderTest.cpp, common/test/src/IO/Md3ParserTest.cpp, common/test/src/IO/PathSuffixNameStrategyTest.cpp, common/test/src/IO/WalTextureReaderTest.cpp
Closes #3035.
This is a followup to #3277, which added support for deeply nested textures. This PR fixes how TB determines texture names from their paths.
=> 3035: Compute texture names correctly for deeply nested files

common/cmake/CppCheck.cmake, common/src/IO/GameConfigParser.cpp, common/src/Renderer/BrushRendererArrays.cpp, common/src/Renderer/BrushRendererArrays.h, common/src/View/CellLayout.h, common/src/View/CreateBrushToolBase.h, common/src/View/MapDocument.cpp, common/src/View/MoveToolController.h, common/src/View/SwitchableMapViewContainer.h, common/src/View/ToolBoxConnector.h
- use all CPU's for cppcheck
- remove workarounds for cppcheck <2.1
- remove broken generator expression which was intended to get include paths
Instead only include the root COMMON_SOURCE_DIR so things like Ensure.h
work. Note, the cppcheck docs explicitly say not to provide all
include dirs, e.g. system and external libraries.
Fixes #3305
=> 33305: fix cppcheck warnings

common/src/View/CompilationDialog.cpp, common/src/View/CompilationDialog.h, common/src/View/CompilationRun.cpp, common/src/View/CompilationRun.h, common/src/View/CompilationRunner.cpp
Closes #3280.
Having explicit buttons makes state management easier and makes the testing functionality easier to discover for users.
This PR also fixes some problems where start / stop notifications from the compilation runners would not work correctly.
=> 3280: Add explicit start / stop / test buttons to compilation dialog

common/src/View/MapView2D.cpp
=> 3307: make "select tall" brush smaller than world bounds

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/BrushFace.cpp, common/src/Model/Tag.cpp, common/src/Model/Tag.h
Fixes #3303
To recap the problem, `MapDocumentCommandFacade::performChangeBrushFaceAttributes` doesn't call the `brushFacesDidChangeNotifier` (which would update face tags) if no attributes actually changed, but it still does
```
Brush brush = node->brush();
...
node->setBrush(std::move(brush));
```
which causes the brush faces to lose tags, since tags aren't copied/moved.
I fixed this by making BrushFace copy/move constructors and swap transfer the Taggable data as well. IMO this is the right fix because it's confusing if `Brush x = std::move(y);` causes the tags on `y` to be lost.
This also fixes several related bugs with `MapDocumentCommandFacade::performMoveTextures`, `performRotateTextures`. `performShearTextures`, `performCopyTexCoordSystemFromFace` which you can see on master if …
=> 3303: fix reapplying a texture causing tags to be cleared

common/src/IO/DiskFileSystem.cpp, common/src/IO/FgdParser.cpp, common/src/IO/FgdParser.h, common/test/src/IO/DiskFileSystemTest.cpp, common/test/src/IO/M8TextureReaderTest.cpp, common/test/src/IO/WalTextureReaderTest.cpp
Closes #3035
The problem was caused by the paths stored in files returned from a `DiskFileSystem`. These paths were absolute when they should have been relative to the file system root path for consistency with the image file systems.
This PR changes that and fixes some behavior that relied on the absolute paths.
=> 3035: Don't return files with absolute paths from DiskFileSystem

app/resources/documentation/manual/index.md, common/src/Assets/ModelDefinition.cpp, common/src/EL/Expression.cpp, common/src/EL/Expression.h, common/src/EL/Value.cpp, common/src/EL/Value.h, common/src/IO/CompilationConfigParser.cpp, common/src/IO/ConfigParserBase.cpp, common/src/IO/ELParser.cpp, common/src/IO/ELParser.h, common/src/IO/EntParser.cpp, common/src/IO/GameConfigParser.cpp, common/src/IO/GameEngineConfigParser.cpp, common/src/IO/LegacyModelDefinitionParser.cpp, common/src/IO/LegacyModelDefinitionParser.h, common/src/Model/EntityAttributesVariableStore.cpp, common/test/src/EL/ExpressionTest.cpp
This PR refators `EL::Value` and `EL::Expression` to make them easier to extend. The polymorphism inherent to both types is now expressed via `std::variant` instead of inheritance. Both types now fully behave like value types and can be copied and moved around.
=> 3317: Refactor EL values and expressions

common/src/View/CreateSimpleBrushTool.cpp
=> 3333: CreateSimpleBrushTool: don't crash when dragging beyond world bounds

common/src/Model/NodeCollection.cpp, common/src/Model/NodeCollection.h, common/src/View/MapDocument.cpp, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapFrame.cpp
and ignore point entities (rather than disabling the command)
Fixes #2971
=> 2971: Change "snap vertices" commands to snap brushes inside groups, 

common/src/View/SelectionTool.cpp, common/src/View/SetBrushFaceAttributesTool.cpp
when alt+clicking quickly after a face selection click.
Fixes #3332
=> 3332: SetBrushFaceAttributesTool::doMouseDoubleClick: don't crash

common/src/View/MapDocument.cpp
Fixes #3186 - This just closes any open groups when you switch layers.
Previously, the group would stay open if you changed the active layer, but the objects in the open group would become locked, which was confusing.
=> 3186: Close open groups before switching current layers

common/CMakeLists.txt, common/src/Model/Brush.cpp, common/src/Model/BrushError.cpp, common/src/Model/BrushError.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/ModelFactoryImpl.cpp, common/src/View/ResizeBrushesTool.cpp, common/test/src/Model/BrushFaceTest.cpp, common/test/src/Model/BrushNodeTest.cpp, common/test/src/Model/BrushTest.cpp, common/test/src/TestUtils.cpp, common/test/src/TestUtils.h, lib/kdl/include/kdl/result.h, lib/kdl/test/src/result_test.cpp
This PR changes `BrushFace`'s interface to use result types instead of throwing exceptions. The call sites are changed so that they either handle errors locally (where appropriate), or throw `GeometryException` in case of error.
These newly introduced throws will be handled in later PRs.
=> 2983: Use result types for BrushFace

common/src/View/DuplicateNodesCommand.cpp, common/src/View/DuplicateNodesCommand.h, common/test/src/View/GroupNodesTest.cpp
Fixes #3348
This just fixes a bug introduced with the changes in the "layers PR" to where new objects are inserted.
=> 3348: fix Ctrl+dragging brushes in an open group not adding them to the group

.github/workflows/clean-commit.yml
Closes #3173
This PR adds a script that is run by travis. The script checks the commit history of the branch against a list of bad words, currently `fixup dropme wip`.
=> 3173: Check branches for bad words

common/src/Model/Brush.cpp, common/src/Model/BrushFace.cpp, common/src/Model/ModelFactoryImpl.cpp, common/src/PreferenceManager.cpp, common/test/src/Model/BrushFaceTest.cpp, common/test/src/PreferencesTest.cpp, common/test/src/TestUtils.cpp, lib/kdl/include/kdl/result.h, lib/kdl/test/src/result_test.cpp
This PR changes the result type API as follows:
- adds member functions `result::visit`, `result::and_then` and `result::get`
- removes free functions `visit_result`, `map_result` and `get_success` in favor of the member functions
- documentation improvements
=> 2983: Refactor result type API

common/src/View/QtUtils.cpp, common/src/View/QtUtils.h, common/src/View/SpinControl.cpp, common/src/View/SpinControl.h
=> 3369: add tooltip for SpinControl documenting Shift/Ctrl modifiers

app/resources/documentation/manual/index.md, common/src/Model/CompilationConfig.cpp, common/src/Model/CompilationConfig.h, common/src/View/CompilationProfileListBox.cpp, common/src/View/CompilationProfileListBox.h, common/src/View/CompilationProfileManager.cpp, common/src/View/CompilationProfileManager.h
=> 1709: add context menu to duplicate/remove compile profiles

common/src/Model/Polyhedron.h, common/src/Model/Polyhedron_ConvexHull.h, lib/kdl/include/kdl/intrusive_circular_list.h
There was one private function in Polyhedron that would throw an exception. This PR handles the causal error condition and handles it locally.
=> 2983: Don't throw exceptions from Polyhedron

common/src/View/MapFrame.cpp, common/src/View/MapFrame.h
Also tweak the spacing a bit:
This is part of #2815 , there are more ideas there which are more work to do so I'll leave it open.
=> 2815: Status bar: add game name, map format, and hidden node counts

app/resources/games/DigitalPaintball2/pball2.fgd, app/resources/games/Quake/Rubicon2.def, common/src/Assets/AttributeDefinition.cpp, common/src/Assets/AttributeDefinition.h, common/src/Assets/ModelDefinition.cpp, common/src/Assets/ModelDefinition.h, common/src/Exceptions.h, common/src/IO/DefParser.cpp, common/src/IO/DefParser.h, common/src/IO/EntParser.cpp, common/src/IO/EntParser.h, common/src/IO/EntityDefinitionClassInfo.cpp, common/src/IO/EntityDefinitionClassInfo.h, common/src/IO/EntityDefinitionParser.cpp, common/src/IO/EntityDefinitionParser.h, common/src/IO/FgdParser.cpp, common/src/IO/FgdParser.h, common/src/IO/ParserStatus.cpp, common/test/CMakeLists.txt, common/test/src/IO/DefParserTest.cpp, common/test/src/IO/EntParserTest.cpp, common/test/src/IO/EntityDefinitionParserTest.cpp, common/test/src/IO/FgdParserTest.cpp, common/test/src/IO/TestParserStatus.cpp, common/test/src/IO/TestParserStatus.h, lib/kdl/CMakeLists.txt, lib/kdl/include/kdl/opt_utils.h
Closes #3379.
This PR refactors some of the entity definition parser internals, and then proceeds to rewrite the inheritance code so that it allows inheriting from non-baseclasses. It also fixes the semantics of inheritance across different file formats since it is now all handled in one place.
=> 3379: Improve handling of entity definition inheritance

common/src/IO/TextureCollectionLoader.cpp, common/src/IO/TextureCollectionLoader.h, lib/kdl/include/kdl/transform_range.h
Closes #3347.
There's quite a bit of duplicated code between the two texture collection loader implementations, but all other approaches would have been much more complicated.
=> 3347: Don't open all texture files at once when loading loose textures

app/resources/documentation/manual/index.md, app/resources/graphics/images/OmitFromExport.svg, common/src/IO/MapReader.cpp, common/src/IO/NodeSerializer.cpp, common/src/IO/NodeSerializer.h, common/src/IO/NodeWriter.cpp, common/src/IO/NodeWriter.h, common/src/IO/WorldReader.cpp, common/src/Model/EntityAttributes.cpp, common/src/Model/EntityAttributes.h, common/src/Model/ExportFormat.h, common/src/Model/GameImpl.cpp, common/src/Model/GameImpl.h, common/src/Model/LayerNode.cpp, common/src/Model/LayerNode.h, common/src/View/Actions.cpp, common/src/View/CompilationRunner.cpp, common/src/View/LayerEditor.cpp, common/src/View/LayerEditor.h, common/src/View/LayerListBox.cpp, common/src/View/LayerListBox.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/test/src/IO/NodeWriterTest.cpp, common/test/src/IO/WorldReaderTest.cpp, common/test/src/TestUtils.cpp, common/test/src/TestUtils.h
Fixes #876
Another small but hopefully useful piece of the layers upgrade.
- The flag is persisted in the .map file, similar to the hidden/lock state.
- It doesn't do anything, except when exporting, causes the marked layer to not be exported.
- The flag is only enabled via this checkbox in the layer context menu, but when enabled, the X icon in the layer row can be clicked to turn off the flag:
The thinking was, it's essential to be able to see at a glance which layers are "omitted", but maybe not so essential to be able to turn on "omit from export" in one click.
- Since not everyone uses the compile UI, I added a File->Export->Map menu item. It does the same thing as the "export map file" compile step, which is the same as a normal save, except marked layers are omitted.
=> 876: option to omit layer from map exports

common/src/View/Actions.cpp, common/src/View/Actions.h, common/src/View/MainMenuBuilder.cpp
Add one for "Export map".
Fixes #3414
=> 3414: add support for Qt status tips on menu items

common/src/View/MapDocument.cpp
Fixes #3384
Should we also rename `allSelectedAttributableNodes` to `recursivelySelectedAttributableNodes`?
Aside from just changing this one line I did review all the call sites for `allSelectedAttributableNodes` and confirm that they'll be OK  with this change (it's only used in entity inspector related functionality), and also test out the undo/redo behaviour.
=> 3384: treat a Group selection as if the contents are selected

common/src/IO/BrushFaceReader.h, common/src/IO/MapParser.cpp, common/src/IO/MapParser.h, common/src/IO/MapReader.cpp, common/src/IO/MapReader.h, common/src/IO/NodeReader.cpp, common/src/IO/NodeReader.h, common/src/IO/StandardMapParser.cpp, common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/MapFormat.cpp, common/src/Model/MapFormat.h, common/src/Model/ModelFactory.cpp, common/src/Model/ModelFactory.h, common/src/Model/ModelFactoryImpl.cpp, common/src/Model/ModelFactoryImpl.h, common/src/Model/ParallelTexCoordSystem.cpp, common/src/Model/ParallelTexCoordSystem.h, common/src/Model/ParaxialTexCoordSystem.cpp, common/src/Model/ParaxialTexCoordSystem.h, common/src/Model/TexCoordSystem.cpp, common/src/Model/TexCoordSystem.h, common/src/Model/WorldNode.cpp, common/src/Model/WorldNode.h, common/test/src/Model/BrushFaceTest.cpp
Fixes #1448
- conversion only happens in `NodeReader::read`, i.e. when pasting, not when opening maps.
- conversion only happens between Standard and Valve variants of a game, not between games. 
Here's a screenshot of a valve -> standard conversion:
=> 1448: paste across standard/valve maps

common/src/View/CompilationRun.cpp, common/src/View/CompilationRun.h, common/src/View/CompilationRunner.cpp, common/src/View/CompilationRunner.h
Caused by deleting the CompilationRun (deleting the QProcess) during execution of a QProcess signal.
Fixes #3422
=> 3422: fix crash when a compile task fails

common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeGrid.h, common/src/View/EntityAttributeModel.cpp, common/src/View/EntityAttributeModel.h, common/src/View/SmartAttributeEditorManager.cpp, common/src/View/SmartTypeEditorMatcher.cpp, common/src/View/SmartTypeEditorMatcher.h
Fixes #3421
There are 3 changes here:
1. 671515cea03019d3e32acbf436b7aea41065b4fa stopped showing the spawnflags smart editor for multiple entities, if they had different spawnflags definitons. I've changed the meaning of `SmartTypeEditorMatcher` to allow this again, and added a new `SmartTypeWithSameDefinitionEditorMatcher` that does what `SmartTypeEditorMatcher` used to.
2. generate more precise diffs in EntityAttributeModel - the previous code only handled a few cases and it would give up and reset the model if rows were both added and removed. This change fixes the bug where a selected cell (e.g. "target") would get deselected if you clicked on a different entity with a different classname that still had a "target" cell.
3. Back up and restore selections in the attribute grid. This …
=> 3421: entity attribute grid fixes

app/resources/documentation/manual/index.md
Closes #3438.
As per issue #3067 it looks like defaults.textureName doesn't do anything and should be omitted from the docs, but the other defaults properties (scale/surfaceFlags/etc.) would be good to have doc'd.
=> 3438: document faceattribs.defaults

common/src/Assets/TextureCollection.cpp
=> 3444: don't crash on empty texture collections

common/src/View/CompilationRun.cpp, common/src/View/CompilationTaskListBox.cpp, common/test/src/EL/InterpolatorTest.cpp
Fixes #3447
I tested putting invalid EL into all of the text boxes of the compile dialog, and it no longer crashes with these fixes.
=> 3447: catch exceptions in compile dialog with malformed EL input

app/resources/games/DDayNormandy/GameConfig.cfg, app/resources/games/DigitalPaintball2/GameConfig.cfg
Alrighty, here we go! After a crash course in GitHub from Eric, I would like to present Quake 2 Valve map support for Quake 2 engine based games D-Day Normandy and Digital Paintball2.
=> Adding Quake2 (Valve) map support.

app/resources/games/DDayNormandy/dday.fgd, app/resources/games/DigitalPaintball2/pball2.fgd, app/resources/games/Quake/Quake.fgd, app/resources/games/Quake/Quoth2.fgd, app/resources/games/Quake/Teamfortress.fgd
Linked issue: #3404 (doesn't fully close it.)
- Quake.fgd: Target class already includes killtarget, so just delete the
typo parent class "Killarget"
- Quoth2.fgd: classes (Targetname) are case sensitive. remove non-existant
superclass "Name" on air_bubbles
- Teamfortress.fgd: Killarget typo
=> 3404: fix Quake .fgd warnings

app/resources/games/Heretic2/heretic2.fgd
Cleaned up the warnings and error message from the TB console on load.
- This fixes the superclass "character" case issues.
- Renamed the duplicate light_chandelier2 to light_chandelier3 and updated the descriptions for all 3 chandeliers.
- Removed unneeded numeric default value of 0 for string property in jumptarget(target_destination)
- Fixed the warning for the float default value for integer property inside the superclass "Sound" on (line 1755, column 31).
=> Heretic2.fgd clean up

app/resources/games/Kingpin/kingpin.fgd
- Removed 4 instances of unknown entity definition header attribute 'offset' on lines 135, 999, 2476, and 2490.
- Removed unknown entity definition header attribute 'flags' (line 593, column 58)
- Removed size from solid entity definition (line 864, column 13)
- Removed duplicate attribute definition: 'wait' (line 908, column 5)
=> Fix the kingpin.fgd warnings.

common/src/View/CreateEntityTool.cpp, common/src/View/Grid.cpp, common/src/View/Grid.h, common/src/View/MapView3D.cpp, common/test/src/TestUtils.h, common/test/src/View/GridTest.cpp
Document the heuritics used.
Fixes #3450
=> 3450: rewrite Grid::moveDeltaForBounds to avoid off-grid pastes on slopes

app/resources/games/Quake/GameConfig.cfg
Fixes #3479
- Added "func" to the brush tags (so I can alt-f to get func creation
drop-down on the fly)
- Made skip opaque, because transparent skip is pretty hellish really.
I know a few people have switched this as well. Skip is solid and
structural, no real reason to have it transparent.
- On the other hand, made Liquid transparent, cause that makes a lot
more sense, even when using opaque liquid in game it's good to see through it in editor!
(I left off the transparent `*glass*` brushface tag)
=> 3479: Quake game config updates from Bal.

common/src/View/MapFrame.cpp, common/src/View/MapFrame.h, common/src/View/MapViewBase.cpp
Fixes #3480
Note, if you set a key binding to "Reveal in Texture Browser", it uses the old behaviour of revealing the texture of the selected face/brush. We can tweak that later, if needed (e.g. it could use the new behaviour of looking at the face under the mouse.)
=> 3480: make "Reveal in Texture Browser" use face under mouse, not selection

common/src/Model/EntityRotationPolicy.cpp
=> 3488: fix rotation not updating "angle" when entity origin is off-grid

common/src/Model/EditorContext.cpp
Related: #3492 (leaving open as this only fixes the easy part of that overall issue)
This is probably safe enough to go into 2020.2 (same logic is used below for brush entities). At the same time it's not a critical regression fix so could also wait.
=> 3492: hide groups when everything inside is hidden

app/resources/shader/EntityLink.fragsh, app/resources/shader/EntityLinkArrow.fragsh, app/resources/shader/EntityLinkArrow.vertsh, common/src/Renderer/EntityLinkRenderer.cpp
Fixes #3487
Note, this was an existing bug that surfaced when we increased the
map bounds to +/-32K in 4b8a4451fb027eddce57dbbe24cfc3a028426ecd
=> 3487: fix entity links not rendering in 2D views

common/src/IO/NodeWriter.cpp, common/src/IO/NodeWriter.h, common/src/Model/GameImpl.cpp
Also fix confusing NodeWriter constructor that took ownership of a raw ptr.
Fixes #3512
=> 3512: Configure Obj writer for exporting (so omitted layers are omitted)

common/src/Assets/Palette.cpp, common/src/Assets/Palette.h, common/src/Assets/Texture.h, common/src/Assets/TextureBuffer.cpp, common/src/Assets/TextureBuffer.h, common/src/Assets/TextureManager.cpp, common/src/IO/M8TextureReader.cpp, common/src/IO/MdlParser.cpp, common/src/IO/MdlParser.h, common/src/IO/WalTextureReader.cpp, common/src/IO/WalTextureReader.h
- `Palette::indexedToRgba` now requires a BufferedReader
- TextureBuffer is now a class rather than std::vector, to avoid unnecessary memory zeroing
- Time for `loadTextureCollection` of Makkon2.wad (50MB) reduced from 1355ms -> 95ms (msvc2019, RelWithDebInfo build)
- Palette now limited to 256 color RGB (768 byte) palettes, clarified exceptions docs
Fixes #3510
=> 3510: optimize Palette::indexedToRgba

common/src/IO/MapReader.h, common/src/IO/NodeReader.cpp, common/src/IO/NodeReader.h, common/src/View/MapDocument.cpp, common/test/src/Model/BrushFaceTest.cpp
The root bug was m_game->parseNodes was not throwing when parsing failed so we would never even try to parse as faces.
Fixes #3516
=> 3516: fix copy/paste of faces

common/src/Model/TexCoordSystem.cpp
This fixes face textures being moved in opposite-to-expected direction when corresponding texture scale was negative.
=> "Move Textures" action: take negative texture scale into account when generating texture offsets.

common/src/IO/NodeReader.cpp, common/src/IO/NodeReader.h, common/src/Model/GameImpl.cpp, common/test/src/Model/BrushFaceTest.cpp, common/test/src/Model/BrushNodeTest.cpp, common/test/src/Model/BrushTest.cpp, common/test/src/Model/TestGame.cpp
Fixes #3535
This is a good example of the problem with exceptions..
The underlying bug was in the way `NodeReader::read`/`NodeReader::readAsFormat` tried to reuse the NodeReader for multiple parse attempts. What would happen is `MapReader::m_brushParent` would get set to point at some node (the Group, I think) during a parse attempt. The parsing would fail, an exception would be thrown and caught in `NodeReader::readAsFormat`. The `m_brushParent` would be left as a dangling pointer when `NodeReader::readAsFormat` deletes the currently parsed nodes, then it would be accessed on a subsequent parse attempt and crash.
=> 3535: don't reuse NodeReader after parsing fails

common/src/Renderer/PointHandleRenderer.cpp
**PointHandleRenderer::doRender()**: in 2D views, render handles fully opaque without depth test (renders handles / highlights once instead of twice, makes center handle of rotation tool more visible when rendered on top of an entity).
**PointHandleRenderer::renderHandles()**: nudge handle toward camera in 3D mode only (not needed in 2D, fixes issue #3477).
=> Cosmetic tweaks to handles/highlights rendering

cmake/launch-c.in, cmake/launch-cxx.in
When using ccache under macOS or Linux, we generate scripts that launch
the system compilers. This is due to a limitiation in Xcode's build system
that prevents it from using ccache, but we apply this to all generators on
macOS and Linux anyway.
The scripts contain a syntax error that prevents them from working on Linux.
=> Fix compiler launch scripts

common/src/EL/Expression.cpp, common/src/EL/Value.cpp, common/src/IO/MapReader.cpp, common/src/Model/Brush.cpp, common/src/Model/BrushBuilder.cpp, common/src/Model/BrushNode.cpp, common/src/Model/BrushSnapshot.cpp, common/src/Model/EntityNode.cpp, common/src/Model/GameImpl.cpp, common/src/Model/GroupSnapshot.cpp, common/src/Model/Snapshot.cpp, common/src/Model/TransformObjectVisitor.cpp, common/src/PreferenceManager.cpp, common/src/View/CreateComplexBrushTool.cpp, common/src/View/CreateSimpleBrushTool.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapView2D.cpp, common/src/View/VertexToolBase.h, common/test/src/Model/BrushTest.cpp, common/test/src/PreferencesTest.cpp, common/test/src/View/InputEventTest.cpp, lib/kdl/include/kdl/overload.h, lib/kdl/include/kdl/result.h, lib/kdl/include/kdl/result_combine.h, lib/kdl/include/kdl/result_io.h, lib/kdl/test/src/result_test.cpp
The previous, deduction guide-based approach exposes a bug in MSVC when
the resulting overload instance is captured in a variable. So we use an
alternative implementation that uses a function to construct the
overloaded struct.
See https://developercommunity2.visualstudio.com/t/Capturing-lambdas-in-function-object-res/475396?entry=problem&dialog=comment&viewtype=all
=> 3523: Work around kdl::overload bug in MSVC

common/src/View/TextureBrowser.cpp
=> 3554: clear texture filter when revealTexture() is used

common/src/Model/CompilationProfile.cpp, common/src/Model/CompilationProfile.h, common/src/View/CompilationProfileEditor.cpp, common/src/View/CompilationProfileEditor.h, common/src/View/CompilationTaskListBox.cpp, common/src/View/CompilationTaskListBox.h
=> 3577: add compilation task context menu with Move Up/Down/Duplicate/Remove

common/src/View/CompilationRunner.cpp
Also log QProcess::ProcessError enum as text.
Fixes #3504
=> 3504: Compilation run: log when working dir doesn't exist

common/src/View/EntityAttributeGrid.cpp, common/src/View/EntityAttributeModel.cpp, common/src/View/EntityAttributeModel.h, common/src/View/EntityAttributeTable.cpp, common/src/View/EntityAttributeTable.h
Qt's `QAbstractItemView::SelectedClicked` has an undesirable delay during which keyboard input is ignored. This removes the delay, so when you click on a selected cell, the editor opens immediately on mouseReleaseEvent.
Fixes #3582
To give more precise instructions for reproducing this e.g. in 2020.2:
- New quake map, Valve format
- Select the starting brush
- Select the Valve cell for the "light" worldspawn key
- Wait a second or more
- Click on the selected cell again
- wait 200ms or so (but not long enough that the cell editor opens)
- then type "2", the selection cursor will navigate to the "mapversion 220" value cell, causing the 2 you typed to be lost.
With this PR, the cell editor will open immediately at the point when I wrote "wait 200ms" above.
=> 3582: Implement our own QAbstractItemView::SelectedClicked edit trigger 

common/src/Model/NodeCollection.cpp, common/src/Model/NodeVisitor.h, common/test/src/View/MapDocumentTest.cpp
Add test. Add static assertion to catch the bug.
Fixes #3592
=> 3592: fix NodeCollection::hasBrushesRecursively() and brushesRecursively()

common/src/View/MapView3D.cpp
The addPoint() function in the old code doesn't actually use the camera position: see: https://github.com/TrenchBroom/TrenchBroom/commit/4831ba7a0aff96d862ea7215273eb3f31615075c
Fixes #3590
=> 3590: fix "focus on selection" command

common/src/Model/GroupNode.cpp, common/src/Model/GroupNode.h, common/src/Model/ModelUtils.cpp, common/test/src/View/MapDocumentTest.cpp
Fixes #3589
First I factored out the `!(group->opened() || group->hasOpenedDescendant())` condition to be `group->closed()` for readability.
Note that I have to both check for a non-empty optional, and check that the contained `GroupNode*` is non-null.
=> 3589: fix findOutermostClosedGroup

app/resources/documentation/manual/index.md, common/src/PreferenceManager.cpp, common/src/Preferences.h, common/src/View/CameraTool3D.cpp, common/src/View/CameraTool3D.h, common/src/View/MousePreferencePane.cpp
Closes #2251. This is an alternative implementation (see #3587) to allow easier control over fly move speed in the 3D view. This implementation allows the user to turn the mouse wheel while holding the right mouse button in the 3D view to adjust movement speed on the fly.
=> 2251: Make fly speed adjustable with the scroll wheel

app/resources/games/Quake2/Quake2.fgd
Closes #3071. Added base class for Angle and made func_door and func_door_secret use it. 
The issue also mentioned Heretic2 missing this key, but looks like that was already fixed via c2a9b4fd34acd17acded9af94367768e6dde3435
=> 3071: Adding 'angle' key for Quake2 func_door / func_door_secret

app/CMakeLists.txt
Fixes #3608
I've tested building the `TrenchBroom` target works in Xcode, and does generate the manual in the correct place.
=> 3608: fix Xcode new build system

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/BrushNode.cpp, common/src/Model/BrushNode.h, common/src/Model/EntityNode.cpp, common/src/Model/EntityNode.h, common/src/Model/GroupNode.cpp, common/src/Model/GroupNode.h, common/src/Model/Object.cpp, common/src/Model/Object.h, common/src/View/ClipTool.cpp, common/src/View/MapDocument.cpp, common/src/View/ResizeBrushesTool.cpp, common/test/src/Model/BrushFaceTest.cpp, common/test/src/Model/BrushTest.cpp, common/test/src/View/MapDocumentTest.cpp, common/test/src/View/RepeatableActionsTest.cpp, common/test/src/View/SwapNodeContentsCommandTest.cpp
Closes #3006 
A while back, I changed all functions that modify a brush to return a new copy of it. The idea was to prevent brushes from going into an invalid state when an operation fails. But now this is no longer important since we always modify node contents after creating a copy, and only if the operation succeeds, do we move the copy back into the node. And since it's easier to avoid unnecessary copies when modifying objects in place, I decided to undo the previous change here. Furthermore, `Entity` already modifies itself in place, so this PR makes the two classes behave consistently in this regard.
=> 3611: Make brush modifications in place

common/src/View/EntityAttributeModel.cpp
=> 3633: fix "no previous prototype" warnings in EntityAttributeModel.cpp

common/src/IO/MapReader.cpp, common/src/IO/NodeSerializer.cpp, common/src/IO/NodeSerializer.h, common/src/Model/GroupNode.cpp, common/src/Model/GroupNode.h, common/src/Model/LayerNode.cpp, common/src/Model/LayerNode.h, common/src/Model/WorldNode.cpp, common/src/Model/WorldNode.h, common/test/CMakeLists.txt, common/test/src/IO/NodeWriterTest.cpp, common/test/src/IO/WorldReaderTest.cpp, common/test/src/Model/WorldNodeTest.cpp
Closes #2607.
Previously, layer and group IDs would be regenerated for every save, with the consequence of the numbers potentially changing unnecessarily, which produces diff noise. This PR keeps the numbers persistent.
=> 2607: Keep layer and group IDs persistent

common/src/Color.cpp, common/src/Color.h, common/src/IO/EntParser.cpp, common/src/IO/GameConfigParser.cpp, common/src/IO/WorldReader.cpp, common/src/Model/Entity.cpp, common/src/Model/EntityRotationPolicy.cpp, common/src/Model/PointFile.cpp, common/src/PreferenceManager.cpp, common/src/View/FaceAttribsEditor.cpp, common/src/View/MapFrame.cpp, common/src/View/MapInspector.cpp, common/src/View/MoveObjectsToolPage.cpp, common/src/View/RotateObjectsToolPage.cpp, common/src/View/ScaleObjectsToolPage.cpp, common/src/View/ScaleObjectsToolPage.h
vm::parse now returns an optional and the can_parse function was removed.
I made this change because I need to write a similar parse function for matrices, and I don't want to deal with can_parse and such.
=> Update to latest vecmath and adapt to changes to vec parse function

common/src/Preferences.cpp, common/src/Preferences.h, common/src/View/CellView.cpp, common/src/View/MapViewBase.cpp, common/src/View/UVView.cpp, common/src/View/ViewPreferencePane.cpp, common/src/View/ViewPreferencePane.h
Implemented #3675.
Change of this setting does not require restarting the app because the GL_MULTISAMPLE option is being set before rendering each frame at ::setupGL.
<details>
<summary>GIF demonstration</summary>
</details>
=> 3675: Configurable Antialiasing

Build.md
=> 3679: Add libqt5svg5-dev to list of debian dependencies

common/src/IO/MapReader.cpp, common/src/Model/Brush.cpp, common/src/Model/BrushBuilder.cpp, common/src/Model/BrushFace.cpp, common/src/PreferenceManager.cpp, common/src/View/ClipTool.cpp, common/src/View/CreateComplexBrushTool.cpp, common/src/View/CreateSimpleBrushTool.cpp, common/src/View/MapDocument.cpp, common/src/View/ResizeBrushesTool.cpp, common/src/View/VertexToolBase.h, common/test/src/Model/BrushFaceTest.cpp, lib/kdl/CMakeLists.txt, lib/kdl/include/kdl/meta_utils.h, lib/kdl/include/kdl/result.h, lib/kdl/include/kdl/result_combine.h, lib/kdl/include/kdl/result_for_each.h, lib/kdl/test/src/result_test.cpp
This PR makes a couple of changes to reduce the amount of typing necessary when using the `kdl::result` type. See the first commit's description for more details.
=> Remove result factories

common/src/View/Actions.cpp
=> 3685: make "Reset texture alignment" work with brushes, and add default shortcuts

common/src/View/MapDocument.cpp, common/test/src/View/MapDocumentTest.cpp
Fixes #3691
Bug was introduced in 6f14f07
The previous code in `MapDocumentCommandFacade::performUpdateSpawnflag` was using `allSelectedAttributableNodes()` to get this list of entities to update, which got lost in the refactor
=> 3691: fix setting spawnflags on brush entities 

.github/workflows/ci.yml
Fixes #2210
For the first pass of this I'm just deploying the Linux manual (iirc it's identical, or almost, to the Windows one).
The idea is, when doing the CI build for a tag, we push the compiled manual to: https://github.com/TrenchBroom/manual/tree/gh-pages/latest
which is visible here: https://trenchbroom.github.io/manual/latest/
I made the pull request before adding the "tag" condition, which is why it deployed the initial copy of the manual there.
=> 2210: Initial setup to deploy manual

common/src/View/ClipToolController.cpp, common/src/View/EntityDefinitionFileChooser.cpp, common/src/View/LayerEditor.cpp, common/src/View/MapDocument.cpp
Previously, it:
- incorrectly committed a undo/redo transaction
- didn't actually reload entity definitions
Fixes #3703
=> 3703: Fix "Reload" entity definitions button

common/src/View/SetBrushFaceAttributesTool.cpp
Closes #3548.
This was an error introduced during a refactoring.
=> 3548: Correctly check source and target drag face handles

common/src/Renderer/Camera.cpp, common/src/Renderer/Camera.h, common/src/View/InputEvent.cpp, common/src/View/InputEvent.h, common/src/View/InputState.cpp, common/src/View/InputState.h, common/src/View/MapView2D.cpp, common/src/View/MapView2D.h, common/src/View/MapView3D.cpp, common/src/View/MapView3D.h, common/src/View/MapViewBase.cpp, common/src/View/RenderView.cpp, common/src/View/ToolBoxConnector.cpp, common/src/View/ToolBoxConnector.h, common/src/View/UVView.cpp, common/src/View/UVView.h, common/test/src/View/ClipToolControllerTest.cpp, common/test/src/View/InputEventTest.cpp
Closes #3561.
This improves precision on some platforms, and makes mouse input feel
less jagged depending on the input device and preferences.
=> 3561: Use double for mouse coordinates

common/src/Model/Brush.cpp, common/test/src/Model/BrushTest.cpp
Closes #3443.
This was mostly an oversight and it's easy to fix so that CSG subtract will clone face attributes for all newly created faces.
=> 3443: Clone face attributes from subtrahends after CSG subtract

common/src/IO/MapFileSerializer.cpp, common/src/IO/StandardMapParser.cpp, common/src/IO/StandardMapParser.h, common/src/IO/Tokenizer.h, common/test/src/IO/NodeWriterTest.cpp, common/test/src/IO/WorldReaderTest.cpp
Closes #3361.
This PR fixes and improves support for reading quoted texture names, and adds support for quoting texture names if necessary when writing map files.
=> 3361: Improve support for quoted texture names in map files

app/resources/documentation/manual/index.md, app/resources/games/Quake3/GameConfig.cfg, common/src/IO/GameConfigParser.cpp, common/src/Model/GameConfig.cpp, common/src/Model/GameConfig.h, common/src/View/GamesPreferencePane.cpp
Closes #3716.
Although other game configs could undoubtedly use compilation tools, and the current Quake config (which has tools) might benefit from tooltips... I only modified the Quake 3 config in this change.
I also adjusted the tool names in the example game config in the manual slightly, since it is supposed to be something resembling Quake 2 (even though the real Q2 config doesn't have compilation tools yet).
=> 3716: Quake 3 compilation tools, including tooltips

common/src/Model/Polyhedron_ConvexHull.h, common/test/src/Model/PolyhedronTest.cpp
Closes #3644
Adding a point to a polygon can fail if all incident faces of the newly
added vertex are coplanar. In this case, the point cannot be added and
the polyhedron remains a polygon.
=> 3644: Fix error when adding a point to a polygon fails

common/CMakeLists.txt, common/src/Uuid.cpp, common/src/Uuid.h, common/test/src/IO/TestEnvironment.cpp
Closes #3722.
Tests that use the file system all rely on TestEnvironment and therefore
depend on the state of the file system. To isolate these tests from each
other, we create a unique directory for each test environment using a
UUID. This allows these tests to be executed in parallel.
=> 3722: Use unique directory for TestEnvironment

app/src/Main.cpp
Fixes #3734
Screenshot of Windows set to 150% with this PR. Without the PR everything is too large.
=> 3734: opt into fractional dpi scaling, so Windows at 150% works

common/src/View/CollapsibleTitledPanel.cpp, common/src/View/CollapsibleTitledPanel.h, common/src/View/EntityInspector.cpp, common/src/View/EntityInspector.h, common/src/View/FaceInspector.cpp, common/src/View/FaceInspector.h, common/src/View/MapInspector.cpp, common/src/View/MapInspector.h
Closes #3701
To make the inspector panels such as the map properties or the texture collections easier to discover, we want them to be expanded by default. Once discovered, they should retain their state, so we add support for saving the window state to `CollapsibleTitledPanel`.
=> 3701: Expand inspector panels by default

app/src/Main.cpp, common/benchmark/src/Main.cpp, common/src/PreferenceManager.cpp, common/src/PreferenceManager.h, common/test/CMakeLists.txt, common/test/src/IO/TestEnvironment.cpp, common/test/src/IO/TestEnvironment.h, common/test/src/RunAllTests.cpp, common/test/src/TestPreferenceManager.cpp, common/test/src/TestPreferenceManager.h, dump-shortcuts/src/Main.cpp
Closes #3732.
This PR introduces a refactoring of `PreferenceManager` that allows us to create a `TestPreferenceManager`, which doesn't access user preferences and is read only. This also speeds up test runs because it doesn't trigger any preference migrations or instantiates actions.
=> 3732: Run tests with sandboxed preferences

common/src/View/Actions.cpp, common/src/View/MapFrame.cpp
1. Move the menu item down:
2. Make "Cancel" the default button. Pressing Space or Enter (or Escape) all dismiss the dialog. You can accept the revert with Tab then Space, though.
Fixes #3746
=> 3746: make Revert command less prone to accidental activation

CMakeLists.txt, app/CMakeLists.txt
These are just two small changes I made while trying to get rid of linker warnings. The first warning I fixed was about my Qt version being built for a later macOS version that what we are linking for. This one has to do with my installation, but while working on it I changed how we find Qt5 to use components. The end result is identical, it's just one less line.
The other change relates to .obj files in our game configs. On macOS, these files must be added as source files in order to set their macOS bundle location. The linker would try to link these .obj files and would fail because they are not binary images, but wavefront files. Setting these files to have the `HEADER_FILE_ONLY` property tells the linker to ignore them.
=> CMake cleanups

common/src/Model/Brush.cpp, common/src/Model/Brush.h, common/src/Model/BrushFace.cpp, common/src/Model/BrushFace.h, common/src/Model/CompareHits.cpp, common/src/Model/EntityNode.cpp, common/src/Model/EntityNode.h, common/src/View/MapDocument.cpp, common/src/View/ResizeBrushesTool.cpp, common/test/src/Model/EntityNodeTest.cpp
Fixes #3725
I've reworked https://github.com/TrenchBroom/TrenchBroom/pull/3745 with a new heuristic and bug fixes:
- If the output face has any coplanar faces in the source brushes, use the largest area one.
- Otherwise take the face from the source brushes whose center point is closest to the output face plane.
=> 3725: transfer attributes after csg merge

common/src/View/MapDocument.cpp, common/test/src/View/SetEntityPropertiesTest.cpp
Closes #3757
After setting some properties to unprotected, we need to update linked
nodes because in some situations, setting a property to unprotected can
lead to it being replicated into the corresponding entities in linked
groups. Suppose we have two linked groups, each containing an entity.
One of the entities has some protected property that the other doesn't.
In this case, when the protected property is set to unprotected, it must
be replicated into the corresponding entity.
=> 3757: Update linked group nodes after setting properties to unprotected

common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/test/src/View/GroupNodesTest.cpp
Closes #3762
The code that separates linked groups did not handle cases where
multiple members of a link set are separated and not relinked again,
which lead to groups getting deleted when ungrouped. This commit
contains a fix for MapDocument::separateLinkedGroups that also repairs
this bug.
=> 3762: Fix ungrouping several members of a link set

common/src/View/EntityPropertyGrid.cpp
Closes #3766.
This PR simply swaps the regular button to add an entity property and the new button to add a protected entity property.
=> 3766: Swap add property buttons

.github/workflows/ci.yml, cmake/Utils.cmake, common/src/View/AppInfoPanel.cpp
Adjust GET_GIT_DESCRIBE macro behaviour:
- If "git describe" fails (e.g. because it's a shallow clone, from GitHub Actions building a PR or a commit on `master`), try to use GITHUB_SHA and GITHUB_REF to construct a replacement version string (see: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables )
- The version string is `{GITHUB_REF}-{GITHUB_SHA}`, with forward slashes replaced with underscores (so the package filename will be valid)
- Behavior should be unchanged for building release tags
Also make it non-fatal if the version description isn't in the v0000.0 format (it won't be for the GitHub Actions master branch / PR cases).
--- 
The Windows build for this PR gets the following package name: 
- …
=> 3023: give Github Actions PR and master branch builds descriptive version names

common/src/View/MapViewBase.cpp
Closes #3767
This context menu entry did not show up because the code that builds the menu
was using an outdated menu entry path.
=> 3767: Restore context menu entry for "Separate Linked Groups"

common/src/Model/BrushNode.cpp, common/src/Model/BrushNode.h, common/test/src/Model/BrushNodeTest.cpp
Closes #3761
When a new brush node is created, we need to deselect the faces of the brush passed into the constructor to avoid consistency errors. Likewise, when a brush is cloned, the clone should not have any selected faces.
I have decided not to add an enum to the `BrushNode` constructor or `BrushNode::setBrush`. I checked all call sites and it turns out that we always want to reset the face selection when creating / cloning a brush node, and we always want to retain the face selection when calling `BrushNode::setBrush`, so I suppose this error naturally doesn't happen after all. The bug was that we didn't reset the face selection in the constructor, which we now do.
=> 3761: Deselect brush faces when creating a new brush node

common/src/View/EntityPropertyModel.cpp
=> 3783: protect renaming classname value

common/src/View/MapDocumentCommandFacade.cpp
UpdateLinkedGroupsHelper calls this with an empty vector of nodes to
replace. Adding the early exit fixes a performance bottleneck with
dragging 1 brush on a large map with no linked groups.
Fixes #3785
=> 3785: exit early in performReplaceChildren() if given empty vector

common/src/View/MapDocument.cpp, common/test/src/View/MapDocumentTest.cpp
=> 3784: lock textures when transforming brushes in linked group

common/src/View/EntityPropertyGrid.cpp, common/src/View/EntityPropertyModel.cpp, common/src/View/EntityPropertyModel.h
Fixes #3789
Aside from the `getCompletions` being wrong, these were also wrong: `const QModelIndex bottomRight = index(static_cast<int>(*oldIndex), 1);` (might have caused the "value" column to not be updated under some circumstances).
=> 3789: EntityPropertyGrid: use symbolic column indices, fix some wrong ones

common/src/Model/PointFile.cpp
If the first two vertices of a pointfile are identical (as some compilers output), the current implementation will only show the first vertex and disregard the whole rest of the file.
This is because the program attempts to normalize the (null) vector connecting the first two vertices and generates a NaN, which then results in no further vertices being picked up.
This pull request explicitly guards against this by cycling until a genuinely different vertex is found.
=> Correctly render pointfiles with duplicate vertices

common/benchmark/CMakeLists.txt, common/test/CMakeLists.txt, dump-shortcuts/CMakeLists.txt
AUTOMOC on the "common" target was not propagating to the tools that depend on it?
Fixes #3797
=> 3797: work around link errors with cmake 3.20.0

common/src/View/ControlListBox.cpp, common/src/View/LayerListBox.cpp, common/src/View/LayerListBox.h
Addresses the biggest slowdown noticed in #3800 ... IMO we can leave that open because we might want to still do a better underlying fix.
Here are some benchmarks:
- The test conditions are: resize-perf.map posted in #3800 , resizing the brush in the .gif there.
- current master ( 523e5e55dc52c799bb5e7b4d48e333da0e673543 ): win64 build from CI
- Average FPS: 23-27
- this PR (TrenchBroom-Win64-unstable-refs_pull_3807_merge-beb4214fb588aefe4e6a797b3de06510fc1627ed-Release)
- Average FPS: 164
=> 3800: optimize layer list UI updates

common/src/Model/EntityNode.cpp, common/test/src/Model/EntityNodeTest.cpp
Closes #3775.
This was just a typo, but a bad one. When Entity::pointEntity is not set correctly, transforming a brush entity can add an origin property.
=> 3775: Correctly set Entity::pointEntity when removing last child node

common/src/View/MapFrame.cpp, common/src/View/MapFrame.h
Closes #3774.
@ericwa could you please give this a brief testing in Windows? I currently don't have access to a Windows machine where TB runs.
=> 3774: Close compile dialog when creating or opening a document

common/src/View/VertexToolBase.h
Closes #3688.
This fixes the problem, but I wonder if we shouldn't disable this particular interaction while in vertex mode.
=> 3688: Ignore unselected nodes when updating vertex handle manager

common/src/Model/GameImpl.cpp
Fixes #3813
With the fix, I can now export DM3.map (from the quake map source) and load the result in blender again (same as in 2021.1).
=> 3813: Fix .obj export being clobbered by .mtl file

common/src/View/MapDocument.cpp, common/src/View/MapFrame.cpp, common/test/src/View/GroupNodesTest.cpp
The non-group nodes stay selected.
Fixes #3824
=> 3824: allow ungrouping with non-groups selected

common/src/View/MapViewBase.cpp
Fixes #3834
This corrects a bad refactoring in 1a45f8278ef75ad6d3b9dcea62a010a1909dfaf2 where the hit type filtering of pickable() was relied on in these lines.
=> 3834: fix crash when right clicking on a scale tool handle with a group selected

common/CMakeLists.txt, common/src/View/CameraTool2D.h, common/src/View/CameraTool3D.h, common/src/View/ClipToolController.cpp, common/src/View/CreateComplexBrushToolController3D.cpp, common/src/View/CreateEntityToolController.cpp, common/src/View/CreateEntityToolController.h, common/src/View/CreateSimpleBrushToolController2D.h, common/src/View/CreateSimpleBrushToolController3D.h, common/src/View/DropTracker.cpp, common/src/View/DropTracker.h, common/src/View/ResizeBrushesToolController.h, common/src/View/RotateObjectsToolController.cpp, common/src/View/ScaleObjectsToolController.h, common/src/View/SelectionTool.h, common/src/View/SetBrushFaceAttributesTool.h, common/src/View/ShearObjectsToolController.h, common/src/View/ToolBox.cpp, common/src/View/ToolBox.h, common/src/View/ToolChain.cpp, common/src/View/ToolChain.h, common/src/View/ToolController.cpp, common/src/View/ToolController.h, common/src/View/UVCameraTool.h, common/src/View/UVOffsetTool.h, common/src/View/UVOriginTool.h, common/src/View/UVRotateTool.h, common/src/View/UVScaleTool.h, common/src/View/UVShearTool.h, common/src/View/VertexToolControllerBase.h
This small PR replaces TB's current handling for drag and drop with an approach similar to https://github.com/TrenchBroom/TrenchBroom/pull/3823. Since this is really only used by `CreateEntityTool`, the actual change is really small.
=> Introduce drop tracker

common/src/Notifier.h
We need to forward the notifier arguments, but doing so requires a forwarding reference.
=> 3781: Fix notifier forwarding

common/src/IO/MapReader.cpp, common/src/Model/GroupNode.cpp, common/src/Model/NodeVisitor.h, common/src/View/MapDocument.cpp, lib/kdl/include/kdl/parallel.h, lib/kdl/include/kdl/result.h, lib/kdl/test/src/parallel_test.cpp
- Partial fix for #3816 (as I mentioned there, this should be good enough for 2021.2)
- also tossed in parallelization of `MapDocument::transformObjects`. This gives a big speedup when dragging the 512-brush groups in the #3816 test case map, or just moving around large chunks of a map with 100s/1000s of brushes.
- also tossed in a lighter weight `kdl::parallel_for` implementation specific to Windows + a performance test. This isn't really critical to have but I was just curious if it would make a difference.
=> 3816: Parallelize linked group rebuilds, object transforms

common/src/Notifier.h, common/src/NotifierConnection.cpp, common/src/NotifierConnection.h
MapView connects to the notifiers of the tools that are being added via
MapView::addTool. These tools are managed by the subclass MapViewToolBox
and when that is destroyed, so are the tools. When ToolBox is then
destroyed, it disconnects from the tool notifiers it previously
connected to, but at this point, they have already been destroyed.
We add a simple fix by providing a function that disconnects the tool
observers connected in ToolBox and is called by ~MapViewToolBox().
=> 3848: Disconnect tool observers before destroying the tools

common/src/View/MapDocument.cpp
=> 3853: avoid unnecessary Brush copies in MapDocument::transformObjects

Build.md
5.9.9 produces an error at cmake configuration time:
CMake Error:
Error evaluating generator expression:
$<TARGET_FILE:Qt5::QWindowsVistaStylePlugin>
No target "Qt5::QWindowsVistaStylePlugin"
=> Build.md: indicate that Qt 5.12+ is required on Windows.

common/CMakeLists.txt, common/src/Assets/EntityDefinition.cpp, common/src/Assets/EntityDefinition.h, common/src/Assets/EntityDefinitionManager.cpp, common/src/Assets/EntityDefinitionManager.h, common/src/Assets/Texture.cpp, common/src/Assets/Texture.h, common/src/Thread.cpp, common/src/Thread.h, common/src/View/EntityBrowser.cpp, common/src/View/EntityBrowser.h, common/src/View/EntityBrowserView.cpp, common/src/View/EntityBrowserView.h, common/test/src/View/UndoTest.cpp
Fixes #3856
The overall issues here are:
- we want to be able to copy Entity / Brush in background threads
- but when doing so, AssetReference copy constructor calls incUsageCount()/decUsageCount() on Texture/EntityDefinition
- none of the inc/decUsageCount() are threadsafe
- the EntityDefinition inc/decUsageCount() calls a notifier, which triggers a crash.
So as a quick fix, I've made inc/decUsageCount() threadsafe, and removed the entity definition usageCountDidChangeNotifier. This is just used to rebuild the entity browser for the purposes of sorting by usage, or showing only used entities. Now it invalidates the browser on every node change, but I'm not seeing any noticeable performance impact from this.
For future work: having AssetReference in Entity/Brush etc. update these usage …
=> 3856: Threading issue in MapDocument::transformObjects with NodeContents

common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/MapFrame.cpp
Fixes #3862
There were multiple bugs here:
- MapFrame not calling updateUndoRedoActions() when necessary
- m_commandProcessor->clear() was being called in response to
documentWasLoadedNotifier/documentWasNewedNotifier, which was too late.
=> 3862: fix updating Undo/Redo menu items when a document is newed/loaded

app/resources/games/Halflife/GameConfig.cfg
Non-Valve-extended format MAP files are used for Half-Life in some circumstances. Obviously the better option for actual work on a map is usually conversion to the Valve-extended format, but that's not always an option especially as then you need a program to do the conversion, and... well... even if TrenchBroom had an option for it, without the format option, it wouldn't happen anyway.
=> Add Standard format option for Half-Life maps

common/src/Model/BrushNode.cpp, common/src/Model/EntityNodeBase.cpp, common/src/Model/EntityNodeBase.h, common/src/Model/ModelUtils.cpp, common/src/Model/ModelUtils.h, common/src/Model/Node.cpp, common/src/Model/Node.h, common/src/Model/NodeCollection.cpp, common/src/Model/NodeCollection.h, common/src/Model/PatchNode.cpp, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/MapFrame.cpp, common/test/src/Model/ModelUtilsTest.cpp, common/test/src/Model/NodeCollectionTest.cpp, common/test/src/TestUtils.cpp, common/test/src/TestUtils.h, common/test/src/View/GroupNodesTest.cpp, common/test/src/View/MapDocumentTest.cpp, common/test/src/View/UpdateLinkedGroupsHelperTest.cpp
Fixes #3768
This evolved a bit from what I was originally thinking, and now only affects face selections.
The last commit has all of the real changes, I'll just repeat the commit message here:
- `MapDocument::allSelectedBrushFaces()`: if multiple groups in a link set are selected, only return one representative face per link set so that user actions can be performed without generating conflicts. (e.g. this allows selecting 2 closed linked groups in a link set and applying textures.)
- `MapDocumentCommandFacade::performSelect(const std::vector<Model::BrushFaceHandle>&)`: "fix up" face selections (if faces in multiple closed groups are attempted to be selected, only select one representative face per link set). Also implicitly lock/unlock other groups in the link set.
You can experiment …
=> 3768: Prevent face actions from being blocked in maps with linked groups

common/benchmark/src/Renderer/BrushRendererBenchmark.cpp, common/src/Renderer/BrushRenderer.cpp, common/src/Renderer/BrushRenderer.h, common/src/Renderer/EntityModelRenderer.cpp, common/src/Renderer/EntityModelRenderer.h, common/src/Renderer/EntityRenderer.cpp, common/src/Renderer/EntityRenderer.h, common/src/Renderer/GroupRenderer.cpp, common/src/Renderer/GroupRenderer.h, common/src/Renderer/MapRenderer.cpp, common/src/Renderer/MapRenderer.h, common/src/Renderer/ObjectRenderer.cpp, common/src/Renderer/ObjectRenderer.h, common/src/Renderer/PatchRenderer.cpp, common/src/Renderer/PatchRenderer.h, common/src/View/ClipTool.cpp, common/src/View/CreateBrushToolBase.cpp, common/src/View/MapDocumentCommandFacade.cpp
Partial fix for https://github.com/TrenchBroom/TrenchBroom/issues/3822
The main bottleneck in #3822 was an unnecessary renderer invalidation on all brushes. The MapRenderer notification handlers mostly ignored the "changed nodes" arguments, as a result, whether or not a given MapDocument change hits a fast path or slow path was unpredictable.
So the change summary here is:
- all MapRenderer notification handlers now use the provided nodes instead of ignoring them. (This means we could hit bugs we weren't catching before, but the notification arguments seem to be accurate in my testing.) The update/invalidate code in MapRenderer is reworked and it makes all changes on a node granularity. This avoids surprises where before, hiding or showing 1 node would cause a hitch, invalidating the …
=> 3822: rework MapRenderer notification handling to only invalidate necessary nodes

app/resources/documentation/manual/index.md
I ran the whole manual through the LibreOffice spellchecker, English (USA). This should correct the most obvious typos.
Because English is not my native language there are still some words left I was not sure about:
- cancelling
This seems to be more common in British English but the rest of the manual is written in American English (USA).
- spacially
Maybe this is an example of bad grammar.
- seldomly
Maybe this is an example of bad grammar as well.
- arrays's
I am pretty sure this word is wrong. I just do not know if the word should be genitive singular or genitive plural.
There will be probably some more typos left in the manual but this should correct those which can be easily found with a spellchecker.
=> Fixing several typos in the manual

CMakeLists.txt
This change fixes a lot of build warnings on macOS.
=> Set macOS deployment target

app/resources/games/Neverball/GameConfig.cfg
Someone changed the name of the OBJ backend, ignoring the Neverball-specific logic nature of it.
But whatever, using that transform with a 64-unit divisor seems common enough.
Still, the GameConfig needs to be updated.
(I'm also not sure what's up with Generic's model format list.)
=> Fix Neverball GameConfig obj backend reference

common/src/IO/Path.cpp, common/test/src/IO/PathTest.cpp
=> 3897: Don't crash when deleting the extension of an empty path

common/src/Model/Polyhedron_Misc.h, common/test/src/Model/BrushRegressionTest.cpp
Closes #3886.
The previous algorithm tried to be smart about removing invalid (short) edges by not restarting the search when a short edge was removed. We change it so that it starts over, which is less prone to errors in cases where more than the short edge itself is removed. This avoids an assertion at the cost of more work when edges are removed.
=> 3886: Make edge healing more robust

common/src/Model/EntityRotationPolicy.cpp, common/src/Model/EntityRotationPolicy.h, common/test/src/Model/EntityRotationPolicyTest.cpp
Closes #3827.
The rotation of an entity should be determined by its entity properties, but in absence of such properties, we must inspect the property definitions instead. The effect is that users can apply rotations to entities that don't have corresponding entity properties such as "angles" can still be rotated without adding such a property if the entity has a property definition for an "angles" property.
=> 3827: Check for property definitions when determining the rotation info

CI-macos.sh, CMakeLists.txt
=> 3989: Set CMAKE_OSX_DEPLOYMENT_TARGET only when building on CI

common/src/Model/Entity.cpp, common/src/View/MapDocument.cpp, common/test/src/View/TransformNodesTest.cpp
Closes #3986.
When transforming all brushes of a brush entity, we now update the entities' rotation properties, e.g. "angle", if present (or defined via an entity definition). This does not apply if some, but not all brushes of the entity are rotated.
=> 3986: Update angle of brush entity when it is transformed while all children are selected

CMakeLists.txt, common/CMakeLists.txt, common/test/CMakeLists.txt, lib/kdl/CMakeLists.txt
Closes #3992
Setting CMAKE_CXX_STANDARD globally sets the default and lets cmake choose whatever flags are appropriate for us.
=> 3992: Set C++ standard version

common/src/View/EntityBrowserView.cpp, common/src/View/EntityBrowserView.h
Closes #4007.
First we revert #3978 because it turns out we do want to apply model scale in the browser. The original problem wasn't the scale per se, but that we failed to correctly scale down models if they were too large to fit a cell of the browser view. This PR fixes the problem by considering the model scale when computing the scale factor for the browser cells.
=> 4007: Scale entity models in browser

Build.md
On Linux, we must pass DCMAKE_PREFIX_PATH to cmake so that it can find our config scripts for some external libraries.
=> 4002: Update build instructions for Linux

common/src/Model/NodeCollection.cpp, common/src/Model/NodeCollection.h, common/src/View/SelectionTool.cpp, common/src/View/SelectionTool.h, common/test/CMakeLists.txt, common/test/src/View/SelectionToolTest.cpp
Closes #4023.
If a face is hidden via a tag, it should not be possible to select the owning brush by click the selected face. This PR fixes this behavior by filtering out hits on brush nodes where the hit face is invisible.
=> 4023: Disallow selection via hidden face

common/src/Assets/EntityModel.cpp
=> 4025: Retain the skin index when loading an entity frame

common/src/Model/EntityRotation.cpp, common/test/src/Model/EntityRotationTest.cpp
Closes #4033
When determining the rotation type, we look at both the actual entity
properties and the entity property definitions from the FGD file with
equal priorities. This commit changes this behavior to prefer the actual
properties over the property definitions so that entities with more than
one defined angle-related properties (e.g. misc_model for Quake 3, which
has both a defined angle and a defined angles property) are still
displayed correctly. Before this change, the definition for the angles
property would override an actual angle property and so the entity
rotation would be computed wrongly.
=> 4033: Prefer entity properties over definitions when determining rotation type

CMakeLists.txt
This change sets some Cmake properties that result in the default visibility of non-public symbols to be hidden. This is important to fix warnings on macOS about inconsistent symbol visibility when linking to some libraries built by vcpkg.
=> Set default visiblity to hidden

.github/workflows/ci.yml
This hopefully fixes the problem that every CI run tries to upload release builds.
=> Put all conditions for uploading releases in one line

common/src/IO/FgdParser.cpp
Part of the work required for #1140
Won't work for HL format sprites until #3938 has been merged
Both `sprite` and `iconsprite` are used in Half-Life FGDs to indicate a sprite model, this change simply adds them to the list.
=> 1140: Add sprite and iconsprite as model fgd header properties

vcpkg.json
This removes a dependency on irrlich and thus enables building TB on arm again.
=> Upgrade to assimp 5.2.4

common/src/Assets/Palette.cpp, common/src/IO/SprParser.cpp
Part of the work required for #1140
The Half-Life sprite format is very similar to the Quake format - the two differences are:
- Render mode added to sprite header
- Palette data embedded after sprite header
The render mode has 4 options which change the behaviour of the alpha channel. This allows sprites to have an 8-bit alpha channel at the expense of RGB data. Since this logic is specific to sprites, the processing code does not need to be abstracted away for re-use, so the conversion to an RGBA palette is done inside the SPR parser. In order to load a 1024 byte RGBA palette without it altering the alpha channel I have also made a small change to the Palette class.
Please let me know if I have done anything wrong or broken any style guidelines - I am not very familiar with C++.
--- …
=> 1140: Add support for Goldsource (Half-Life) Sprite format

app/CMakeLists.txt, app/resources/linux/trenchbroom.desktop, app/resources/linux/trenchbroom.xml
- Adds a new `text/x-quakemap` MIME type definition with a shared mime info file.
- Updates the `Exec` line in the desktop file so that TrenchBroom is listed in the "Open with" application list.
- Adds `MimeType` line to desktop file to associate TrenchBroom with `text/x-quakemap` files.
In my test the built package has the new XML file in the correct location:
=> Improve Linux desktop integration

common/src/View/AddRemoveNodesCommand.cpp, common/src/View/AddRemoveNodesCommand.h, common/src/View/BrushVertexCommands.cpp, common/src/View/BrushVertexCommands.h, common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/src/View/MapDocumentCommandFacade.cpp, common/src/View/MapDocumentCommandFacade.h, common/src/View/ReparentNodesCommand.cpp, common/src/View/ReparentNodesCommand.h, common/src/View/SwapNodeContentsCommand.cpp, common/src/View/SwapNodeContentsCommand.h, common/src/View/UpdateLinkedGroupsHelper.cpp, common/src/View/UpdateLinkedGroupsHelper.h, common/test/src/View/UpdateLinkedGroupsHelperTest.cpp
Instead of fully computing linked group updates immediately, we just collect the linked groups that have changes that need to be replicated to their link sets. This makes it a bit easier to implement later changes to this mechanism.
=> Simplify linked group updates

common/src/View/BrushVertexCommands.cpp, common/src/View/Command.cpp, common/src/View/Command.h, common/src/View/CommandProcessor.cpp, common/src/View/UndoableCommand.cpp, common/src/View/UndoableCommand.h, common/test/src/View/CommandProcessorTest.cpp
This change allows transactions to be collated if the last command of the preceeding transaction and the first command of the succeeding transaction can be collated.
=> Collate transactions

.github/workflows/ci.yml, cmake/Utils.cmake
The macos-10.15 runner image is being removed, so we need to update to macos-11.
=> Use macos-11 image for github actions

common/src/EL/Expressions.cpp, common/src/IO/DefParser.cpp, common/src/IO/EntParser.cpp, common/src/IO/FgdParser.cpp, common/test/src/EL/ExpressionTest.cpp
Closes #4094.
The operators `&&`, `||`, `->` should only evaluate the right hand side if that is necessary to evaluate the entire operator. If the left hand side already determined the outcome, then the right hand side should not be evaluated. This makes it possible to guard expressions from left to right, e.g. `model != null && model[0]` should only evaluate the right hand side if the `model` variable is not null.
=> 4094: Fix short circuit evaluation for logical and case operators

common/src/IO/FgdParser.cpp, common/test/src/IO/FgdParserTest.cpp
This PR fixes the following corner case when parsing FGDs:
```
@PointClass unknownprop base(Targetname) = my_entity : 
```
In the above example, `unknownprop` is not recognised by TrenchBroom, so `FgdParser::skipClassProperty()` is called to skip any parentheses. However, since the `unknownprop` token has already been consumed and no parentheses are present, the token `base` is encountered and skipped, and then the function exits since the parentheses depth is 0. Parsing subsequently fails since the parenthesis that is read next is unexpected.
This was a corner case I encountered when parsing Source FGDs on my own branch. Many of the modifications I had to make to the parsing code at large aren't relevant to TrenchBroom, but I think this one might be if it's possible to specify class …
=> Fix for parsing unrecognised FGD class properties

common/src/View/CompilationVariables.cpp, common/test/src/View/CompilationRunnerTest.cpp
Closes #4010 .
This makes the code align with the documented behavior.
All this change does is bump MAP_DIR_PATH up in the "hierarchy" of variables, taking it out of CompilationWorkDirVariables and into its parent class CommonCompilationVariables which is used both for workdir and tool interpolations.
This does mean that CompilationWorkDirVariables now is functionally identical to CommonCompilationVariables, but it seems fine to leave them as two distinct classes to make it easy to handle any future changes where they diverge again.
The added test checks that MAP_DIR_PATH and WORK_DIR_PATH will be interpolated as expected in the context of compilation tools.
=> 4010: make MAP_DIR_PATH interpolation available for tools

app/resources/games/Halflife/GameConfig.cfg
These two textures are missing from the list of textures that only serve a functional purpose and are commonly transparent. NULL is especially important as these faces are skipped entirely during compiling. Making them transparent would seriously improve visibility in maps with complex geometry.
=> Half-Life: render NULL and ORIGIN textures transparent

common/src/TrenchBroomApp.cpp
Closes #3572.
This change doesn't fix the issues underlying the reports mentioned in #3572, but if it happens again, we will get more info.
=> If loading fails due to an unexpected error, let the crash handler deal with it

common/src/IO/AssimpParser.cpp, common/src/IO/AssimpParser.h
Fixes #4085
FBX files can have their own arbitrary axis transform. Assimp doesn't apply this transform automatically. It instead just stores it as metadata in the imported `aiScene`. Because of this, FBX files that don't already use the right coordinate system are oriented incorrectly in TB.
This PR reads the metadata, creates a new transformation matrix if there is metadata present that describes a different coordinate system, and applies it to our already-existing axis transform that converts the model from Assimp's coordinate system to ours.
See here the reproduction model from #4085 in this branch:
Here is a minimal game configuration containing models, entities and maps for testing.
Put the folder inside this zip in your TB games folder, and point the game directory in TB's settings …
=> Use FBX axis transform if listed in Assimp metadata.

common/src/Renderer/MapRenderer.cpp, common/src/Renderer/MapRenderer.h
This fixes a bug where the selected faces are not rendered. I introduced this problem in a recent commit.
=> Restore correct behavior when determining renderers

Build.md
I cannot maintain these instructions since I don't use Fedora.
Closes #4138.
=> 4138: Remove Fedora instructions from Build.md

common/src/View/MapDocument.cpp, common/test/src/View/MapDocumentTest.cpp
Closes #4166.
This PR makes it so that selecting a brush entity by a line number in the entity itself (e.g. one of its properties) and not one of the contained brushes, then all brushes in the entity are selected. Previously, nothing would be selected because brush entities are not selectable.
=> 4166: Select brushes in entity if selecting the entity by line number

common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h
Closes #4152.
The cause of the undo/redo menu items getting disabled is possibly that there is a transaction still running. Transactions get started for drags, and drags can end unexpectedly if the map view loses focus. We now explicitly cancel any drags when the map view loses focus to keep TB in a clean state.
=> 4152: Cancel dragging when map view loses focus

common/src/IO/MapReader.cpp, common/src/Model/EntityProperties.cpp, common/src/Model/EntityProperties.h, common/src/View/EntityPropertyModel.cpp, common/src/View/MapDocument.cpp, common/test/src/View/TransformNodesTest.cpp
Closes #4115.
The current logic for transforming a brush entity if all children are transformed relies on the selection status of the children. When rotating a group, the rotated brushes in the group are not selected, so the check would fail, and any brush entity in the group would not be transformed even though all of its children were. This PR addresses this flaw by explicitly examining the objects being transformed and not just the objects that are selected.
=> 4115: Transform grouped brush entities if all children are transformed

common/src/View/UVView.cpp, common/src/View/UVView.h
This is a follow up to https://github.com/TrenchBroom/TrenchBroom/pull/4169 so that the UV view will also cancel mouse drags when it loses focus.
=> 4152: Cancel dragging when UV view loses focus

common/src/Preference.cpp, common/src/Preference.h, common/src/PreferenceManager.cpp, common/src/PreferenceManager.h, common/test/src/PreferencesTest.cpp
Closes #4171.
This PR makes two changes: First, we delay writing the preferences after a change for 500ms to avoid writing the preferences file multiple times in a short time. Second, we use a lock file to synchronize access to the preferences file so that multiple instances of TB can write and read the preferences without interfering with each other.
=> 4171: Avoid simultaneous access to preferences file

common/src/IO/EntParser.cpp, common/src/IO/EntParser.h, common/test/src/IO/EntParserTest.cpp, common/test/src/IO/FgdParserTest.cpp
=> 4162: Don't crash if an ENT file is missing the box property

common/src/IO/MapReader.cpp, common/src/Model/Brush.cpp, common/src/Model/BrushFace.cpp, common/src/Model/GameImpl.cpp, common/src/Model/GroupNode.cpp, common/src/PreferenceManager.cpp, common/src/View/ClipTool.cpp, common/src/View/CreateComplexBrushTool.cpp, common/src/View/CreateSimpleBrushTool.cpp, common/src/View/ExtrudeTool.cpp, common/src/View/MapDocument.cpp, common/src/View/UpdateLinkedGroupsCommandBase.cpp, common/src/View/UpdateLinkedGroupsHelper.cpp, common/src/View/VertexToolBase.h, common/test/src/Model/tst_Brush.cpp, common/test/src/Model/tst_BrushFace.cpp, common/test/src/Model/tst_GroupNode.cpp, common/test/src/View/tst_UpdateLinkedGroupsHelper.cpp, common/test/src/tst_Preferences.cpp, lib/kdl/include/kdl/meta_utils.h, lib/kdl/include/kdl/result.h, lib/kdl/include/kdl/result_combine.h, lib/kdl/include/kdl/result_for_each.h, lib/kdl/include/kdl/result_io.h, lib/kdl/test/src/tst_result.cpp
This PR refactors the result types to give them a more functional API. We add a new function `result::or_else` to replace `result::map_errors` and `result::handle_errors`.
=> Refactor result types

common/src/View/MapViewBase.cpp, common/src/View/MapViewBase.h, common/src/View/UVView.cpp, common/src/View/UVView.h
Closes #4214.
Some windows managers deactivate views when the mouse cursor leaves them regardless of whether a drag is in progress. This would lead to mouse drags being cancelled inadvertedly because we cancel mouse drags when a map view or the UV view lose focus.
In this commit, we change it so that we cancel mouse drags when the window is deactivated.
=> 4214: Only cancel mouse drags if window deactivates

common/src/View/MapDocument.cpp, common/src/View/MapDocument.h, common/test/CMakeLists.txt, common/test/src/View/tst_Transaction.cpp
Closes #4152.
This is most likely the cause of undo / redo menu items getting disabled. The transaction stack was not actually cleared by the command manager when a transaction is canceled via `Transaction::cancel()`, and undo / redo is disabled while a transaction is ongoing.
=> 4152: Undo commands when cancelling a transaction

common/src/IO/AssimpParser.cpp, common/src/IO/MapReader.cpp, common/src/IO/ObjParser.cpp, common/src/IO/ResourceUtils.cpp, common/src/IO/SkinLoader.cpp, common/src/Model/Brush.cpp, common/src/Model/BrushBuilder.cpp, common/src/Model/GameImpl.cpp, common/src/Model/GroupNode.cpp, common/src/PreferenceManager.cpp, common/src/View/ClipTool.cpp, common/src/View/CreateComplexBrushTool.cpp, common/src/View/CreateSimpleBrushTool.cpp, common/src/View/ExtrudeTool.cpp, common/src/View/MapDocument.cpp, common/src/View/UpdateLinkedGroupsCommandBase.cpp, common/src/View/UpdateLinkedGroupsHelper.cpp, common/src/View/VertexToolBase.h, common/test/src/IO/tst_LoadTextureCollection.cpp, common/test/src/IO/tst_Quake3ShaderFileSystem.cpp, common/test/src/IO/tst_ReadFreeImageTexture.cpp, common/test/src/Model/tst_Brush.cpp, common/test/src/Model/tst_BrushRegression.cpp, common/test/src/Model/tst_GroupNode.cpp, common/test/src/tst_Preferences.cpp, lib/kdl/CMakeLists.txt, lib/kdl/include/kdl/result.h, lib/kdl/include/kdl/result_combine.h, lib/kdl/include/kdl/result_fold.h, lib/kdl/test/src/tst_result.cpp
This PR generally improves and simplifies the `kdl::result` type. It also moves its API closer to that of `std::expected` by supplying only the same monadic functions, specifically `and_then`, `or_else`, `transform` and `transform_error`. Furthermore, we also simplify handling of ranges of results by means of `kdl::fold_results`.
=> Improve result type

common/src/View/ExtrudeToolController.cpp, common/src/View/RotateObjectsToolController.cpp, common/src/View/ScaleObjectsToolController.cpp, common/src/View/ShearObjectsToolController.cpp, common/src/View/ToolController.cpp, common/src/View/ToolController.h, common/src/View/UVOriginTool.cpp, common/src/View/UVRotateTool.cpp, common/src/View/UVScaleTool.cpp, common/src/View/VertexToolController.cpp, common/src/View/VertexToolControllerBase.h
This seems to be an oversight from a previous refactoring where I introduced `DragTracker`. There weren't any bug reports, but I noticed that the extrude tool would print
```
updateProposedDragHandles called during a drag
```
in the console if shift was released during a drag.
=> Remove ToolController::anyToolDragging and use InputState::anyToolDragging

common/src/Model/GameFactory.cpp, common/src/View/MapDocument.cpp, common/test/src/IO/TestEnvironment.cpp, common/test/src/IO/TestEnvironment.h, common/test/src/Model/tst_GameFactory.cpp
This PR fixes two crashes:
- reading a game info comment can crash
- reloading a point file crashes when the point file no longer exists
These crashes were introduced during a large refactoring of the file IO code.
=> Fix fs refactor bugs

app/src/Main.cpp, common/src/PreferenceManager.h, common/src/TrenchBroomApp.cpp, common/test/src/RunAllTests.cpp, dump-shortcuts/src/Main.cpp
Closes #4171. This change ensures that the preference manager is destroyed before the application shuts down. This might eliminate a hang that occurs `QFileSystemWatcher` because the preference manager uses a `QFileSystemWatcher` to reload the preference file when it changes on disk. I don't know for sure, but it might be that the watcher must be destroyed before the app terminates.
=> 4171: Destroy preference manager in application destructor

common/src/IO/Tokenizer.h, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/test/src/IO/tst_NodeReader.cpp
=> 4270: Allow capital 'E' when parsing float number in scientific notation

common/src/TrenchBroomApp.cpp
Closes #4280
Hopefully the correct fix with nothing else this time.
=> Fix crash if there is no file specified in the command line.

common/src/Assets/EntityModel.cpp, common/test/CMakeLists.txt, common/test/src/Assets/tst_EntityModel.cpp
This change is again related to the Assimp model support. Assimp supports skins by offering "alternative textures" for each mesh in the model. The tricky part is (at least when loading HL1 models), each mesh will only have 1 texture if there are no alternatives for it, so if you set a skin index greater than 0, all the meshes disappear except for the ones with alternate skins. And if you specify a skin index that isn't valid, the model doesn't render at all.
This change simply allows the user to specify "invalid" skin indices, but it will default to using the first skin in the collection when the index is invalid. This has two advantages:
- the model doesn't disappear when the wrong skin index is specified (even though this might be a good way to point out to the user that something is …
=> Use the first skin if an unknown skin index is provided

common/src/IO/VirtualFileSystem.cpp, common/test/src/IO/TestFileSystem.cpp, common/test/src/IO/tst_FileSystem.cpp
=> 4294: Ensure that VirtualFileSystem::makeAbsolute checks path info

CMakeLists.txt, common/src/TrenchBroomApp.cpp, common/src/TrenchBroomApp.h, common/src/View/MapFrame.cpp, common/src/View/RecentDocumentListBox.cpp, common/src/View/RecentDocumentListBox.h, common/src/View/RecentDocuments.cpp, common/src/View/RecentDocuments.h, common/test/CMakeLists.txt, common/test/src/View/tst_RecentDocuments.cpp
Reimplementation of https://github.com/TrenchBroom/TrenchBroom/pull/4283
This PR filters the recent documents list dynamically. Entries are hidden from the list as soon as the corresponding file cannot be found.
=> Filter recent documents

vcpkg.json
This fixes a configure warning by updating to the latest assimp package from upstream.
=> Fix minizip warning

common/test/CMakeLists.txt
This frequently fails on macOS and I'm tired of trying to fix it. Let's see what happens without it. CI builds should not be affected.
=> Don't remove the test fixture directory

.github/workflows/ci.yml
Resolves #4372 
---
This PR aims to upgrade the version of macOS from version `11` to `12`.
This is likely a **breaking change** as the end users will need macOS 12 to run the application.
=> 4372: Upgrade macOS version from 11 to 12

app/resources/documentation/manual/index.md, app/src/Main.cpp, common/src/IO/SystemPaths.cpp, common/src/IO/SystemPaths.h, common/src/TrenchBroomApp.cpp, common/test/CMakeLists.txt, common/test/src/IO/tst_SystemPaths.cpp
Redirects the config files to the app directory when the `--portable` flag is passed at runtime.
This has been requested informally a couple of times in Discord - if there's a formal feature request issue I could not find it but I would be glad to link to it.
I took a very simple approach to make this work. If there's a more preferable way to handle bool for the portable state I would be glad to modify it.
=> Add portable flag to store config in app directory

Build.md
[Following the suggestion of @kduske](https://github.com/TrenchBroom/TrenchBroom/pull/4367#issuecomment-1806505595), I have moved the Docker support for the TrenchBroom source code and build process to a dedicated repository: https://github.com/jonathanlinat/dockerized-trenchbroom
The purpose of this PR is to modify the `Build.md` documentation to include a mention of this external, unofficial project.
=> ADHOC: Add Dockerized TrenchBroom reference to the Build.md file

app/resources/documentation/manual/_reset.css, app/resources/documentation/manual/_responsive.css, app/resources/documentation/manual/_specific.css, app/resources/documentation/manual/_specific.darkmode.css, app/resources/documentation/manual/_variables.css, app/resources/documentation/manual/_variables.darkmode.css, app/resources/documentation/manual/default.css, app/resources/documentation/manual/default.darkmode.css, app/resources/documentation/manual/template.html, app/resources/documentation/manual/toc_toggler.js
Resolves #4369
---
I've added a Dark Mode to the Reference Manual, making it easier to read at night. 
This mode changes automatically based on the computer's settings, thanks to a special feature in the coding. It tweaks some of the design elements without changing everything, keeping the overall look consistent.
To test it:
- Switch to this new version by checking out the branch.
- Build the Reference Manual.
- Use your browser's tools to switch between Light and Dark Mode and see the changes.
If your computer is already set to Dark Mode, you'll see the changes right away. You can also switch using the native feature included in the DevTools of the browsers.
Plus, I've changed the main font to something that's easier on the eyes.
@kduske @ericwa Let me know if the colours are fine for …
=> 4369: Introduce automatic dark mode (TrenchBroom Manual)

app/resources/games/Halflife/HalfLife.fgd
Adds the recently-added Assimp animation & skin support into the Half-Life FGD model definitions.
Related to:
Add support for GoldSrc #1140 
Add support for loading multiple skins to AssimpParser #4395 
Preview animation sequences for Assimp models #4396
=> Update the HL FGD for skins/animations

Build.md
qt5-default is missing from Debian-based distributions since Debian 12 (Bookworm) and its derivatives (including Ubuntu ≥ 21.04 cf. [launchpad bug 1926802][1]).
The CI was fixed in 3a5670ac2a850885d3962d9cf5cb99141604ece3 but the install instructions were not updated.
[1]: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1926802
=> Fix install instructions for Qt5

common/src/TrenchBroomApp.cpp
https://github.com/TrenchBroom/TrenchBroom/pull/4446 broken the ability to open multiple files that were passed on the command line, so we fix it here.
=> 4348: Simplify and fix behavior

common/src/View/Autosaver.cpp, common/src/View/Autosaver.h, common/test/src/IO/TestEnvironment.cpp, common/test/src/IO/TestEnvironment.h, common/test/src/View/tst_Autosaver.cpp, lib/kdl/include/kdl/vector_utils.h, lib/kdl/test/src/tst_vector_utils.cpp
Closes #4455. `Autosaver` got broken during a recent refactoring in a way that would make some backups disappear.
=> 4455: Fix autosaver cleanup

common/src/View/FourPaneMapView.cpp, common/src/View/MapFrame.cpp, common/src/View/Splitter.cpp, common/src/View/Splitter.h, common/src/View/ThreePaneMapView.cpp, common/src/View/TwoPaneMapView.cpp
The splitters are a bit hard to grab, so we make them wider. For selected splitters (mostly those in the inspectors), we add a little handle to make them more obvious, too.
=> Make splitters wider and draw a handle for selected splitters

.github/workflows/ci.yml, .github/workflows/clang-format-check.yml, .github/workflows/clean-commit.yml, CI-linux.sh
This PR aims to eliminate these warning messages in GitHub Actions as the entire infrastructure is migrating to Node 20:
The external actions must be upgraded to their newest available version.
**Reference**: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Upgrade external GitHub Actions actions (Node 20)

common/src/Assets/TextureCollection.cpp, common/src/Assets/TextureCollection.h, common/src/View/FaceInspector.cpp, common/src/View/FaceInspector.h, common/src/View/MapDocument.cpp, common/src/View/TextureBrowserView.cpp
Closes #4452 and #4491.
https://github.com/TrenchBroom/TrenchBroom/pull/4485 used the names of texture collections for filtering them, but the names are not unique. In this PR, we switch to using paths, which are unique.
Furthermore, we enable some texture collections by default. If the map has a `wad` property, then all texture collections are enabled by default. Otherwise, we enable only those texture collections that contain used textures by default.
=> 4452: Always enable used texture collections and show paths instead of names

common/src/View/MapDocument.cpp, common/test/src/View/tst_GroupNodes.cpp
=> 4481: Correctly set link IDs when duplicating objects in linked groups

.github/workflows/ci.yml
This reverts commit db71fb6ebe1850983ae65c6c603fe2eb613e9934.
Apparently this issue is now fixed or different in a new runner image that is being deployed.
=> 4528: Fix python install on macOS CI

app/resources/shader/TextureBrowser.fragsh, common/src/Assets/Texture.cpp, common/src/Assets/Texture.h, common/src/Assets/TextureManager.cpp, common/src/IO/LoadTextureCollection.cpp, common/src/Model/GameFileSystem.cpp, common/src/View/TextureBrowserView.cpp, common/test/src/IO/tst_LoadTextureCollection.cpp, common/test/src/Model/TestGame.cpp
Wad files used to be mounted under textures/<wadname>. This was useful
because it allows to filter the wad files in the texture browser
settings, and it also allowed us to show overridden textures in the
browser. At the same time, it complicates handling of texture names
because the texture names cannot be extracted from the file paths in a
uniform matter across different games.
We change this to simplify texture loading, in preparation for the new
material system.
=> 4519: Mount wads directly under /textures

common/src/View/CellView.cpp, common/src/View/MaterialBrowserView.cpp
Would otherwise crash when going to entity browser, or material browser respectively.
=> Fix uniform name mixups.

app/resources/documentation/manual/index.md
This PR fixes a small typo in the TrenchBroom manual in the Camera Navigation section.
=> Fix small typo in the manual

common/src/IO/DiskFileSystem.cpp, common/src/IO/DiskFileSystem.h, common/src/IO/DiskIO.cpp, common/src/IO/DiskIO.h, common/src/IO/FileSystem.cpp, common/src/IO/FileSystem.h, common/src/IO/VirtualFileSystem.cpp, common/src/IO/VirtualFileSystem.h, common/src/Model/GameConfig.cpp, common/src/Model/GameConfig.h, common/src/Model/GameFactory.cpp, common/src/Model/GameFactory.h, common/test/src/IO/tst_DiskFileSystem.cpp, common/test/src/IO/tst_DiskIO.cpp, common/test/src/Model/tst_GameFactory.cpp
Closes #4308.
The user config files were stored in a path derived from the game's display name as configured in the game config. This name could contain invalid characters which would crash TB when saving user config files.
This commit changes this behavior to store these files in a directory named after the directory that contains the game config - which must be a valid name. Existing config files are migrated automatically.
As a consequence, users switching between this version of TB and older versions might have to manually undo the migration to keep their user ocnfigurations intact.
=> 4308: Store user config files in a suitable location

common/src/View/EntityInspector.cpp
=> 3522: Don't set min sizes for main entity splitter

common/src/View/MapDocument.cpp
=> 4265: Allow UV / texture lock when editing inside of a linked group

common/src/ui/MapDocument.cpp, common/test/src/ui/tst_GroupNodes.cpp
=> 4616: When separating groups, propagate the changes to the containing linked groups

common/src/ui/CompilationTaskListBox.cpp
=> 4624: Don't crash when opening compilation task context menu

common/src/ui/Actions.cpp
=> 4630: Consider action context when checking if an action is enabled

common/src/render/MapRenderer.cpp
This fixes an issue where a decal occludes the label of a selected entity.
Closes #4419 and #3553.
=> Render decals and links first

common/src/render/EntityRenderer.cpp
=> 4631: Fix use of wrong base vector for rotation angle indicator

common/src/mdl/BrushFace.cpp, common/test/src/mdl/tst_Brush.cpp
Closes #4647.
This broke in f24ba9427d02f97336221db738c0ced5e6dab091.
=> 4647: Keep textures aligned after CSG convex merge

common/src/ui/UVEditor.cpp
=> 4657: Set default face attributes when resetting UV in UV editor

common/src/ui/MapDocument.cpp, common/test/src/ui/tst_GroupNodes.cpp
=> 4654: Don't unlink nested linked groups when separating linked groups

common/src/ui/SelectionTool.cpp, common/test/src/ui/tst_SelectionTool.cpp
When hiding a material (eg. `NULL` or `SKIP`) you can select brushes through faces that are hidden but you cannot select faces, shift-clicking through hidden materials is a no-op.
This fixes the issue and allows the user to select faces as well as brushes through hidden materials.
=> Allow selecting faces through hidden materials

CI-macos.sh, CMakeLists.txt, common/test/src/io/TestEnvironment.cpp, common/test/src/io/TestEnvironment.h
Otherwise, this throws hard to diagnose errors in the destructor that show up only when using ASAN (and might even end up deleting important files).
=> Throw an exception when creating a TestEnvironment with an absolute path

common/src/ui/MapDocument.cpp
This PR addresses the first item from #4552 where default properties are not applied to the `worldspawn` entity when creating a new map and `setDefaultProperties` is set. The second item should probably be tracked in a separate issue.
I was thinking in moving `setWorldDefaultProps()` to `setWorld()`, after the line `loadAssets()` but that would require an extra parameter to check if it's loading a map or creating a new one.
Thank you very much!
=> Apply default properties for worldspawn on new map

common/src/render/MapRenderer.cpp
Closes #4705.
Hidden faces are not hidden when they're in a locked layer. This PR fixes that.
Repro map with an unlocked brush encased in a locked brush, using a single SKIP face on each brush:
```
// Game: Half-Life
// Format: Valve
// entity 0
{
"mapversion" "220"
"classname" "worldspawn"
// brush 0
{
( -16 -16 -128 ) ( -16 -15 -128 ) ( -16 -16 -127 ) __TB_empty [ 0 1 0 0 ] [ 0 0 -1 0 ] 0 1 1
( 16 -16 -128 ) ( 16 -16 -127 ) ( 17 -16 -128 ) SKIP [ 1 0 0 0 ] [ 0 0 -1 0 ] 0 1 1
( 16 -16 -128 ) ( 17 -16 -128 ) ( 16 -15 -128 ) __TB_empty [ 1 0 0 0 ] [ 0 -1 0 0 ] 0 1 1
( 96 16 64 ) ( 96 17 64 ) ( 97 16 64 ) __TB_empty [ 1 0 0 0 ] [ 0 -1 0 0 ] 0 1 1
( 96 16 -112 ) ( 97 16 -112 ) ( 96 16 -111 ) __TB_empty [ 1 0 0 0 ] [ 0 0 -1 0 ] 0 1 1
( 96 16 -112 ) ( 96 16 -111 ) ( 96 17 -112 ) __TB_empty [ 0 …
```
=> Hide hidden faces even in locked layers

CI-macos.sh, CMakeLists.txt
The macOS deployment target should be set for CI builds only. On developer machines, it's better to drop it so that it will be defaulted to whatever system version the machine is running. This will avoid lots of warnings about mismatching object files.
=> Update vcpkg and drop CMAKE_OSX_DEPLOYMENT_TARGET from CMakeLists

CI-linux.sh
=> 4715: Remove `-` from `-ldd` command (`CI-linux.sh`)

common/CMakeLists.txt, common/src/TrenchBroomApp.cpp, common/src/io/LoadMaterialCollections.cpp, common/src/io/MapHeader.cpp, common/src/io/MapHeader.h, common/src/mdl/GameFactory.cpp, common/src/mdl/GameFactory.h, common/src/ui/GameDialog.cpp, common/src/ui/GameDialog.h, common/src/ui/MapDocument.cpp, common/test/CMakeLists.txt, common/test/src/io/tst_MapHeader.cpp, common/test/src/mdl/tst_GameFactory.cpp, common/test/src/ui/tst_Autosaver.cpp, common/test/src/ui/tst_MapDocument.cpp, lib/kdl/include/kdl/result.h, lib/kdl/test/src/tst_result.cpp
Closes https://github.com/TrenchBroom/TrenchBroom/issues/4718
@eGax please give this a try
=> Restore game detection

.github/workflows/clang-tidy-check.yml
Ubuntu 24.04 uses a different version of the clang tools than what is in the dev-tools repo, causing issues with clang-format.
=> Run cpplinter checks on Ubuntu 22.04

app/resources/games/DDayNormandy/GameConfig.cfg
The main changes are as follows :
- Added map compiler tool path options under preferences.
- Add brush/face options in line with TB's Quake 2 cfg (being based on same engine/map format).
- Fixed unused contentflags being shown in TB, now hidden.
=> Update GameConfig.cfg fixes & additions for DDAY

common/src/io/AseLoader.cpp, common/test/src/io/tst_AseLoader.cpp, lib/kdl/include/kdl/path_utils.h, lib/kdl/test/src/tst_path_utils.cpp
Closes #4763.
ASE files often contain material paths with backlashes as directory separators. Since a backslash is a valid path character on POSIX systems, such paths are not parse correctly. We convert the backslashes to forward slashes on such systems.
=> Convert windows paths in ASE files

.github/workflows/ci.yml, CI-linux.sh, CI-macos.sh
The ASAN build was incorrectly using a Release build, and, on top of that, it was trying to sign / notarize the package.
=> Fix ASAN build

.github/workflows/ci.yml, app/CMakeLists.txt, app/cmake/AppImageGenerator.cmake.in
This is necessary for the auto update component because it simplifies unpacking and installing the update. This change also renames the AppImage to `TrenchBroom.AppImage`. Like on other platforms, the version information is only part of the zip archive filename.
=> Distribute AppImage builds in a zip archive

common/src/mdl/Polyhedron_Misc.h
This fixes a crash that happens when creating a very flat brush such that deleting short edges essentially destroys the brush. v1 gets deleted, and since the check whether v2 was deleted relies on v1, we crashed.
Closes #4536
=> Fix crash when extruding a brush

common/src/io/MdxLoader.cpp, common/src/mdl/ModelDefinition.cpp
There were two bugs in the MDX loader which actually prevented it from working at all. Additionally, TB did not load model paths correctly from entity definitions on macOS and Linux if they contained Windows path separators.
Closes #4809.
=> Fix loading MDX models

common/src/ui/CompilationRun.cpp, common/src/ui/CompilationRunner.cpp, common/test/src/ui/tst_CompilationRunner.cpp
=> Allow either '/' or '\' as path separators for paths used in compilation profiles

.github/workflows/ci.yml, CI-linux.sh, CI-macos.sh, CI-windows.bat, CMakeLists.txt, app/CMakeLists.txt, cmake/Utils.cmake, lib/kdl/test/CMakeLists.txt, lib/vm/test/CMakeLists.txt
Originally, this PR was supposed to enable ccache on Windows. Eventually it turned out though that caching ccache's cache on github thrashes the vcpkg binary cache, so we don't gain much in the end. That's why the last commit disables ccache on CI again. I decided to keep the rest of the PR because the other changes are useful on their own.
=> Enable ccache on Windows

CMakeLists.txt, app/CMakeLists.txt, common/CMakeLists.txt, common/src/TrenchBroomApp.cpp, common/src/el/Value.cpp, common/src/mdl/EntityColor.cpp, common/src/mdl/EntityRotation.cpp, common/src/ui/ClipTool.cpp, common/src/ui/MapFrame.cpp, common/src/ui/MapInspector.cpp, common/src/ui/QtUtils.h, common/src/ui/RotateObjectsHandle.cpp, common/src/ui/RotateObjectsToolPage.cpp, common/src/ui/ScaleObjectsToolPage.cpp, common/test/CMakeLists.txt, dump-shortcuts/CMakeLists.txt, lib/kdl/CMakeLists.txt, lib/kdl/src/kdl/string_utils.cpp, lib/kdl/src/kdl/string_utils.h, lib/kdl/test/src/tst_string_utils.cpp, lib/vm/CMakeLists.txt, lib/vm/include/vm/from_chars.h, lib/vm/include/vm/mat_io.h, lib/vm/include/vm/vec_io.h, vcpkg.json
Number formatting and parsing in the UI is currently inconsistent. Some controls use the current locale settings, (e.g. using `,` as the decimal separator on a German system), and some don't. With this PR, all UI widgets will use the current locale when editing numbers.
A non-obvious exception are numbers in the entity attributes grid, but here, we are actually editing strings, so formatting doesn't apply. This might change in the future.
Closes #3933
=> Format numbers using the current locale in the UI

common/src/ui/UpdateVersion.cpp, common/test/src/ui/tst_UpdateVersion.cpp
The updater didn't consider release candidates when selecting an asset to download. This resulted in a failed update when a newer release candidate version is available.
=> Fix asset selection for auto updater

.github/workflows/ci.yml
github action cache has been disabled as a caching provider for the vcpkg binary cache. GitHub packages is an alternative, but requires nuget on all platforms.
=> Replace github action cache with GitHub packages

.github/workflows/ci.yml, .github/workflows/clang-tidy-check.yml, .github/workflows/clean-commit.yml
- Use github action token for nuget repository caches; this fixes a problem where the cache couldn't be restored.
- Use the nuget repository for the clang-tidy action; this was forgotten and now it didn't cache vcpkg anymore.
- Don't install cmake on macOS, it's already installed and homebrew complained about it.
- Unrelated: macOS builds could no longer be signed because I had to accept changes to Apple's TOS.
=> Fix CI builds

.github/workflows/ci.yml, Build.md, common/src/io/MapFileSerializer.cpp, common/src/ui/Autosaver.cpp, common/src/ui/MapDocument.cpp, common/src/ui/MapViewBase.cpp, common/src/ui/ModEditor.cpp, common/test/src/mdl/tst_BezierPatch.cpp, common/test/src/ui/tst_QtUtils.cpp, common/test/src/ui/tst_UpdateVersion.cpp, lib/kdl/src/kdl/range_io.h, lib/kdl/src/kdl/set_adapter.h, lib/kdl/src/kdl/vector_set.h, lib/upd/test/src/upd/tst_GithubApi.cpp, vcpkg.json
By default, we compile with GCC 11, but this version of GCC doesn't properly support the ranges library.
=> Use GCC 13 on Ubuntu

lib/kdl/CMakeLists.txt, lib/upd/CMakeLists.txt
Both kdl and upd are only really used internally and never linked so explicitly setting it as static ensures it will be included directly in the final executable
=> Update kdl and upd to be static libraries

.github/workflows/ci.yml
The macos-13 image will be deprecated, and we want to use more C++20 features, for which Xcode16 has better support. Xcode16 is not available on macos-13.
=> Switch to macos-15 for macOS intel builds
